import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createControlPlane } from "../src/app.js";
import { createTestConfig } from "../src/config.js";

const origin = "http://127.0.0.1:4317"; const roots: string[] = [];
afterEach(() => { while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }); });
const fixture = () => { const root = mkdtempSync(join(tmpdir(), "chubz-m10-routing-test-")); roots.push(root); const config = { ...createTestConfig(root), logLevel: "fatal" as const }; return { config, control: createControlPlane(config) }; };
const authenticate = async (control: ReturnType<typeof createControlPlane>) => { await control.app.ready(); await control.app.inject({ method: "POST", url: "/v1/auth/bootstrap", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const login = await control.app.inject({ method: "POST", url: "/v1/auth/login", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const cookie = String(login.headers["set-cookie"]); const principal = control.auth.authenticate(cookie.split(";", 1)[0]?.split("=", 2)[1]); if (!principal) throw new Error("authentication failed"); return { cookie, csrf: (login.json() as { csrfToken: string }).csrfToken, principal }; };
const headers = (auth: Awaited<ReturnType<typeof authenticate>>) => ({ origin, cookie: auth.cookie, "x-csrf-token": auth.csrf, "content-type": "application/json" });

function seedReadyCodex(control: ReturnType<typeof createControlPlane>): void {
  const hash = "1".repeat(64); const at = new Date().toISOString(); const evidenceId = `evidence.codex.sha256.${hash}`;
  const readiness = { coordinationVersion: "1.0", readinessId: `readiness.codex.sha256.${hash}`, workerId: "codex-cli", adapterId: "codex-cli-adapter", connectorTier: "cli", providerId: "openai", runtimeId: "codex-cli-runtime", installedVersion: "1.2.3", executableId: "codex-native", executableHash: `sha256:${"2".repeat(64)}`, authenticationState: "authenticated", sandboxCapability: "validated", noninteractiveCapability: "validated", structuredOutputCapability: "validated", cancellationCapability: "validated", resumeCapability: "validated", healthStatus: "healthy", quotaVisibility: "unknown", freezeState: "enabled", capabilityProbeAt: at, readinessState: "ready", capabilities: [{ capability: "code-write", assurance: "validated", evidenceRef: evidenceId }, { capability: "review", assurance: "validated", evidenceRef: evidenceId }], evidenceRefs: [evidenceId] };
  const evidence = { evidenceId, compatibility: "passed", drift: false, windowsSandbox: { configuredImplementation: "elevated", selectedImplementation: "elevated", elevatedProbeResult: "passed", elevatedFailureClassification: null, fallbackSelected: false, fallbackCanaryResult: "not-required", assurance: "elevated" } };
  control.database.connection.prepare("INSERT INTO m5_adapter_readiness(readiness_id,worker_id,adapter_id,readiness_state,freeze_state,readiness_json,evidence_json,recorded_at) VALUES(?,?,?,?,?,?,?,?)").run(readiness.readinessId, readiness.workerId, readiness.adapterId, readiness.readinessState, readiness.freezeState, JSON.stringify(readiness), JSON.stringify(evidence), at);
}
const createCodex = async (control: ReturnType<typeof createControlPlane>, auth: Awaited<ReturnType<typeof authenticate>>, suffix: string) => { seedReadyCodex(control); const response = await control.app.inject({ method: "POST", url: "/v1/ui/tasks", headers: headers(auth), payload: { idempotencyKey: `task-create:${suffix}`, projectId: `project-${suffix}`, instructions: "Update the bounded README section", workerId: "codex-cli", scopeMode: "workspace-write", allowedPaths: ["README.md"], timeoutSec: 600 } }); expect(response.statusCode).toBe(201); return response.json() as { taskId: string; attemptId: string; operationId: string; version: number; state: string }; };

describe("M10 routing, quota, confirmation, and fallback authority", () => {
  it("requires a deterministic confirmed route before existing approval and grant gates", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "main-flow");
    const direct = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/approve-dispatch`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "approve:no-routing" } }); expect(direct.statusCode).toBe(409);
    const generated = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:generate-main" } }); expect(generated.statusCode).toBe(201); const recommendation = generated.json() as Record<string, unknown>;
    expect(recommendation).toMatchObject({ recommendationVersion: "m10.routing/v1", riskClass: "medium", selected: { workerId: "codex-cli", adapterId: "codex-cli-adapter" }, automaticDispatch: false, automaticFallback: false }); expect(generated.body).not.toContain("Update the bounded README");
    const candidates = recommendation["candidates"] as Array<Record<string, unknown>>; expect(candidates[0]).toMatchObject({ workerId: "codex-cli", eligible: true, costClass: "estimated-low" }); expect(candidates[1]).toMatchObject({ workerId: "manual-relay", eligible: false }); expect(candidates[1]?.["rejectionReasons"]).toContain("code-write:unavailable");
    const replay = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:generate-main" } }); expect(replay.json()).toEqual(recommendation);
    const conflict = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version + 1, idempotencyKey: "routing:generate-main" } }); expect(conflict.statusCode).toBe(409);
    const recommendationId = String(recommendation["recommendationId"]); const selected = recommendation["selected"] as Record<string, unknown>;
    const tampered = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations/${recommendationId}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:confirm-tampered", recommendationVersion: recommendation["recommendationVersion"], inputDigest: recommendation["inputDigest"], selectedWorkerId: "manual-relay", selectedAdapterId: "manual-relay" } }); expect(tampered.statusCode).toBe(409);
    const confirmRequest = { method: "POST" as const, url: `/v1/ui/tasks/${task.taskId}/routing/recommendations/${recommendationId}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:confirm-main", recommendationVersion: recommendation["recommendationVersion"], inputDigest: recommendation["inputDigest"], selectedWorkerId: selected["workerId"], selectedAdapterId: selected["adapterId"] } }; const confirmed = await Promise.all([control.app.inject(confirmRequest), control.app.inject(confirmRequest)]); expect(confirmed.every((response) => response.statusCode === 200)).toBe(true); expect(confirmed[0]!.json()).toMatchObject({ dispatchCreated: false, capabilityGranted: false, nextGate: "existing-owner-approval-and-capability-grant" }); expect(confirmed[1]!.json()).toEqual(confirmed[0]!.json()); expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m10_route_confirmations WHERE task_id=?").get(task.taskId) as { n: number }).n).toBe(1);
    expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m4_grants WHERE task_id=?").get(task.taskId) as { n: number }).n).toBe(0);
    const approved = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/approve-dispatch`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "approve:after-routing" } }); expect(approved.statusCode).toBe(200); expect(approved.json()).toMatchObject({ grant: { status: "issued", singleUse: true } });
    expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m8_operational_events WHERE source='m10_routing'").get() as { n: number }).n).toBeGreaterThanOrEqual(2); await control.close();
  });

  it("rejects unauthenticated, wrong-origin, stale, tampered, duplicate, and cross-owner routing mutations", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "security"); const url = `/v1/ui/tasks/${task.taskId}/routing/recommendations`;
    expect((await control.app.inject({ method: "POST", url, headers: { origin, "content-type": "application/json" }, payload: { expectedVersion: task.version, idempotencyKey: "routing:unauthorized" } })).statusCode).toBe(403);
    expect((await control.app.inject({ method: "POST", url, headers: { ...headers(auth), origin: "http://evil.invalid" }, payload: { expectedVersion: task.version, idempotencyKey: "routing:evil-origin" } })).statusCode).toBe(403);
    expect((await control.app.inject({ method: "POST", url, headers: { origin, cookie: auth.cookie, "content-type": "application/json" }, payload: { expectedVersion: task.version, idempotencyKey: "routing:missing-csrf" } })).statusCode).toBe(403);
    const policy = await control.app.inject({ method: "PUT", url: "/v1/ui/projects/project-security/routing-policy", headers: headers(auth), payload: { expectedVersion: 0, idempotencyKey: "routing:policy-security", allowManualRelay: false, preferLowerCost: true, requireStrongSandboxForHighRisk: true, maximumQuotaAgeSeconds: 300, preferredWorkers: ["codex-cli", "manual-relay"], allowLowRiskConfirmation: true } }); expect(policy.statusCode).toBe(200); expect(policy.json()).toMatchObject({ version: 1, policy: { allowManualRelay: false } }); expect((await control.app.inject({ method: "PUT", url: "/v1/ui/projects/project-security/routing-policy", headers: headers(auth), payload: { expectedVersion: 1, idempotencyKey: "routing:policy-injection", preferredWorkers: ["arbitrary-provider"] } })).statusCode).toBe(400);
    const generated = (await control.app.inject({ method: "POST", url, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:security-generate" } })).json() as Record<string, unknown>; control.database.connection.prepare("UPDATE tasks SET version=version+1 WHERE task_id=?").run(task.taskId);
    const stale = await control.app.inject({ method: "POST", url: `${url}/${String(generated["recommendationId"])}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:security-confirm", recommendationVersion: generated["recommendationVersion"], inputDigest: generated["inputDigest"], selectedWorkerId: "codex-cli", selectedAdapterId: "codex-cli-adapter" } }); expect(stale.statusCode).toBe(409); expect((control.database.connection.prepare("SELECT status FROM m10_recommendations WHERE recommendation_id=?").get(generated["recommendationId"]) as { status: string }).status).toBe("stale");
    expect(() => control.routing.snapshot({ ...auth.principal, administratorId: "other-owner" })).toThrow(); await control.close();
  });

  it("persists and owner-confirms a fallback plan without creating an attempt, grant, retry, or dispatch", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "fallback-plan"); const generated = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:fallback-generate" } }); expect(generated.statusCode).toBe(201);
    const response = await control.app.inject({ method: "GET", url: `/v1/ui/tasks/${task.taskId}/routing/fallback`, headers: { cookie: auth.cookie } }); expect(response.statusCode).toBe(200); const fallback = response.json() as Record<string, unknown>; const options = fallback["options"] as Array<Record<string, unknown>>; const optionIndex = options.findIndex((option) => option["kind"] === "owner-intervention"); expect(fallback).toMatchObject({ status: "proposed", automaticExecution: false }); expect(optionIndex).toBeGreaterThanOrEqual(0);
    const before = control.database.connection.prepare("SELECT (SELECT COUNT(*) FROM task_attempts WHERE task_id=?) AS attempts,(SELECT COUNT(*) FROM m4_grants WHERE task_id=?) AS grants,(SELECT COUNT(*) FROM m4_dispatch_queue WHERE task_id=?) AS dispatches").get(task.taskId, task.taskId, task.taskId); const confirmed = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/fallback/${String(fallback["fallbackPlanId"])}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, optionIndex, idempotencyKey: "routing:fallback-confirm" } }); expect(confirmed.statusCode).toBe(200); expect(confirmed.json()).toMatchObject({ status: "confirmed", dispatchCreated: false, attemptCreated: false, nextRequiredAction: "create-new-immutable-attempt-through-normal-lifecycle" }); const after = control.database.connection.prepare("SELECT (SELECT COUNT(*) FROM task_attempts WHERE task_id=?) AS attempts,(SELECT COUNT(*) FROM m4_grants WHERE task_id=?) AS grants,(SELECT COUNT(*) FROM m4_dispatch_queue WHERE task_id=?) AS dispatches").get(task.taskId, task.taskId, task.taskId); expect(after).toEqual(before); expect((control.routing.snapshot(auth.principal)["fallbackPlans"] as Array<Record<string, unknown>>)[0]).toMatchObject({ taskId: task.taskId, status: "confirmed", automaticExecution: false }); await control.close();
  });

  it("keeps stale and owner-attested quota visible and blocks confirmation on stale quota", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "quota");
    const observedAt = new Date(Date.now() + 1_000).toISOString(); control.routing.recordQuotaObservationSystem({ observationId: "quota-owner-attested", workerId: "codex-cli", adapterId: "codex-cli-adapter", state: "constrained", confidence: "low", source: "owner-attested", observedAt, expiresAt: new Date(Date.now() - 1_000).toISOString(), resetAt: null, remaining: 1, limitation: "owner estimate" });
    const generated = (await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:quota-generate" } })).json() as Record<string, unknown>; const selected = generated["selected"] as Record<string, unknown>;
    const candidate = (generated["candidates"] as Array<Record<string, unknown>>)[0]!; expect(candidate["quota"]).toMatchObject({ state: "stale", confidence: "low", fresh: false }); expect(candidate["limitations"]).toContain("The quota observation is stale and cannot establish current availability.");
    const confirm = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations/${String(generated["recommendationId"])}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:quota-confirm", recommendationVersion: generated["recommendationVersion"], inputDigest: generated["inputDigest"], selectedWorkerId: selected["workerId"], selectedAdapterId: selected["adapterId"] } }); expect(confirm.statusCode).toBe(409);
    const observations = await control.app.inject({ method: "GET", url: "/v1/ui/routing/observations", headers: { cookie: auth.cookie } }); expect(observations.body).toContain("owner-attested"); expect(observations.body).toContain("stale"); await control.close();
  });

  it("fails closed when the authoritative readiness probe is stale", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "stale-readiness"); const row = control.database.connection.prepare("SELECT readiness_id,readiness_json FROM m5_adapter_readiness WHERE worker_id='codex-cli' ORDER BY recorded_at DESC LIMIT 1").get() as { readiness_id: string; readiness_json: string }; const readiness = JSON.parse(row.readiness_json) as Record<string, unknown>; readiness["capabilityProbeAt"] = "2026-01-01T00:00:00.000Z"; control.database.connection.prepare("UPDATE m5_adapter_readiness SET readiness_json=? WHERE readiness_id=?").run(JSON.stringify(readiness), row.readiness_id);
    const generated = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:stale-readiness" } }); expect(generated.statusCode).toBe(201); const value = generated.json() as Record<string, unknown>; expect(value).toMatchObject({ selected: null, status: "no-eligible-route" }); expect((value["candidates"] as Array<Record<string, unknown>>)[0]).toMatchObject({ readiness: "unknown", eligible: false }); await control.close();
  });

  it("structurally refuses out-of-scope work regardless of readiness or quota", async () => {
    const { control } = fixture(); const auth = await authenticate(control); seedReadyCodex(control); const taskId = "task-structural-refusal"; const attemptId = "attempt-structural-refusal"; const operationId = "operation-structural-refusal"; const at = new Date().toISOString(); const action = { operation: "worker.dispatch", policyClass: "production-deployment", target: { resourceId: "codex-cli" } };
    control.database.connection.prepare("INSERT INTO tasks(task_id,project_id,state,attempt_id,updated_at,version,created_at,current_operation_id) VALUES(?,?,'AWAITING_DISPATCH',?,?,2,?,?)").run(taskId, "project-structural", attemptId, at, at, operationId); control.database.connection.prepare("INSERT INTO task_attempts(attempt_id,task_id,attempt_sequence,action_json,action_digest,input_text,created_at) VALUES(?,?,1,?,?,?,?)").run(attemptId, taskId, JSON.stringify(action), `sha256:${"4".repeat(64)}`, "sensitive production request", at);
    const response = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: 2, idempotencyKey: "routing:structural-refusal" } }); expect(response.statusCode).toBe(201); expect(response.json()).toMatchObject({ riskClass: "owner-only", selected: null, status: "no-eligible-route" }); expect((response.json() as Record<string, unknown>)["policyRules"]).toContain("M10-RISK-OWNER-PRODUCTION"); await control.close();
  });

  it("never activates fallback for execution-unknown or cancellation uncertainty", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "unknown"); control.database.connection.prepare("UPDATE tasks SET state='BLOCKED',blocked_context_json=?,version=version+1 WHERE task_id=?").run(JSON.stringify({ blockedReason: "execution-unknown", cancellationState: "unconfirmed" }), task.taskId);
    const generated = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version + 1, idempotencyKey: "routing:unknown-generate" } }); expect(generated.statusCode).toBe(201);
    const fallback = await control.app.inject({ method: "GET", url: `/v1/ui/tasks/${task.taskId}/routing/fallback`, headers: { cookie: auth.cookie } }); expect(fallback.json()).toMatchObject({ status: "unavailable", options: [], automaticExecution: false });
    const fallbackId = String((fallback.json() as Record<string, unknown>)["fallbackPlanId"]); const confirmed = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/fallback/${fallbackId}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version + 1, optionIndex: 0, idempotencyKey: "routing:unknown-fallback" } }); expect(confirmed.statusCode).toBe(409); expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m4_dispatch_queue WHERE task_id=?").get(task.taskId) as { n: number }).n).toBe(0); await control.close();
  });

  it("blocks generation and confirmation under emergency stop and never auto-resumes after release", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await createCodex(control, auth, "stop"); const generatedResponse = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:stop-before" } }); const generated = generatedResponse.json() as Record<string, unknown>; const selected = generated["selected"] as Record<string, unknown>; const stopResponse = await control.app.inject({ method: "POST", url: "/v1/ui/emergency-stops", headers: headers(auth), payload: { scopeType: "project", projectId: "project-stop", reason: "routing stop", expectedVersion: 0, idempotencyKey: "routing:stop-activate" } }); expect(stopResponse.statusCode).toBe(201); const stop = stopResponse.json() as Record<string, unknown>;
    const blockedGenerate = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:stop-generate" } }); expect(blockedGenerate.statusCode).toBe(503); const blockedConfirm = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations/${String(generated["recommendationId"])}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:stop-confirm", recommendationVersion: generated["recommendationVersion"], inputDigest: generated["inputDigest"], selectedWorkerId: selected["workerId"], selectedAdapterId: selected["adapterId"] } }); expect(blockedConfirm.statusCode).toBe(503); const released = await control.app.inject({ method: "POST", url: `/v1/ui/emergency-stops/${String(stop["stopId"])}/release`, headers: headers(auth), payload: { expectedVersion: 1, idempotencyKey: "routing:stop-release" } }); expect(released.statusCode).toBe(200); expect(released.json()).toMatchObject({ autoResumed: false }); expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m10_route_confirmations WHERE task_id=?").get(task.taskId) as { n: number }).n).toBe(0); expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m4_dispatch_queue WHERE task_id=?").get(task.taskId) as { n: number }).n).toBe(0); await control.close();
  });

  it("reconciles restart without duplicating recommendation, confirmation, dispatch, or fallback", async () => {
    const value = fixture(); const auth = await authenticate(value.control); const task = await createCodex(value.control, auth, "restart"); const concurrent = await Promise.all(["one", "two", "three"].map((suffix) => value.control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: `routing:restart-${suffix}` } }))); expect(concurrent.every((response) => response.statusCode === 201)).toBe(true); expect(new Set(concurrent.map((response) => String((response.json() as Record<string, unknown>)["recommendationId"]))).size).toBe(1); const generated = concurrent[0]!.json() as Record<string, unknown>; const selected = generated["selected"] as Record<string, unknown>; await value.control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/routing/recommendations/${String(generated["recommendationId"])}/confirm`, headers: headers(auth), payload: { expectedVersion: task.version, idempotencyKey: "routing:restart-confirm", recommendationVersion: generated["recommendationVersion"], inputDigest: generated["inputDigest"], selectedWorkerId: selected["workerId"], selectedAdapterId: selected["adapterId"] } });
    const before = value.control.database.connection.prepare("SELECT (SELECT COUNT(*) FROM m10_recommendations) AS recommendations,(SELECT COUNT(*) FROM m10_route_confirmations) AS confirmations,(SELECT COUNT(*) FROM m10_fallback_plans) AS fallbacks,(SELECT COUNT(*) FROM m4_dispatch_queue) AS dispatches").get(); await value.control.close(); const restarted = createControlPlane(value.config); const after = restarted.database.connection.prepare("SELECT (SELECT COUNT(*) FROM m10_recommendations) AS recommendations,(SELECT COUNT(*) FROM m10_route_confirmations) AS confirmations,(SELECT COUNT(*) FROM m10_fallback_plans) AS fallbacks,(SELECT COUNT(*) FROM m4_dispatch_queue) AS dispatches").get(); expect(after).toEqual(before); expect((restarted.database.connection.prepare("SELECT status FROM m10_recommendations WHERE recommendation_id=?").get(generated["recommendationId"]) as { status: string }).status).toBe("confirmed"); await restarted.close();
  });
});
