import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import type { M11RuntimeConfiguration } from "../src/m11-config.js";
import { clearStaleRuntimePidRecords, inspectRuntime, startRuntime, stopRuntime, type ProcessIdentity, type RuntimeProcessAdapter } from "../src/m11-runtime-manager.js";

const roots: string[] = []; afterEach(() => { delete process.env["CHUBZ_TEST_SESSION_SECRET"]; delete process.env["UNRELATED_SECRET"]; while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }); });
const sha = (value: string): string => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const configFor = (root: string, port: number): M11RuntimeConfiguration => Object.freeze({ configVersion: 1, controlPlane: Object.freeze({ host: "127.0.0.1", port, allowedOrigin: `http://127.0.0.1:${port}`, sessionSecretRef: "environment:CHUBZ_TEST_SESSION_SECRET" }), bridge: Object.freeze({ endpoint: `ws://127.0.0.1:${port}/v1/bridge/ws`, enrollmentIdentity: "local-bridge", heartbeatIntervalMs: 10_000 }), paths: Object.freeze({ approvedManagedRoots: Object.freeze([root]), managedDataRoot: join(root, "runtime-data"), databaseFile: "control-plane.sqlite", logsDirectory: "operational-logs", supportBundlesDirectory: "support-bundles", packagesDirectory: "release-packages" }), bounds: Object.freeze({ logMaxBytes: 65_536, logRetentionFiles: 2, captureMaxBytes: 65_536, packageMaxBytes: 1_048_576, packageMaxFiles: 100, supportBundleMaxBytes: 1_048_576, supportBundleMaxFiles: 16, storageWarningPercent: 90 }), retention: Object.freeze({ operationalLogDays: 14, resolvedAlertDays: 30, supportBundleDays: 30, packagingStagingHours: 24 }), projects: Object.freeze([]), display: Object.freeze({ productName: "CHUBZ", environmentLabel: "Test" }) });
const freePort = async (): Promise<number> => new Promise((done, fail) => { const server = createServer(); server.once("error", fail); server.listen(0, "127.0.0.1", () => { const address = server.address(); if (!address || typeof address === "string") return fail(new Error("port unavailable")); server.close(() => done(address.port)); }); });

class FakeProcesses implements RuntimeProcessAdapter {
  public identities = new Map<number, ProcessIdentity>(); public terminated: number[] = []; public environments: NodeJS.ProcessEnv[] = []; public spawnCount = 0; public failSpawnAt = 0; private nextPid = 40_000;
  public inspect(pid: number): Promise<ProcessIdentity | null> { return Promise.resolve(this.identities.get(pid) ?? null); }
  public spawn(executable: string, args: readonly string[], environment: NodeJS.ProcessEnv): Promise<number> { this.spawnCount += 1; this.environments.push(environment); if (this.failSpawnAt === this.spawnCount) return Promise.reject(new Error("synthetic spawn failure")); const pid = this.nextPid++; this.identities.set(pid, Object.freeze({ pid, executablePath: resolve(executable), commandDigest: sha([executable, ...args].join("\0")), processStartedAt: new Date(1_700_000_000_000 + pid).toISOString() })); return Promise.resolve(pid); }
  public terminateKnown(identity: ProcessIdentity): Promise<Readonly<{ terminated: boolean; proven: boolean; observedPids: readonly number[]; livePids: readonly number[] }>> { if (this.identities.get(identity.pid) !== identity) return Promise.reject(new Error("identity mismatch")); this.identities.delete(identity.pid); this.terminated.push(identity.pid); return Promise.resolve(Object.freeze({ terminated: true, proven: true, observedPids: Object.freeze([identity.pid]), livePids: Object.freeze([]) })); }
}

const packageFixture = async () => { const root = mkdtempSync(join(tmpdir(), "chubz-m11-runtime-test-")); roots.push(root); const packageRoot = join(root, "package"); const configPath = join(root, "runtime-config.json"); mkdirSync(join(packageRoot, "app"), { recursive: true }); mkdirSync(join(packageRoot, "release"), { recursive: true }); const controlBytes = Buffer.from("// synthetic control"); const bridgeBytes = Buffer.from("// synthetic bridge"); const releaseBytes = Buffer.from(JSON.stringify({ applicationVersion: "0.11.0-mvp.1", gitCommit: "a".repeat(40), buildTimestamp: "2026-07-23T00:00:00.000Z" })); writeFileSync(join(packageRoot, "app", "control-plane.mjs"), controlBytes); writeFileSync(join(packageRoot, "app", "local-bridge.mjs"), bridgeBytes); writeFileSync(join(packageRoot, "release", "release-manifest.json"), releaseBytes); const files = [{ path: "app/control-plane.mjs", size: controlBytes.byteLength, sha256: sha(controlBytes.toString()) }, { path: "app/local-bridge.mjs", size: bridgeBytes.byteLength, sha256: sha(bridgeBytes.toString()) }, { path: "release/release-manifest.json", size: releaseBytes.byteLength, sha256: sha(releaseBytes.toString()) }].sort((left, right) => left.path.localeCompare(right.path)); writeFileSync(join(packageRoot, "SHA256SUMS.json"), JSON.stringify({ formatVersion: 1, files })); writeFileSync(configPath, "{}"); process.env["CHUBZ_TEST_SESSION_SECRET"] = "synthetic-runtime-secret-at-least-32-bytes"; return { root, packageRoot, configPath, config: configFor(root, await freePort()) }; };

describe("M11 bounded runtime process management", () => {
  it("prevents duplicates, refuses wrong identities, and stops only exact known process trees", async () => {
    const value = await packageFixture(); const adapter = new FakeProcesses(); process.env["UNRELATED_SECRET"] = "must-not-be-inherited"; const started = await startRuntime(value.config, value.configPath, value.packageRoot, adapter); delete process.env["UNRELATED_SECRET"]; expect((started["started"] as unknown[]).length).toBe(2); expect(adapter.environments[0]).toMatchObject({ NODE_ENV: "production", CHUBZ_BUILD_VERSION: "0.11.0-mvp.1", CHUBZ_BUILD_COMMIT: "a".repeat(40), CHUBZ_TEST_SESSION_SECRET: "synthetic-runtime-secret-at-least-32-bytes" }); expect(adapter.environments[0]).not.toHaveProperty("UNRELATED_SECRET"); expect((await inspectRuntime(value.config, adapter)).map((entry) => entry.status)).toEqual(["running", "running"]); await expect(startRuntime(value.config, value.configPath, value.packageRoot, adapter)).rejects.toThrow("PID record exists");
    const control = (await inspectRuntime(value.config, adapter))[0]!.record!; adapter.identities.set(control.pid, Object.freeze({ ...adapter.identities.get(control.pid)!, commandDigest: sha("unrelated process") })); await expect(stopRuntime(value.config, adapter)).rejects.toThrow("another process"); expect(adapter.terminated).toHaveLength(0);
    const parsed = JSON.parse(readFileSync(join(value.root, "runtime-data", "runtime", "control-plane.pid.json"), "utf8")) as ProcessIdentity; adapter.identities.set(control.pid, Object.freeze({ pid: parsed.pid, executablePath: parsed.executablePath, commandDigest: parsed.commandDigest, processStartedAt: parsed.processStartedAt })); const stopped = await stopRuntime(value.config, adapter); expect(stopped).toMatchObject({ knownProcessTreesOnly: true, provenPidRecordsRemoved: true }); expect(adapter.terminated).toHaveLength(2); expect((await inspectRuntime(value.config, adapter)).every((entry) => entry.status === "absent")).toBe(true);
  });

  it("reports and explicitly clears only proven-stale PID records", async () => {
    const value = await packageFixture(); const adapter = new FakeProcesses(); await startRuntime(value.config, value.configPath, value.packageRoot, adapter); adapter.identities.clear(); expect((await inspectRuntime(value.config, adapter)).every((entry) => entry.status === "stale")).toBe(true); const cleared = await clearStaleRuntimePidRecords(value.config, adapter); expect(cleared).toMatchObject({ exactPidAbsenceProven: true, processesTerminated: false, unrelatedFilesRemoved: false }); expect((await inspectRuntime(value.config, adapter)).every((entry) => entry.status === "absent")).toBe(true);
  });

  it("rolls back a known partial start and refuses a port conflict before spawning", async () => {
    const value = await packageFixture(); const partial = new FakeProcesses(); partial.failSpawnAt = 2; await expect(startRuntime(value.config, value.configPath, value.packageRoot, partial)).rejects.toThrow("synthetic spawn failure"); expect(partial.terminated).toHaveLength(1); expect((await inspectRuntime(value.config, partial)).every((entry) => entry.status === "absent")).toBe(true);
    const server = createServer(); await new Promise<void>((done, fail) => { server.once("error", fail); server.listen(value.config.controlPlane.port, value.config.controlPlane.host, done); }); const conflict = new FakeProcesses(); try { await expect(startRuntime(value.config, value.configPath, value.packageRoot, conflict)).rejects.toThrow("port is already in use"); expect(conflict.spawnCount).toBe(0); } finally { await new Promise<void>((done) => server.close(() => done())); }
  });
});
