import { createHash, createHmac } from "node:crypto";
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import WebSocket from "ws";
import { createControlPlane } from "../src/app.js";
import { createTestConfig } from "../src/config.js";
import { BoundedOperationalLog } from "../src/m11-artifacts.js";
import { parseM11Configuration, validateM11Configuration } from "../src/m11-config.js";

const origin = "http://127.0.0.1:4317"; const roots: string[] = [];
const fixture = () => { const root = mkdtempSync(join(tmpdir(), "chubz-m11-test-")); roots.push(root); const config = { ...createTestConfig(root), logLevel: "fatal" as const }; return { root, config, control: createControlPlane(config) }; };
afterEach(async () => { while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }); });
const authenticate = async (control: ReturnType<typeof createControlPlane>) => { await control.app.inject({ method: "POST", url: "/v1/auth/bootstrap", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const login = await control.app.inject({ method: "POST", url: "/v1/auth/login", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); return { cookie: String(login.headers["set-cookie"]), csrf: (login.json() as { csrfToken: string }).csrfToken }; };
const headers = (auth: { cookie: string; csrf: string }) => ({ origin, cookie: auth.cookie, "x-csrf-token": auth.csrf, "content-type": "application/json" });
const sha = (value: Buffer | string): string => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const runtimeConfig = (root: string, extra: Record<string, unknown> = {}) => ({ configVersion: 1, controlPlane: { host: "127.0.0.1", port: 4317, allowedOrigin: origin, sessionSecretRef: "environment:CHUBZ_TEST_SESSION_SECRET" }, bridge: { endpoint: "ws://127.0.0.1:4317/v1/bridge/ws", enrollmentIdentity: "local-bridge", heartbeatIntervalMs: 10_000 }, paths: { approvedManagedRoots: [root], managedDataRoot: join(root, "runtime-data"), databaseFile: "control-plane.sqlite", logsDirectory: "operational-logs", supportBundlesDirectory: "support-bundles", packagesDirectory: "release-packages" }, bounds: { logMaxBytes: 65_536, logRetentionFiles: 2, captureMaxBytes: 65_536, packageMaxBytes: 1_048_576, packageMaxFiles: 100, supportBundleMaxBytes: 1_048_576, supportBundleMaxFiles: 16, storageWarningPercent: 90 }, retention: { operationalLogDays: 14, resolvedAlertDays: 30, supportBundleDays: 30, packagingStagingHours: 24 }, projects: [], display: { productName: "CHUBZ", environmentLabel: "Local" }, ...extra });

describe("M11 operational summary and persistent alerts", () => {
  it("reports evidence confidence and keeps acknowledgement distinct from authoritative resolution", async () => {
    const { control } = fixture(); const auth = await authenticate(control);
    expect((await control.app.inject({ method: "GET", url: "/v1/ui/operations/summary" })).statusCode).toBe(401);
    const response = await control.app.inject({ method: "GET", url: "/v1/ui/operations/summary", headers: { cookie: auth.cookie } }); expect(response.statusCode).toBe(200); const summary = response.json() as { metrics: Record<string, { confidence: string }>; alerts: Array<Record<string, unknown>> };
    expect(Object.values(summary.metrics).every((entry) => ["authoritative", "observed", "estimated", "owner-attested", "unknown", "stale"].includes(entry.confidence))).toBe(true);
    const disconnected = summary.alerts.find((alert) => alert["conditionKey"] === "bridge-disconnected")!; expect(disconnected).toMatchObject({ state: "active", acknowledgementResolvesCondition: false });
    control.operational.refreshAlerts(); const stable = control.operational.alert({ administratorId: (control.database.connection.prepare("SELECT id FROM administrators").get() as { id: string }).id } as never, disconnected["alertId"]); expect(stable["version"]).toBe(disconnected["version"]);
    const ackBody = { expectedVersion: disconnected["version"], idempotencyKey: "m11-alert-ack-one" };
    expect((await control.app.inject({ method: "POST", url: `/v1/ui/alerts/${disconnected["alertId"]}/acknowledge`, headers: { ...headers(auth), origin: "http://evil.invalid" }, payload: ackBody })).statusCode).toBe(403);
    const ack = await control.app.inject({ method: "POST", url: `/v1/ui/alerts/${disconnected["alertId"]}/acknowledge`, headers: headers(auth), payload: ackBody }); expect(ack.statusCode).toBe(200); expect(ack.json()).toMatchObject({ state: "acknowledged", conditionResolved: false });
    expect((await control.app.inject({ method: "POST", url: `/v1/ui/alerts/${disconnected["alertId"]}/acknowledge`, headers: headers(auth), payload: ackBody })).json()).toEqual(ack.json());
    control.operational.refreshAlerts(); const acknowledged = (await control.app.inject({ method: "GET", url: `/v1/ui/alerts/${disconnected["alertId"]}`, headers: { cookie: auth.cookie } })).json(); expect(acknowledged.state).toBe("acknowledged");
    control.database.connection.prepare("UPDATE m8_bridge_state SET connection_state='connected',last_seen_at=?,updated_at=?,version=version+1 WHERE bridge_id='local-bridge'").run(new Date().toISOString(), new Date().toISOString()); control.operational.refreshAlerts();
    const resolved = (await control.app.inject({ method: "GET", url: `/v1/ui/alerts/${disconnected["alertId"]}`, headers: { cookie: auth.cookie } })).json(); expect(resolved.state).toBe("resolved"); expect(resolved.resolvedAt).toBeTruthy();
    expect(() => control.operational.alert({ administratorId: "another-owner" } as never, disconnected["alertId"])).toThrow("owner scope"); await control.close();
  });

  it("authenticates the outbound Bridge WebSocket and records bounded version/heartbeat evidence", async () => {
    const { control, config } = fixture(); await control.app.listen({ host: "127.0.0.1", port: 0 }); const address = control.app.server.address(); if (!address || typeof address === "string") throw new Error("listener unavailable");
    const authorization = `Bearer ${createHmac("sha256", config.sessionSecret).update("chubz.m11.bridge-session/v1\nlocal-bridge").digest("base64url")}`; const socket = new WebSocket(`ws://127.0.0.1:${address.port}/v1/bridge/ws`, { headers: { authorization } }); await new Promise<void>((resolve, reject) => { socket.once("open", resolve); socket.once("error", reject); });
    const received = new Promise<Record<string, unknown>>((resolve) => socket.once("message", (message) => resolve(JSON.parse(message.toString()) as Record<string, unknown>))); socket.send(JSON.stringify({ kind: "bridge.heartbeat", enrollmentIdentity: "local-bridge", sentAt: new Date().toISOString(), runtimeVersion: "0.11.0-mvp.1", emergencyGate: "required" })); expect(await received).toMatchObject({ kind: "bridge.heartbeat-accepted", emergencyStopGateRequired: true });
    expect(control.database.connection.prepare("SELECT connection_state FROM m8_bridge_state WHERE bridge_id='local-bridge'").get()).toMatchObject({ connection_state: "connected" }); expect(control.database.connection.prepare("SELECT runtime_version FROM m11_component_versions WHERE component_id='local-bridge'").get()).toMatchObject({ runtime_version: "0.11.0-mvp.1" }); socket.close(); await new Promise((done) => socket.once("close", done)); await control.close();
  });
});

describe("M11 configuration, logs, support, package, upgrade, and retention evidence", () => {
  it("rejects unsafe configuration and persists bounded redacted restart-safe logs", () => {
    const root = mkdtempSync(join(tmpdir(), "chubz-m11-config-test-")); roots.push(root); const valid = runtimeConfig(root); expect(parseM11Configuration(valid).configVersion).toBe(1);
    const unknown = validateM11Configuration({ ...valid, arbitraryCommand: "calc.exe --password top-secret" }); expect(unknown.valid).toBe(false); expect(JSON.stringify(unknown)).not.toContain("top-secret");
    const unsafe = runtimeConfig(root, { paths: { ...(valid.paths as Record<string, unknown>), managedDataRoot: join(root, "..", "escape") } }); expect(validateM11Configuration(unsafe).valid).toBe(false);
    const logRoot = join(root, "logs"); const log = new BoundedOperationalLog(logRoot, "control-plane", 65_536, 2); for (let index = 0; index < 500; index += 1) log.write("warning", "bounded-event", { token: "secret-value", line: `safe\nforged-${index}`, message: "password=hunter2" }); const files = ["control-plane.jsonl", "control-plane.jsonl.1", "control-plane.jsonl.2"].filter((name) => existsSync(join(logRoot, name))); expect(files.length).toBeGreaterThan(1); const content = files.map((name) => readFileSync(join(logRoot, name), "utf8")).join(""); expect(content).not.toMatch(/secret-value|hunter2|\nforged-/u); expect(new BoundedOperationalLog(logRoot, "control-plane", 65_536, 2).recent(10).length).toBeLessThanOrEqual(10);
  });

  it("generates sanitized immutable evidence, detects tampering, verifies packages, previews upgrades, and applies exact retention", async () => {
    const { root, control } = fixture(); const auth = await authenticate(control); const protectedHeaders = headers(auth);
    const body = { expectedVersion: 0, idempotencyKey: "support-generate-one" }; expect((await control.app.inject({ method: "POST", url: "/v1/ui/support-bundles", headers: { ...protectedHeaders, "x-csrf-token": "wrong" }, payload: body })).statusCode).toBe(403);
    const generated = await control.app.inject({ method: "POST", url: "/v1/ui/support-bundles", headers: protectedHeaders, payload: body }); expect(generated.statusCode).toBe(201); const artifact = generated.json() as { artifactId: string; fileName: string; sha256: string; version: number }; expect((await control.app.inject({ method: "POST", url: "/v1/ui/support-bundles", headers: protectedHeaders, payload: body })).json()).toEqual(artifact);
    const path = join(root, "support-bundles", artifact.fileName); const content = readFileSync(path, "utf8"); chmodSync(path, 0o600); expect(content).not.toMatch(/correct-horse|sessionSecret|taskInstructions|synthetic-private-prompt|synthetic-raw-worker-result/iu); expect(content).toContain("secretValuesIncluded");
    writeFileSync(path, `${content}tampered`); const ownerId = (control.database.connection.prepare("SELECT id FROM administrators").get() as { id: string }).id; expect(control.artifacts.verifySupport({ administratorId: ownerId, username: "owner", sessionId: "test", csrfToken: "test" }, artifact.artifactId, { expectedVersion: artifact.version, idempotencyKey: "support-verify-tampered" })).toMatchObject({ verified: false, status: "tampered" }); const verification = await control.app.inject({ method: "POST", url: `/v1/ui/support-bundles/${artifact.artifactId}/verify`, headers: protectedHeaders, payload: { expectedVersion: artifact.version, idempotencyKey: "support-verify-tampered" } }); expect(verification.json()).toMatchObject({ verified: false, status: "tampered" });

    const packageRoot = join(root, "release-packages", "candidate-one"); mkdirSync(join(packageRoot, "release"), { recursive: true }); const appBytes = Buffer.from("synthetic application"); const releaseBytes = Buffer.from(JSON.stringify({ applicationVersion: "0.11.0-mvp.1", gitCommit: "a".repeat(40), buildTimestamp: "2026-07-23T00:00:00.000Z", schemaVersions: { database: 11, configuration: 1 } })); writeFileSync(join(packageRoot, "app.mjs"), appBytes); writeFileSync(join(packageRoot, "release", "release-manifest.json"), releaseBytes); const files = [{ path: "app.mjs", size: appBytes.byteLength, sha256: sha(appBytes) }, { path: "release/release-manifest.json", size: releaseBytes.byteLength, sha256: sha(releaseBytes) }]; writeFileSync(join(packageRoot, "SHA256SUMS.json"), JSON.stringify({ formatVersion: 1, files }));
    const packageResponse = await control.app.inject({ method: "POST", url: "/v1/ui/runtime-packages/verify", headers: protectedHeaders, payload: { packageName: "candidate-one", expectedVersion: 0, idempotencyKey: "package-verify-one" } }); expect(packageResponse.statusCode).toBe(200); const verifiedPackage = packageResponse.json() as { artifactId: string; verified: boolean }; expect(verifiedPackage.verified).toBe(true);
    const upgrade = await control.app.inject({ method: "POST", url: "/v1/ui/upgrade-plan", headers: protectedHeaders, payload: { artifactId: verifiedPackage.artifactId } }); expect(upgrade.json()).toMatchObject({ candidateVersion: "0.11.0-mvp.1", candidateGitCommit: "a".repeat(40), mutationPerformed: false, installationPerformed: false, deploymentPerformed: false, backup: { required: true }, restartRequired: true });
    writeFileSync(join(packageRoot, "app.mjs"), "tampered application"); expect((await control.app.inject({ method: "POST", url: "/v1/ui/runtime-packages/verify", headers: protectedHeaders, payload: { packageName: "candidate-one", expectedVersion: 0, idempotencyKey: "package-verify-stale" } })).statusCode).toBe(409); const packageTamper = await control.app.inject({ method: "POST", url: "/v1/ui/runtime-packages/verify", headers: protectedHeaders, payload: { packageName: "candidate-one", expectedVersion: 1, idempotencyKey: "package-verify-two" } }); expect(packageTamper.json()).toMatchObject({ verified: false, status: "tampered", version: 2 });
    control.database.connection.prepare("UPDATE m11_runtime_artifacts SET created_at=? WHERE artifact_id=?").run("2020-01-01T00:00:00.000Z", artifact.artifactId); utimesSync(path, new Date("2020-01-01T00:00:00Z"), new Date("2020-01-01T00:00:00Z"));
    const preview = await control.app.inject({ method: "POST", url: "/v1/ui/retention/preview", headers: protectedHeaders, payload: { supportBundleDays: 1, operationalLogDays: 1, expectedVersion: 0, idempotencyKey: "retention-preview-one" } }); expect(preview.statusCode).toBe(200); const retention = preview.json() as { previewId: string; version: number; candidates: Array<{ identity: string }> }; expect(retention.candidates.some((entry) => entry.identity === artifact.artifactId)).toBe(true); expect(existsSync(path)).toBe(true);
    const applied = await control.app.inject({ method: "POST", url: "/v1/ui/retention/apply", headers: protectedHeaders, payload: { previewId: retention.previewId, expectedVersion: retention.version, idempotencyKey: "retention-apply-one" } }); expect(applied.json()).toMatchObject({ knownFilesOnly: true, broadRecursiveDeletion: false, authoritativeDatabaseRecordsDeleted: false, ownerProjectFilesDeleted: false }); expect(existsSync(path)).toBe(false); expect(control.database.connection.prepare("SELECT status FROM m11_runtime_artifacts WHERE artifact_id=?").get(artifact.artifactId)).toMatchObject({ status: "retained-metadata" }); await control.close();
  });
});
