import { createHash } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createControlPlane } from "../src/app.js";
import { createTestConfig } from "../src/config.js";
import { M7ReviewService } from "../src/m7-review.js";

const origin = "http://127.0.0.1:4317"; const roots: string[] = [];
afterEach(() => { while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }); });
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const sha256 = (value: string): `sha256:${string}` => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const fixture = () => { const root = mkdtempSync(join(tmpdir(), "chubz-m7-review-test-")); roots.push(root); const config = createTestConfig(root); return { root, config, control: createControlPlane(config) }; };
const authenticate = async (control: ReturnType<typeof createControlPlane>) => { await control.app.ready(); await control.app.inject({ method: "POST", url: "/v1/auth/bootstrap", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const login = await control.app.inject({ method: "POST", url: "/v1/auth/login", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const cookie = String(login.headers["set-cookie"]); const principal = control.auth.authenticate(cookie.split(";", 1)[0]?.split("=", 2)[1]); if (!principal) throw new Error("fixture authentication failed"); return { cookie, csrf: (login.json() as { csrfToken: string }).csrfToken, principal }; };
const headers = (auth: Awaited<ReturnType<typeof authenticate>>) => ({ origin, cookie: auth.cookie, "x-csrf-token": auth.csrf, "content-type": "application/json" });

async function eligibleManual(control: ReturnType<typeof createControlPlane>, auth: Awaited<ReturnType<typeof authenticate>>, key: string) {
  const created = (await control.app.inject({ method: "POST", url: "/v1/ui/tasks", headers: headers(auth), payload: { idempotencyKey: `task-create:${key}`, projectId: "project-manual", instructions: "Review bounded evidence", workerId: "manual-relay", timeoutSec: 900 } })).json() as { taskId: string; attemptId: string; operationId: string; version: number };
  const result = (await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${created.taskId}/manual-text`, headers: headers(auth), payload: { idempotencyKey: `manual-text:${key}`, expectedVersion: created.version, responseType: "review", text: "bounded worker claim", attested: true } })).json() as { version: number };
  return { ...created, version: result.version };
}

function packageFor(binding: Record<string, unknown>) {
  const core = { schemaVersion: "m7.review-package/v1", captureId: binding["captureId"], binding, capturedAt: "2026-07-22T10:00:00.000Z", packageStatus: "captured", git: { baselineCommit: "1".repeat(40), head: "2".repeat(40) }, changedPaths: [{ path: "README.md", beforeHash: `sha256:${"3".repeat(64)}`, afterHash: `sha256:${"4".repeat(64)}` }], diff: { complete: true, text: "safe bounded diff" }, validations: [{ command: ["pnpm", "test"], exitCode: 0, authoritativeOutcome: "passed", parser: { parsed: true, passed: 1, failed: 0, skipped: 0, total: 1 } }], evidence: { workerReportedClaim: "bounded worker claim", systemObserved: true, ownerAttestedManualEvidence: { attestationId: "attestation-one" }, reviewerConclusion: null }, provenance: { applied: false, artifactExecution: false }, limitations: [], redactions: { diff: 0 }, omissions: [] };
  const packageDigest = sha256(`chubz.m7.review-package/v1\n${canonical(core)}`); const packageId = `package-${packageDigest.slice(7, 55)}`; const document = { ...core, packageId, packageDigest }; const packageJson = `${canonical(document)}\n`; const manifestCore = { schemaVersion: "m7.review-manifest/v1", packageId, captureId: binding["captureId"], files: [{ name: "review-package.json", sha256: sha256(packageJson), byteLength: Buffer.byteLength(packageJson) }], totalByteLength: Buffer.byteLength(packageJson), applied: false }; const manifestDigest = sha256(`chubz.m7.review-manifest/v1\n${canonical(manifestCore)}`); return { document, manifest: { ...manifestCore, manifestDigest } };
}

describe("M7 authoritative capture lifecycle and protected review APIs", () => {
  it("requires auth, Origin, CSRF, exact state, stale checks, and idempotently deduplicates concurrent capture requests", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const task = await eligibleManual(control, auth, "capture-one"); const url = `/v1/ui/tasks/${task.taskId}/captures`; const payload = { idempotencyKey: "capture-request:one", expectedVersion: task.version };
    expect((await control.app.inject({ method: "POST", url, headers: { origin, "content-type": "application/json" }, payload })).statusCode).toBe(403);
    expect((await control.app.inject({ method: "POST", url, headers: { ...headers(auth), origin: "http://evil.invalid" }, payload })).statusCode).toBe(403);
    const [first, duplicate] = await Promise.all([control.app.inject({ method: "POST", url, headers: headers(auth), payload }), control.app.inject({ method: "POST", url, headers: headers(auth), payload })]); expect(first.statusCode).toBe(202); expect(duplicate.statusCode).toBe(202); expect(duplicate.json()).toEqual(first.json());
    const conflict = await control.app.inject({ method: "POST", url, headers: headers(auth), payload: { ...payload, expectedVersion: task.version - 1 } }); expect(conflict.statusCode).toBe(409); expect((control.database.connection.prepare("SELECT COUNT(*) AS count FROM m7_capture_requests").get() as { count: number }).count).toBe(1); expect((control.database.connection.prepare("SELECT COUNT(*) AS count FROM events WHERE payload_json LIKE '%evidence.capture-pending%'").get() as { count: number }).count).toBe(1); await control.close();
  });

  it("finalizes one immutable sanitized package, verifies stored hashes, safely downloads it, and blocks IDOR/tampering", async () => {
    const { config, control } = fixture(); const auth = await authenticate(control); const task = await eligibleManual(control, auth, "finalize-one"); const request = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/captures`, headers: headers(auth), payload: { idempotencyKey: "capture-request:finalize", expectedVersion: task.version } }); const capture = request.json() as { captureId: string };
    const review = control.review; review.beginSystemCapture(capture.captureId); const binding = { captureId: capture.captureId, ownerId: auth.principal.administratorId, projectId: "project-manual", taskId: task.taskId, attemptId: task.attemptId, operationId: task.operationId, journalId: "journal-one", workerId: "manual-relay", adapterId: "manual-relay", adapterRunId: null }; const built = packageFor(binding); const finalized = review.finalizeSystemCapture({ captureId: capture.captureId, packageDocument: built.document, manifest: built.manifest }); expect(finalized).toMatchObject({ status: "captured", replayed: false }); expect(review.finalizeSystemCapture({ captureId: capture.captureId, packageDocument: built.document, manifest: built.manifest })).toMatchObject({ replayed: true });
    expect(() => review.finalizeSystemCapture({ captureId: capture.captureId, packageDocument: { ...built.document, packageDigest: `sha256:${"9".repeat(64)}` }, manifest: built.manifest })).toThrow(); expect((control.database.connection.prepare("SELECT COUNT(*) AS count FROM events WHERE payload_json LIKE '%evidence.package-captured%'").get() as { count: number }).count).toBe(1);
    const verify = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/review-packages/${String(finalized["packageId"])}/verify`, headers: headers(auth), payload: {} }); expect(verify.statusCode).toBe(200); expect(verify.json()).toMatchObject({ verified: true });
    const download = await control.app.inject({ method: "GET", url: `/v1/review-packages/${String(finalized["packageId"])}`, headers: { cookie: auth.cookie } }); expect(download.statusCode).toBe(200); expect(download.headers["content-disposition"]).toContain("attachment"); expect(download.body).not.toContain("capabilityGrant");
    expect(() => review.download({ ...auth.principal, administratorId: "other-owner" }, finalized["packageId"])).toThrow("not found"); expect((await control.app.inject({ method: "POST", url: `/v1/ui/tasks/wrong-task/review-packages/${String(finalized["packageId"])}/verify`, headers: headers(auth), payload: {} })).statusCode).toBe(404); expect(() => control.database.connection.prepare("UPDATE m7_review_packages SET status='incomplete' WHERE package_id=?").run(finalized["packageId"])).toThrow();
    const packageDirectory = join(config.dataDirectory, "review-packages", String(finalized["packageId"])); const manifestPath = join(packageDirectory, "manifest.json"); chmodSync(manifestPath, 0o600); writeFileSync(manifestPath, "{}\n"); const tampered = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/review-packages/${String(finalized["packageId"])}/verify`, headers: headers(auth), payload: {} }); expect(tampered.json()).toMatchObject({ verified: false }); expect((await control.app.inject({ method: "GET", url: `/v1/review-packages/${String(finalized["packageId"])}`, headers: { cookie: auth.cookie } })).statusCode).toBe(409);
    control.database.connection.prepare("UPDATE m7_capture_requests SET owner_id='other-owner' WHERE capture_id=?").run(capture.captureId); const hidden = await control.app.inject({ method: "GET", url: `/v1/ui/tasks/${task.taskId}/captures`, headers: { cookie: auth.cookie } }); expect((hidden.json() as { captures: unknown[] }).captures).toHaveLength(0); await control.close();
  });

  it("marks interrupted capture as incomplete after restart and permits only explicit failed/incomplete retry", async () => {
    const { config, control } = fixture(); const auth = await authenticate(control); const task = await eligibleManual(control, auth, "restart-one"); const response = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/captures`, headers: headers(auth), payload: { idempotencyKey: "capture-request:restart", expectedVersion: task.version } }); const capture = response.json() as { captureId: string }; const review = new M7ReviewService(control.database, config); review.beginSystemCapture(capture.captureId); const staging = join(config.dataDirectory, "review-packages", ".staging-orphan"); mkdirSync(staging); new M7ReviewService(control.database, config); expect(existsSync(staging)).toBe(false); const status = control.database.connection.prepare("SELECT status,failure_reason FROM m7_capture_requests WHERE capture_id=?").get(capture.captureId) as { status: string; failure_reason: string }; expect(status).toEqual({ status: "incomplete", failure_reason: "capture interrupted by restart" });
    const retry = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/captures/${capture.captureId}/retry`, headers: headers(auth), payload: { idempotencyKey: "capture-retry:restart", expectedVersion: task.version } }); expect(retry.statusCode).toBe(202); expect(retry.json()).toMatchObject({ status: "pending", retryOfCaptureId: capture.captureId }); const retryId = (retry.json() as { captureId: string }).captureId;
    const denied = await control.app.inject({ method: "POST", url: `/v1/ui/tasks/${task.taskId}/captures/${retryId}/retry`, headers: headers(auth), payload: { idempotencyKey: "capture-retry:denied", expectedVersion: task.version } }); expect(denied.statusCode).toBe(409); await control.close();
  });
});
