import { createHash } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createControlPlane } from "../src/app.js";
import { createTestConfig } from "../src/config.js";

const origin = "http://127.0.0.1:4317"; const roots: string[] = [];
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const sha256 = (value: string): `sha256:${string}` => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const fixture = () => { const root = mkdtempSync(join(tmpdir(), "chubz-m9-control-test-")); roots.push(root); const config = { ...createTestConfig(root), logLevel: "fatal" as const }; return { root, config, control: createControlPlane(config) }; };
afterEach(() => { while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }); });
const authenticate = async (control: ReturnType<typeof createControlPlane>) => { await control.app.ready(); await control.app.inject({ method: "POST", url: "/v1/auth/bootstrap", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const login = await control.app.inject({ method: "POST", url: "/v1/auth/login", headers: { origin, "content-type": "application/json" }, payload: { username: "owner", password: "correct-horse-battery-staple" } }); const cookie = String(login.headers["set-cookie"]); const principal = control.auth.authenticate(cookie.split(";", 1)[0]?.split("=", 2)[1]); if (!principal) throw new Error("authentication failed"); return { cookie, csrf: (login.json() as { csrfToken: string }).csrfToken, principal }; };
const headers = (auth: Awaited<ReturnType<typeof authenticate>>) => ({ origin, cookie: auth.cookie, "x-csrf-token": auth.csrf, "content-type": "application/json" });

function reviewPackage(binding: Record<string, unknown>, repositoryId: string) {
  const baseline = "1".repeat(40); const head = "2".repeat(40); const core = { schemaVersion: "m7.review-package/v1", captureId: binding["captureId"], binding, capturedAt: "2026-07-23T01:00:00.000Z", packageStatus: "captured", git: { repositoryId, branch: "task/reviewed", detached: false, head, directParent: baseline, baselineCommit: baseline, mergeBase: baseline, commitSubjects: [`${head}\treviewed change`], refsStable: true, configurationAssurance: { systemConfigDisabled: true, globalConfigDisabled: true, hooksDisabled: true, externalDiffDisabled: true, textConversionDisabled: true }, rawMetadataDigest: sha256("raw"), numstatDigest: sha256("numstat") }, changedPaths: [{ path: "src/safe.ts", originalPath: null, operation: "modified", staged: false, unstaged: false, untracked: false, additions: 2, deletions: 1, beforeHash: sha256("before"), afterHash: sha256("after"), content: { included: true, reason: null, binary: false } }], diffStatistics: { files: 1, additions: 2, deletions: 1, binaryFiles: 0 }, diff: { format: "unified", text: "safe diff", byteLimit: 1024, truncated: false, redacted: false, redactionCount: 0, complete: true }, validations: [{ validationId: "review-test", kind: "test", command: ["pnpm", "test"], workingDirectory: ".", startedAt: "2026-07-23T00:59:00.000Z", finishedAt: "2026-07-23T00:59:01.000Z", exitCode: 0, terminationReason: null, authoritativeOutcome: "passed", parser: { parsed: true, passed: 1, failed: 0, skipped: 0, total: 1 }, stdout: { truncated: false, redacted: false }, stderr: { truncated: false, redacted: false }, processTreeTermination: null, toolVersions: {}, artifactHashes: [] }], artifacts: { references: [], quarantineStatus: "none-observed" }, evidence: { workerReportedClaim: "claim only", systemObserved: true, ownerAttestedManualEvidence: null, reviewerConclusion: null }, provenance: { readiness: {}, sandbox: {}, terminalState: "completed", executionUnknown: false, cancellation: [], applied: false, artifactExecution: false, manualRelay: false }, limitations: [], redactions: { diff: 0, workerClaim: 0, validations: 0, provenance: 0 }, omissions: [] };
  const packageDigest = sha256(`chubz.m7.review-package/v1\n${canonical(core)}`); const packageId = `package-${packageDigest.slice(7, 55)}`; const document = { ...core, packageId, packageDigest }; const packageJson = `${canonical(document)}\n`; const manifestCore = { schemaVersion: "m7.review-manifest/v1", packageId, captureId: binding["captureId"], files: [{ name: "review-package.json", sha256: sha256(packageJson), byteLength: Buffer.byteLength(packageJson) }], totalByteLength: Buffer.byteLength(packageJson), applied: false }; return { document, manifest: { ...manifestCore, manifestDigest: sha256(`chubz.m7.review-manifest/v1\n${canonical(manifestCore)}`) } };
}

async function eligible(control: ReturnType<typeof createControlPlane>, auth: Awaited<ReturnType<typeof authenticate>>, suffix = "one", isolatedProjects = suffix === "promotion-restart") {
  const taskId = `task-m9-${suffix}`; const attemptId = `attempt-m9-${suffix}`; const operationId = `operation-m9-${suffix}`; const captureId = `capture-m9-${suffix}`; const sourceIdentity = sha256(`source-${suffix}`); const targetIdentity = sha256(`target-${suffix}`); const sourceProjectId = isolatedProjects ? `source-project-${suffix}` : "source-project"; const targetProjectId = isolatedProjects ? `target-project-${suffix}` : "target-project"; const at = new Date().toISOString(); const db = control.database.connection;
  db.prepare("INSERT INTO tasks(task_id,project_id,state,attempt_id,updated_at,version,created_at,current_operation_id) VALUES(?,?,'APPROVED',?,?,7,?,?)").run(taskId, sourceProjectId, attemptId, at, at, operationId);
  db.prepare("INSERT INTO task_attempts(attempt_id,task_id,attempt_sequence,action_json,action_digest,input_text,created_at) VALUES(?,?,1,'{}',?,'bounded task',?)").run(attemptId, taskId, sha256("action"), at);
  db.prepare("INSERT INTO m7_capture_requests(capture_id,identity_digest,owner_id,project_id,task_id,attempt_id,operation_id,worker_id,adapter_id,status,requested_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'capturing',?,?)").run(captureId, sha256(`capture-${suffix}`), auth.principal.administratorId, sourceProjectId, taskId, attemptId, operationId, "codex-cli", "codex-cli", at, at);
  const binding = { captureId, ownerId: auth.principal.administratorId, projectId: sourceProjectId, taskId, attemptId, operationId, journalId: `journal-${suffix}`, workerId: "codex-cli", adapterId: "codex-cli", adapterRunId: `run-${suffix}` }; const built = reviewPackage(binding, sourceIdentity); const finalized = control.review.finalizeSystemCapture({ captureId, packageDocument: built.document, manifest: built.manifest });
  control.apply.registerRepositorySystem({ ownerId: auth.principal.administratorId, projectId: sourceProjectId, bindingKind: "source-managed", repositoryIdentity: sourceIdentity, canonicalPath: join(control.database.connection.name, "..", `source-${suffix}`) });
  control.apply.registerRepositorySystem({ ownerId: auth.principal.administratorId, projectId: targetProjectId, bindingKind: "target-owner", repositoryIdentity: targetIdentity, canonicalPath: join(control.database.connection.name, "..", `target-${suffix}`), validationPlans: [{ validationPlanId: "required", commands: [{ validationId: "required-tests", kind: "test", executable: "node", args: ["--test"], cwd: ".", timeoutMs: 60_000 }] }] });
  return { taskId, attemptId, operationId, captureId, packageId: finalized["packageId"] as string, sourceIdentity, targetIdentity, sourceProjectId, targetProjectId };
}
const planPayload = (value: Awaited<ReturnType<typeof eligible>>, idempotencyKey = "apply-plan-one") => ({ packageId: value.packageId, targetProjectId: value.targetProjectId, targetRef: "refs/heads/main", expectedTargetHead: "1".repeat(40), applyMode: "exact-reviewed-commit", validationPlanId: "required", expectedTaskVersion: 7, idempotencyKey });

describe("M9 Control Plane apply authority", () => {
  it("enforces protected eligibility, immutable plan binding, one-use prepare grant, separate exact promotion confirmation, and final evidence", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const value = await eligible(control, auth);
    expect((await control.app.inject({ method: "POST", url: "/v1/ui/apply/eligibility", headers: { origin, "content-type": "application/json" }, payload: planPayload(value) })).statusCode).toBe(403);
    expect((await control.app.inject({ method: "POST", url: "/v1/ui/apply/eligibility", headers: { ...headers(auth), origin: "http://evil.invalid" }, payload: planPayload(value) })).statusCode).toBe(403);
    const eligibility = await control.app.inject({ method: "POST", url: "/v1/ui/apply/eligibility", headers: headers(auth), payload: planPayload(value) }); expect(eligibility.statusCode).toBe(200); expect(eligibility.json()).toMatchObject({ eligible: true, failures: [] });
    const created = await control.app.inject({ method: "POST", url: "/v1/ui/apply-plans", headers: headers(auth), payload: planPayload(value) }); expect(created.statusCode).toBe(201); const plan = created.json() as Record<string, unknown>; expect(plan).toMatchObject({ status: "planned", applyMode: "exact-reviewed-commit", reviewedCommit: "2".repeat(40), expectedOldHead: "1".repeat(40) }); expect((await control.app.inject({ method: "POST", url: "/v1/ui/apply-plans", headers: headers(auth), payload: planPayload(value) })).json()).toEqual(plan);
    const applyId = String(plan["applyId"]); const preparedRequest = await control.app.inject({ method: "POST", url: `/v1/ui/apply/${applyId}/prepare`, headers: headers(auth), payload: { expectedVersion: plan["version"], idempotencyKey: "apply-prepare-one" } }); expect(preparedRequest.statusCode).toBe(202); expect(preparedRequest.json()).toMatchObject({ status: "prepare-queued" }); const command = control.apply.claimPrepareSystem(applyId); expect(command).toMatchObject({ packageId: value.packageId, reviewedChangedPaths: ["src/safe.ts"], applyMode: "exact-reviewed-commit" }); expect((control.database.connection.prepare("SELECT status FROM m9_capability_grants WHERE apply_id=?").get(applyId) as { status: string }).status).toBe("consumed");
    const result = { applyId, status: "ready", packageDigest: command["packageDigest"], preparationDigest: command["preparationDigest"], targetRepositoryIdentity: command["targetRepositoryIdentity"], oldHead: "1".repeat(40), preparedHead: "3".repeat(40), targetRef: "refs/heads/main", applyWorktree: "managed://apply/worktree", worktreesBefore: [], worktreesAfter: [], changedPaths: ["src/safe.ts"], diffStatistics: { files: 1, additions: 2, deletions: 1, binaryFiles: 0 }, conflicts: [], validations: [{ validationId: "required-tests", kind: "test", executable: "node", args: ["--test"], commandDigest: sha256(canonical(["node", "--test"])), cwd: ".", timeoutMs: 60_000, outcome: "passed", exitCode: 0 }], validationEvidenceDigest: sha256("validation"), applyWorktreeDigest: sha256("worktree"), previewDigest: sha256("preview"), rollback: { originalHead: "1".repeat(40), promotedHead: null, revertCandidateAvailable: true, automaticRollback: false, limitations: ["new operation required"] }, startedAt: at(), finishedAt: at() }; expect(() => control.apply.recordPrepareResultSystem(applyId, { ...result, validations: [{ ...result.validations[0], args: ["--forged"] }] })).toThrow("validation evidence"); const ready = control.apply.recordPrepareResultSystem(applyId, result); expect(ready).toMatchObject({ status: "ready", preparedHead: "3".repeat(40), actions: { canPromote: true } });
    const denied = await control.app.inject({ method: "POST", url: `/v1/ui/apply/${applyId}/promote`, headers: headers(auth), payload: { expectedVersion: ready["version"], confirmationDigest: sha256("wrong"), idempotencyKey: "apply-promote-wrong" } }); expect(denied.statusCode).toBe(409); const confirmationDigest = String(ready["promotionConfirmationDigest"]); const confirmed = await control.app.inject({ method: "POST", url: `/v1/ui/apply/${applyId}/promote`, headers: headers(auth), payload: { expectedVersion: ready["version"], confirmationDigest, idempotencyKey: "apply-promote-one" } }); expect(confirmed.statusCode).toBe(202); expect(confirmed.json()).toMatchObject({ status: "promotion-queued" }); expect(control.apply.claimPromotionSystem(applyId)).toMatchObject({ expectedOldHead: "1".repeat(40), preparedHead: "3".repeat(40), confirmationDigest }); const promoted = control.apply.recordPromotionResultSystem(applyId, { applyId, status: "promoted", oldHead: "1".repeat(40), newHead: "3".repeat(40), targetRef: "refs/heads/main", promotedAt: at(), rollback: { originalHead: "1".repeat(40), promotedHead: "3".repeat(40), revertCandidateAvailable: true, automaticRollback: false, limitations: ["new operation required", "no automatic push"] } }); expect(promoted).toMatchObject({ status: "promoted", actions: { automaticPush: false, retryAllowed: false } }); expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m9_apply_evidence WHERE apply_id=?").get(applyId) as { n: number }).n).toBeGreaterThanOrEqual(5); expect((control.database.connection.prepare("SELECT COUNT(*) AS n FROM m8_operational_events WHERE source='m9_apply_requests'").get() as { n: number }).n).toBeGreaterThanOrEqual(4); await control.close();
  });

  it("rejects tampering, unsafe refs, unsupported modes, stale versions, IDOR, duplicate conflicts, and emergency-stop races", async () => {
    const { control } = fixture(); const auth = await authenticate(control); const value = await eligible(control, auth, "security"); expect((await control.app.inject({ method: "POST", url: "/v1/ui/apply/eligibility", headers: headers(auth), payload: { ...planPayload(value), targetRef: "refs/heads/main;touch-pwned" } })).statusCode).toBe(400); expect((await control.app.inject({ method: "POST", url: "/v1/ui/apply/eligibility", headers: headers(auth), payload: { ...planPayload(value), applyMode: "bounded-patch" } })).json()).toMatchObject({ eligible: false, failures: ["unsupported-apply-mode"] });
    const created = (await control.app.inject({ method: "POST", url: "/v1/ui/apply-plans", headers: headers(auth), payload: planPayload(value, "security-plan") })).json() as Record<string, unknown>; expect((await control.app.inject({ method: "POST", url: "/v1/ui/apply-plans", headers: headers(auth), payload: { ...planPayload(value, "security-plan"), expectedTargetHead: "9".repeat(40) } })).statusCode).toBe(409); expect(() => control.apply.snapshot({ ...auth.principal, administratorId: "other-owner" }, value.taskId)).not.toThrow(); expect(control.apply.snapshot({ ...auth.principal, administratorId: "other-owner" }, value.taskId)).toHaveLength(0);
    const stop = await control.app.inject({ method: "POST", url: "/v1/ui/emergency-stops", headers: headers(auth), payload: { scopeType: "global", reason: "block apply", expectedVersion: 0, idempotencyKey: "m9-emergency-stop" } }); expect(stop.statusCode).toBe(201); expect((await control.app.inject({ method: "POST", url: `/v1/ui/apply/${String(created["applyId"])}/prepare`, headers: headers(auth), payload: { expectedVersion: created["version"], idempotencyKey: "security-prepare" } })).statusCode).toBe(503); await control.close();
  });

  it("marks interrupted preparation and promotion unknown exactly once across restart without retry", async () => {
    const value = fixture(); const auth = await authenticate(value.control); const eligibleValue = await eligible(value.control, auth, "restart"); const plan = (await value.control.app.inject({ method: "POST", url: "/v1/ui/apply-plans", headers: headers(auth), payload: planPayload(eligibleValue, "restart-plan") })).json() as Record<string, unknown>; await value.control.app.inject({ method: "POST", url: `/v1/ui/apply/${String(plan["applyId"])}/prepare`, headers: headers(auth), payload: { expectedVersion: plan["version"], idempotencyKey: "restart-prepare" } }); value.control.apply.claimPrepareSystem(plan["applyId"]);
    const promotionEligible = await eligible(value.control, auth, "promotion-restart"); const promotionPlan = (await value.control.app.inject({ method: "POST", url: "/v1/ui/apply-plans", headers: headers(auth), payload: planPayload(promotionEligible, "promotion-restart-plan") })).json() as Record<string, unknown>; await value.control.app.inject({ method: "POST", url: `/v1/ui/apply/${String(promotionPlan["applyId"])}/prepare`, headers: headers(auth), payload: { expectedVersion: promotionPlan["version"], idempotencyKey: "promotion-restart-prepare" } }); const command = value.control.apply.claimPrepareSystem(promotionPlan["applyId"]); const result = { applyId: promotionPlan["applyId"], status: "ready", packageDigest: command["packageDigest"], preparationDigest: command["preparationDigest"], targetRepositoryIdentity: command["targetRepositoryIdentity"], oldHead: "1".repeat(40), preparedHead: "3".repeat(40), targetRef: "refs/heads/main", applyWorktree: "managed://promotion-restart/worktree", validations: [{ validationId: "required-tests", kind: "test", executable: "node", args: ["--test"], commandDigest: sha256(canonical(["node", "--test"])), cwd: ".", timeoutMs: 60_000, outcome: "passed", exitCode: 0 }], validationEvidenceDigest: sha256("promotion-restart-validation"), applyWorktreeDigest: sha256("promotion-restart-worktree"), rollback: { originalHead: "1".repeat(40), promotedHead: null, automaticRollback: false, limitations: [] } }; const ready = value.control.apply.recordPrepareResultSystem(promotionPlan["applyId"], result); value.control.apply.confirmPromotion(auth.principal, promotionPlan["applyId"], { expectedVersion: ready["version"], confirmationDigest: ready["promotionConfirmationDigest"], idempotencyKey: "promotion-restart-confirm" }); value.control.apply.claimPromotionSystem(promotionPlan["applyId"]); await value.control.close();
    const restarted = createControlPlane(value.config); const authRestarted = await authenticate(restarted).catch(() => auth); const snapshot = restarted.apply.snapshot(authRestarted.principal); const first = snapshot.find((entry) => entry["applyId"] === plan["applyId"]); const second = snapshot.find((entry) => entry["applyId"] === promotionPlan["applyId"]); expect(first).toMatchObject({ status: "apply-unknown", actions: { retryAllowed: false, canPromote: false } }); expect(second).toMatchObject({ status: "promotion-unknown", actions: { retryAllowed: false, canPromote: false } }); const firstCount = (restarted.database.connection.prepare("SELECT COUNT(*) AS n FROM m9_apply_evidence WHERE apply_id=? AND evidence_kind='restart-reconciliation'").get(plan["applyId"]) as { n: number }).n; const secondCount = (restarted.database.connection.prepare("SELECT COUNT(*) AS n FROM m9_apply_evidence WHERE apply_id=? AND evidence_kind='restart-reconciliation'").get(promotionPlan["applyId"]) as { n: number }).n; await restarted.close(); const again = createControlPlane(value.config); expect((again.database.connection.prepare("SELECT COUNT(*) AS n FROM m9_apply_evidence WHERE apply_id=? AND evidence_kind='restart-reconciliation'").get(plan["applyId"]) as { n: number }).n).toBe(firstCount); expect((again.database.connection.prepare("SELECT COUNT(*) AS n FROM m9_apply_evidence WHERE apply_id=? AND evidence_kind='restart-reconciliation'").get(promotionPlan["applyId"]) as { n: number }).n).toBe(secondCount); await again.close();
  });
});

const at = () => new Date().toISOString();
