import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { createTask, loadSnapshot, login, logout, mutateTask, setCsrfToken } from "./api.js";
import { boardColumns, classifyIncomingSequence, mergeTasks, newIdempotencyKey, statusLabel, taskColumn } from "./state.js";
import type { Adapter, ApiError, ConnectionState, Page, Snapshot, Task } from "./types.js";

const dateTime = (value: unknown): string => typeof value === "string" && Number.isFinite(Date.parse(value)) ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const shortId = (value: unknown): string => typeof value === "string" ? value.length > 22 ? `${value.slice(0, 12)}…${value.slice(-6)}` : value : "—";
const valueText = (value: unknown): string => value === null || value === undefined ? "—" : typeof value === "object" ? JSON.stringify(value, null, 2) : String(value);

function StatusPill({ tone, children }: { tone: string; children: ReactNode }) {
  return <span className={`pill pill-${tone}`}><span className="pill-mark" aria-hidden="true" />{children}</span>;
}

function Empty({ title, children }: { title: string; children: ReactNode }) {
  return <div className="empty"><div className="empty-orbit" aria-hidden="true"><span /></div><h3>{title}</h3><p>{children}</p></div>;
}

function LoginScreen({ onAuthenticated }: { onAuthenticated: () => Promise<void> }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (busy) return; setBusy(true); setError("");
    try { const result = await login(username, password); setCsrfToken(result.csrfToken); await onAuthenticated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Sign-in failed."); } finally { setBusy(false); }
  };
  return <main className="login-page">
    <section className="login-intro"><span className="eyebrow">LOCAL CONTROL SURFACE</span><div className="brand-mark large" aria-hidden="true"><i /><i /><i /></div><h1>Command work.<br /><em>Keep authority.</em></h1><p>One secure local surface for owner-directed tasks, approvals, worker readiness, and honest execution state.</p><div className="local-note"><span>01</span><div><strong>Loopback only</strong><small>No remote browser exposure in M6.</small></div></div></section>
    <section className="login-panel"><form onSubmit={submit} className="login-card"><span className="eyebrow">ADMINISTRATOR SESSION</span><h2>Welcome back</h2><p>Sign in to the authoritative Control Plane.</p><label>Username<input autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <div className="notice danger" role="alert">{error}</div>}<button className="primary wide" disabled={busy}>{busy ? "Authenticating…" : "Enter Command Center"}</button><small className="form-foot">Credentials remain in the authenticated same-origin request and are never placed in a URL.</small></form></section>
  </main>;
}

function TaskCard({ task, selected, onSelect }: { task: Task; selected: boolean; onSelect: () => void }) {
  const attempt = task.attempts.at(-1); const worker = attempt?.workerId ?? "unassigned";
  return <button className={`task-card ${selected ? "selected" : ""} ${task.executionUnknown ? "unknown" : ""}`} onClick={onSelect} aria-pressed={selected}>
    <div className="task-card-top"><span className="mono">{shortId(task.taskId)}</span><span className={`state-dot state-${taskColumn(task)}`} aria-hidden="true" /></div>
    <strong>{attempt?.instructions ?? "Task awaiting instructions"}</strong>
    <div className="task-meta"><span>{task.projectId}</span><span>{worker}</span></div>
    <div className="task-card-foot"><span className="state-label">{statusLabel(task)}</span><time>{dateTime(task.updatedAt)}</time></div>
  </button>;
}

function Board({ tasks, selectedTaskId, onSelect }: { tasks: Task[]; selectedTaskId: string | null; onSelect: (task: Task) => void }) {
  return <section className="page board-page"><header className="page-heading"><div><span className="eyebrow">AUTHORITATIVE LIFECYCLE</span><h1>Task board</h1><p>Cards move only when the Control Plane confirms a real state transition. Dragging is intentionally unavailable.</p></div><div className="count-block"><strong>{tasks.length}</strong><span>persisted tasks</span></div></header>
    {tasks.length === 0 ? <Empty title="No persisted tasks">Create the first owner-directed task in Chat. Refreshes and reconnects load it from the Control Plane.</Empty> : <div className="board-scroll" tabIndex={0} aria-label="Kanban board"><div className="board-grid">{boardColumns.map((column) => { const cards = tasks.filter((task) => taskColumn(task) === column.id); return <section className="board-column" key={column.id} aria-labelledby={`column-${column.id}`}><header><div><h2 id={`column-${column.id}`}>{column.title}</h2><p>{column.description}</p></div><span>{cards.length}</span></header><div className="card-stack">{cards.map((task) => <TaskCard key={task.taskId} task={task} selected={task.taskId === selectedTaskId} onSelect={() => onSelect(task)} />)}{cards.length === 0 && <div className="column-empty">No authoritative records</div>}</div></section>; })}</div></div>}
  </section>;
}

function Composer({ onCreated, busy }: { onCreated: (taskId: string) => Promise<void>; busy: boolean }) {
  const [instructions, setInstructions] = useState(""); const [projectId, setProjectId] = useState("chubz-ai"); const [workerId, setWorkerId] = useState("codex-cli"); const [scopeMode, setScopeMode] = useState("workspace-write"); const [paths, setPaths] = useState("README.md"); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (busy || instructions.trim().length === 0) return; setError("");
    const allowedPaths = paths.split(/[\n,]/u).map((value) => value.trim()).filter(Boolean);
    try {
      const result = await createTask({ idempotencyKey: newIdempotencyKey("task-create"), projectId, instructions, workerId, scopeMode: workerId === "codex-cli" ? scopeMode : undefined, allowedPaths: workerId === "codex-cli" ? allowedPaths : undefined, timeoutSec: 1_800 });
      setInstructions(""); await onCreated(String(result["taskId"]));
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Task creation failed."); }
  };
  return <form className="composer" onSubmit={submit}><div className="composer-fields"><label>Project<input value={projectId} onChange={(event) => setProjectId(event.target.value)} pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,127}" required /></label><label>Worker<select value={workerId} onChange={(event) => setWorkerId(event.target.value)}><option value="codex-cli">Codex CLI</option><option value="manual-relay">Manual relay</option></select></label>{workerId === "codex-cli" && <><label>Scope<select value={scopeMode} onChange={(event) => setScopeMode(event.target.value)}><option value="workspace-write">Workspace write</option><option value="read-only">Read only</option></select></label><label className="paths">Allowed paths<input value={paths} onChange={(event) => setPaths(event.target.value)} placeholder="README.md, src/app.ts" required /></label></>}</div><label className="instruction-label"><span>Task instructions</span><textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} rows={4} maxLength={64 * 1024} placeholder="Describe the bounded task. The server binds these instructions to an immutable attempt…" required /></label>{workerId === "manual-relay" && <div className="notice warning">Manual relay is owner-attested, has weaker provenance, and is not automated worker execution.</div>}{error && <div className="notice danger" role="alert">{error}</div>}<div className="composer-foot"><span>{instructions.length.toLocaleString()} / 65,536</span><button className="primary" disabled={busy || !instructions.trim()}>{busy ? "Submitting…" : "Create authoritative task"}</button></div></form>;
}

function Chat({ tasks, onSelect, onCreated, busy }: { tasks: Task[]; onSelect: (task: Task) => void; onCreated: (taskId: string) => Promise<void>; busy: boolean }) {
  return <section className="page chat-page"><header className="page-heading compact"><div><span className="eyebrow">OWNER INTERACTION</span><h1>Command chat</h1><p>Instructions and system status stay visibly separate. Worker-reported text is never treated as proof.</p></div></header><div className="conversation">{tasks.length === 0 ? <Empty title="The channel is ready">Create a task below. The first message becomes a persisted, server-bound attempt.</Empty> : tasks.slice().reverse().map((task) => { const attempt = task.attempts.at(-1); const result = task.manualResults.at(-1) ?? task.results.at(-1); return <article className="thread" key={task.taskId}><button className="owner-message" onClick={() => onSelect(task)}><span>Owner · {task.projectId}</span><p>{attempt?.instructions}</p><small>{shortId(task.taskId)} · {dateTime(attempt?.createdAt)}</small></button><button className="system-message" onClick={() => onSelect(task)}><span className="system-icon" aria-hidden="true">↗</span><div><strong>{statusLabel(task)}</strong><p>Control Plane confirmed version {task.version}. Attempt {shortId(task.attemptId)}.</p></div><time>{dateTime(task.updatedAt)}</time></button>{result && <button className="worker-message" onClick={() => onSelect(task)}><span>Worker-reported · {String(result["provenance"] ?? "automated adapter claim")}</span><pre>{String(result["text"] ?? result["output"] ?? "Structured result recorded")}</pre><small>Claim only — inspect authoritative evidence in task detail.</small></button>}</article>; })}</div><Composer onCreated={onCreated} busy={busy} /></section>;
}

function Metric({ label, value, warning }: { label: string; value: unknown; warning?: boolean }) { return <div className={`metric ${warning ? "metric-warning" : ""}`}><span>{label}</span><strong>{valueText(value)}</strong></div>; }
function AdapterCard({ adapter, bridgeConnected }: { adapter: Adapter; bridgeConnected: boolean }) {
  return <article className="adapter-card"><header><div className="adapter-symbol" aria-hidden="true">C</div><div><span className="eyebrow">{adapter.connectorTier} ADAPTER</span><h2>{adapter.workerId}</h2><p>{adapter.adapterId} · v{adapter.version}</p></div><StatusPill tone={adapter.readinessState === "ready" ? "good" : "warn"}>{adapter.readinessState}</StatusPill></header>{adapter.degradedBoundedLocal && <div className="assurance-warning"><strong>degraded-bounded-local</strong><p>This unelevated fallback is bounded local operation. It is not elevated isolation and is not represented as equivalent security.</p></div>}<div className="metric-grid"><Metric label="Authentication" value={adapter.authenticationState} /><Metric label="Health" value={adapter.healthStatus} warning={adapter.healthStatus !== "healthy"} /><Metric label="Sandbox capability" value={adapter.sandboxCapability} /><Metric label="Sandbox assurance" value={adapter.sandboxAssurance} warning={adapter.degradedBoundedLocal} /><Metric label="Cancellation" value={adapter.cancellationCapability} /><Metric label="Resume" value={adapter.resumeCapability} /><Metric label="Structured output" value={adapter.structuredOutputCapability} /><Metric label="Quota confidence" value={adapter.quotaConfidence} /></div><footer><span>Probe {dateTime(adapter.capabilityProbeAt)}</span><span className="mono">{shortId(adapter.executableHash ?? adapter.executableId)}</span></footer><button className="secondary wide" disabled={!bridgeConnected} title={bridgeConnected ? "Request an authoritative Bridge probe" : "An outbound Bridge connection is required"}>Refresh readiness {bridgeConnected ? "" : "— Bridge unavailable"}</button></article>;
}
function Adapters({ snapshot }: { snapshot: Snapshot }) {
  return <section className="page adapters-page"><header className="page-heading"><div><span className="eyebrow">PROVENANCE & READINESS</span><h1>Worker adapters</h1><p>Readiness comes from recorded Control Plane snapshots. Secret authentication material and raw environment data never appear here.</p></div></header><div className="adapter-list">{snapshot.adapters.map((adapter) => <AdapterCard adapter={adapter} bridgeConnected={snapshot.bridge.connected} key={adapter.readinessId} />)}<article className="adapter-card manual"><header><div className="adapter-symbol" aria-hidden="true">M</div><div><span className="eyebrow">MANUAL CONNECTOR</span><h2>Manual relay</h2><p>owner-attested transport</p></div><StatusPill tone="warn">manual only</StatusPill></header><div className="assurance-warning"><strong>Weaker manual provenance</strong><p>This surface records what the authenticated owner attests they pasted. It is not real automated execution, cannot self-authorize, and cannot cancel a human transport.</p></div><div className="metric-grid"><Metric label="Automated execution" value="No" /><Metric label="Artifact transport" value={snapshot.manualRelay.artifactTransportAvailable ? "Bridge available" : "Unavailable"} warning /><Metric label="Applied to project" value="False" /><Metric label="Applied to worktree" value="False" /></div></article></div></section>;
}

function DetailSection({ title, children }: { title: string; children: ReactNode }) { return <section className="detail-section"><h3>{title}</h3>{children}</section>; }
function DataList({ entries }: { entries: Array<[string, unknown]> }) { return <dl>{entries.map(([label, value]) => <div key={label}><dt>{label}</dt><dd className={label.toLowerCase().includes("id") || label.toLowerCase().includes("hash") ? "mono" : ""}>{valueText(value)}</dd></div>)}</dl>; }

function TaskDetail({ task, snapshot, pending, onClose, onMutated }: { task: Task; snapshot: Snapshot; pending: boolean; onClose: () => void; onMutated: () => Promise<void> }) {
  const [manualText, setManualText] = useState(""); const [attested, setAttested] = useState(false); const [error, setError] = useState(""); const attempt = task.attempts.at(-1); const assignment = task.assignments.at(-1); const scope = task.scopes.at(-1);
  const act = async (name: "approve-dispatch" | "cancel" | "decision" | "manual-text", body: Record<string, unknown>, confirmation?: string) => {
    if (pending || (confirmation && !window.confirm(confirmation))) return; setError("");
    try { await mutateTask(task.taskId, name, { idempotencyKey: newIdempotencyKey(name), expectedVersion: task.version, ...body }); setManualText(""); setAttested(false); await onMutated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The action failed."); }
  };
  return <aside className="detail-drawer" aria-label="Task detail"><header className="drawer-head"><div><span className="eyebrow">TASK DETAIL</span><h2>{shortId(task.taskId)}</h2><p>{task.projectId}</p></div><button className="icon-button" onClick={onClose} aria-label="Close task detail">×</button></header><div className="drawer-scroll"><div className="detail-status"><StatusPill tone={task.executionUnknown || ["FAILED", "BLOCKED"].includes(task.state) ? "danger" : ["COMPLETED", "APPROVED"].includes(task.state) ? "good" : "info"}>{statusLabel(task)}</StatusPill><span>version {task.version}</span><span>updated {dateTime(task.updatedAt)}</span></div>{task.executionUnknown && <div className="notice danger"><strong>Execution unknown</strong><br />The operation may have started, but completion is not proven. Retry remains structurally unavailable.</div>}{error && <div className="notice danger" role="alert">{error}</div>}
    <DetailSection title="Bound identity"><DataList entries={[["Task ID", task.taskId], ["Attempt ID", task.attemptId], ["Operation ID", task.operationId], ["Project", task.projectId], ["Worker", attempt?.workerId], ["Adapter", assignment?.["adapterId"]], ["Connector tier", assignment?.["connectorTier"]]]} /></DetailSection>
    <DetailSection title="Owner instructions"><div className="claim-box owner"><span>Owner instruction · immutable attempt {attempt?.sequence}</span><pre>{attempt?.instructions}</pre></div><DataList entries={[["Action digest", attempt?.actionDigest], ["Timeout", attempt?.timeoutSec ? `${attempt.timeoutSec}s` : null], ["Clean worktree required", attempt?.requiresCleanWorktree]]} /></DetailSection>
    <DetailSection title="Assignment & lease"><DataList entries={[["Assignment status", assignment?.["status"]], ["Assignment ID", assignment?.["assignment_id"]], ["Owner confirmed", assignment?.["ownerConfirmed"]], ["Readiness snapshot", assignment?.["readinessSnapshotRef"]], ["Lease status", task.lease?.["status"]], ["Lease ID", task.lease?.["lease_id"]], ["Queue status", task.queue?.["status"]]]} /></DetailSection>
    <DetailSection title="Approval & capability grant"><DataList entries={[["Approval status", task.approval?.["status"] ?? (task.actions.canApproveDispatch ? "pending" : null)], ["Approval ID", task.approval?.["approval_id"]], ["Grant status", task.grant?.["status"]], ["Grant ID", task.grant?.["grant_id"]], ["Grant expires", dateTime(task.grant?.["expires_at"])], ["Consumed", task.grant?.["consumed_at"] ? "yes" : "no"]]} /><p className="subtle">Grant secret and authentication signature are intentionally excluded from browser responses.</p></DetailSection>
    {scope && <DetailSection title="Write scope & policy"><DataList entries={[["Scope ID", scope["scope_id"]], ["Scope hash", scope["scope_hash"]], ["Allowed paths", scope["allowedExactPaths"]], ["Permissions", scope["permissions"]], ["Denied classes", scope["deniedPathClasses"]], ["Policy outcome", scope["policyOutcome"]]]} /></DetailSection>}
    <DetailSection title="Results & operation journal">{task.manualResults.length === 0 && task.results.length === 0 ? <p className="subtle">No authoritative result has been recorded.</p> : <>{task.manualResults.map((result) => <div className="claim-box manual" key={String(result["result_ref"])}><span>Worker-claimed · owner-attested manual relay · weaker provenance</span><pre>{String(result["text"] ?? "")}</pre><small>Applied to project: false · Applied to worktree: false</small></div>)}{task.results.map((result) => <div className="claim-box" key={String(result["result_ref"])}><span>Worker-reported output · {String(result["provenance"])}</span><pre>{String(result["output"] ?? "")}</pre><DataList entries={[["Execution state", result["state"]], ["Failure code", result["failureCode"]], ["Journal ref", result["journalRef"]], ["Truncated", result["outputTruncated"]]]} /></div>)}</>}</DetailSection>
    <DetailSection title="Meaningful history"><ol className="timeline">{task.transitions.map((event) => <li key={String(event["transition_id"])}><span /><div><strong>{String(event["from_state"])} → {String(event["to_state"])}</strong><p>{String(event["actor"])} · version {String(event["resulting_version"])}</p><time>{dateTime(event["occurred_at"])}</time></div></li>)}</ol></DetailSection>
    {task.actions.canSubmitManualText && <DetailSection title="Manual relay response"><div className="notice warning"><strong>Manual and owner-attested</strong><br />Paste only the worker response. This does not prove automated identity or execution.</div><label>Response type<select defaultValue="text" id={`response-type-${task.taskId}`}><option value="text">Text</option><option value="review">Review</option><option value="design">Design</option></select></label><label>Worker response<textarea rows={7} maxLength={64 * 1024} value={manualText} onChange={(event) => setManualText(event.target.value)} /></label><label className="check"><input type="checkbox" checked={attested} onChange={(event) => setAttested(event.target.checked)} />I attest that I manually received and pasted this response for this exact attempt.</label><button className="primary wide" disabled={pending || !attested || !manualText.trim()} onClick={() => { const element = document.getElementById(`response-type-${task.taskId}`) as HTMLSelectElement | null; void act("manual-text", { text: manualText, responseType: element?.value ?? "text", attested: true }, "Record this as an owner-attested manual relay response?"); }}>Record manual response</button><div className="artifact-boundary"><strong>Quarantined artifacts</strong><p>Allowed types: {snapshot.manualRelay.allowedArtifactTypes.join(", ")}. Artifact transport is unavailable until an authoritative outbound Bridge is connected. No preview, extraction, apply, copy, cherry-pick, or execution is offered.</p><ul><li>Safe filename / identifier</li><li>Declared type and bounded size</li><li>SHA-256 declaration and validation</li><li>Quarantine status</li><li>Applied to project: false</li><li>Applied to worktree: false</li></ul><button disabled>Import through Bridge unavailable</button></div></DetailSection>}
    <DetailSection title="Owner controls"><div className="action-row">{task.actions.canApproveDispatch && <button className="primary" disabled={pending} onClick={() => void act("approve-dispatch", {}, "Approve this exact worker, action digest, scope, and single-use grant?")}>Approve dispatch</button>}{task.actions.canDecideResult && <><button className="primary" disabled={pending} onClick={() => void act("decision", { decision: "approve" }, "Approve this recorded result?")}>Approve result</button><button className="secondary danger-text" disabled={pending} onClick={() => void act("decision", { decision: "reject" }, "Reject this recorded result? This state is terminal.")}>Reject</button></>}{task.actions.canCancel && <button className="secondary danger-text" disabled={pending} onClick={() => void act("cancel", {}, "Request cancellation for this exact authoritative task version?")}>Cancel task</button>}<button className="secondary" disabled title="A new immutable attempt is available only when the backend explicitly supports retry">Retry unavailable</button></div></DetailSection>
    </div></aside>;
}

export default function App() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [authenticated, setAuthenticated] = useState<boolean | null>(null); const [page, setPage] = useState<Page>("chat"); const [selectedTaskId, setSelectedTaskId] = useState<string | null>(null); const [connection, setConnection] = useState<ConnectionState>("connecting"); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const [globalError, setGlobalError] = useState("");
  const retryRef = useRef(0); const socketRef = useRef<WebSocket | null>(null); const refreshInFlight = useRef<Promise<void> | null>(null); const cursorRef = useRef({ streamId: "ui-tasks", lastConsumedSequence: 0 });
  const refresh = useCallback(async () => {
    if (refreshInFlight.current) return refreshInFlight.current;
    const work = (async () => { try { const fresh = await loadSnapshot(); setSnapshot((current) => current ? { ...fresh, tasks: mergeTasks(current.tasks, fresh.tasks) } : fresh); setAuthenticated(true); setGlobalError(""); } catch (reason) { const error = reason as ApiError; if (error.status === 401) { setAuthenticated(false); setSnapshot(null); } else { setGlobalError(error.message || "Authoritative snapshot is unavailable."); } } finally { setLoading(false); refreshInFlight.current = null; } })();
    refreshInFlight.current = work; return work;
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { if (snapshot?.cursor) cursorRef.current = { streamId: snapshot.cursor.streamId, lastConsumedSequence: Math.max(cursorRef.current.lastConsumedSequence, snapshot.cursor.lastConsumedSequence) }; }, [snapshot?.cursor]);
  useEffect(() => {
    if (!authenticated || !snapshot) return;
    let cancelled = false; let retryTimer: number | undefined;
    const connect = () => {
      if (cancelled) return; setConnection(retryRef.current === 0 ? "connecting" : "resynchronizing");
      const protocol = location.protocol === "https:" ? "wss:" : "ws:"; const socket = new WebSocket(`${protocol}//${location.host}/v1/ws`); socketRef.current = socket;
      socket.addEventListener("open", () => { retryRef.current = 0; setConnection("live"); const cursor = cursorRef.current; socket.send(JSON.stringify({ protocolVersion: "1.0", messageId: `resume-${crypto.randomUUID()}`, messageKind: "stream.resume", sentAt: new Date().toISOString(), payload: { cursor } })); });
      socket.addEventListener("message", (event) => { try { const message = JSON.parse(String(event.data)) as Record<string, unknown>; if (message["messageKind"] === "protocol.error") { setConnection("resynchronizing"); void refresh().then(() => setConnection("live")); return; } if (message["messageKind"] !== "task.event") return; const payload = message["payload"] as Record<string, unknown>; const sequence = Number(payload["sequence"]); const classification = classifyIncomingSequence(cursorRef.current.lastConsumedSequence, sequence); if (classification === "duplicate") return; if (classification !== "next") { setConnection("resynchronizing"); void refresh().then(() => setConnection("live")); return; } cursorRef.current = { ...cursorRef.current, lastConsumedSequence: sequence }; setSnapshot((current) => current ? { ...current, cursor: { ...current.cursor, lastConsumedSequence: sequence } } : current); void refresh(); } catch { setConnection("resynchronizing"); void refresh(); } });
      socket.addEventListener("close", () => { if (cancelled) return; setConnection("disconnected"); retryRef.current += 1; retryTimer = window.setTimeout(connect, Math.min(1_000 * 2 ** retryRef.current, 15_000)); });
      socket.addEventListener("error", () => socket.close());
    };
    connect(); const polling = window.setInterval(() => { void refresh(); }, 30_000);
    return () => { cancelled = true; window.clearInterval(polling); if (retryTimer !== undefined) window.clearTimeout(retryTimer); socketRef.current?.close(); };
  }, [authenticated, refresh, snapshot?.cursor.streamId]);
  const selected = useMemo(() => snapshot?.tasks.find((task) => task.taskId === selectedTaskId) ?? null, [snapshot, selectedTaskId]);
  const mutateRefresh = async () => { setPending(true); try { await refresh(); } finally { setPending(false); } };
  const created = async (taskId: string) => { setPending(true); try { await refresh(); setSelectedTaskId(taskId); } finally { setPending(false); } };
  if (authenticated === false) return <LoginScreen onAuthenticated={refresh} />;
  if (loading || authenticated === null || !snapshot) return <main className="boot"><div className="brand-mark large"><i /><i /><i /></div><h1>CHUBZ AI</h1><p>{globalError || "Loading authoritative state…"}</p></main>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark" aria-hidden="true"><i /><i /><i /></div><div><strong>CHUBZ AI</strong><span>COMMAND CENTER</span></div></div><nav aria-label="Primary navigation"><button className={page === "chat" ? "active" : ""} onClick={() => setPage("chat")}><span>⌁</span>Chat</button><button className={page === "board" ? "active" : ""} onClick={() => setPage("board")}><span>▦</span>Task board</button><button className={page === "adapters" ? "active" : ""} onClick={() => setPage("adapters")}><span>◫</span>Adapters</button></nav><div className="sidebar-foot"><span className="eyebrow">SESSION</span><strong>{snapshot.session.username}</strong><small>Sole administrator · local</small><button onClick={() => { void logout().finally(() => { setAuthenticated(false); setSnapshot(null); }); }}>Sign out</button></div></aside><main className="workspace"><header className="topbar"><div className="mobile-brand">CHUBZ AI</div><div className="status-strip"><StatusPill tone={snapshot.controlPlane.readiness === "ready" ? "good" : "danger"}>Control Plane {snapshot.controlPlane.readiness}</StatusPill><StatusPill tone={snapshot.bridge.connected ? "good" : "warn"}>Bridge {snapshot.bridge.availability}</StatusPill><StatusPill tone={connection === "live" ? "good" : connection === "disconnected" ? "danger" : "warn"}>{connection}</StatusPill></div><button className="refresh-button" onClick={() => void refresh()} disabled={pending} aria-label="Refresh authoritative state">↻ <span>Refresh</span></button></header>{globalError && <div className="global-alert" role="alert"><strong>Authoritative state unavailable</strong><span>{globalError}</span><button onClick={() => void refresh()}>Try again</button></div>}{page === "chat" && <Chat tasks={snapshot.tasks} onSelect={(task) => setSelectedTaskId(task.taskId)} onCreated={created} busy={pending} />}{page === "board" && <Board tasks={snapshot.tasks} selectedTaskId={selectedTaskId} onSelect={(task) => setSelectedTaskId(task.taskId)} />}{page === "adapters" && <Adapters snapshot={snapshot} />}</main>{selected && <TaskDetail task={selected} snapshot={snapshot} pending={pending} onClose={() => setSelectedTaskId(null)} onMutated={mutateRefresh} />}</div>;
}
