import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { access, chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { promisify } from "node:util";
import { afterEach, describe, expect, it } from "vitest";
import { SafeApplyExecutor, type M9PrepareRequest } from "../src/safe-apply.js";

const exec = promisify(execFile);
const roots: string[] = [];
const git = async (cwd: string, args: readonly string[]): Promise<string> => (await exec("git", [...args], { cwd, encoding: "utf8", windowsHide: true, env: { ...process.env, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_GLOBAL: process.platform === "win32" ? "NUL" : "/dev/null" } })).stdout.trim();
const hash = (value: string): `sha256:${string}` => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const identity = (path: string): `sha256:${string}` => hash((process.platform === "win32" ? resolve(path).toLowerCase() : resolve(path)).replace(/^\\\\\?\\/u, ""));

type Fixture = Readonly<{ root: string; seed: string; source: string; target: string; applyRoot: string; baseline: string; reviewed: string; targetRemote: string }>;
async function fixture(): Promise<Fixture> {
  const root = await mkdtemp(resolve(process.cwd(), "m9-git-fixture-")); roots.push(root); const seed = resolve(root, "seed"); const source = resolve(root, "source"); const target = resolve(root, "target"); const targetRemote = resolve(root, "target-remote.git"); const applyRoot = resolve(root, "apply-root"); await mkdir(seed); await git(seed, ["init", "-b", "main"]); await writeFile(resolve(seed, "file.txt"), "baseline\n"); await git(seed, ["add", "file.txt"]); await git(seed, ["-c", "user.name=Fixture", "-c", "user.email=fixture@invalid", "commit", "-m", "baseline"]); const baseline = await git(seed, ["rev-parse", "HEAD"]); await git(root, ["clone", "--no-local", seed, source]); await git(root, ["clone", "--bare", "--no-local", seed, targetRemote]); await git(root, ["clone", "--no-local", targetRemote, target]); await git(target, ["checkout", "--detach", baseline]); await writeFile(resolve(source, "file.txt"), "baseline\nreviewed\n"); await git(source, ["add", "file.txt"]); await git(source, ["-c", "user.name=Worker", "-c", "user.email=worker@invalid", "commit", "-m", "reviewed change"]); const reviewed = await git(source, ["rev-parse", "HEAD"]); await mkdir(applyRoot); return { root, seed, source, target, applyRoot, baseline, reviewed, targetRemote };
}
const request = (value: Fixture, applyId = "apply-test-0001", validations: M9PrepareRequest["validations"] = [{ validationId: "node-pass", kind: "test", executable: process.execPath, args: ["-e", "console.log('1 test passed')"], cwd: ".", timeoutMs: 10_000 }]): M9PrepareRequest => ({ applyId, ownerId: "owner-test", sourceProjectId: "project-source", targetProjectId: "project-target", taskId: "task-test", attemptId: "attempt-test", operationId: "operation-test", workerId: "codex-cli", adapterId: "codex-cli", captureId: "capture-test", packageId: "package-test", packageSchemaVersion: "m7.review-package/v1", packageDigest: hash("package"), manifestDigest: hash("manifest"), sourceRepositoryPath: value.source, sourceRepositoryIdentity: identity(value.source), reviewedBaseline: value.baseline, reviewedCommit: value.reviewed, reviewedChangedPaths: ["file.txt"], targetRepositoryPath: value.target, targetRepositoryIdentity: identity(value.target), targetRef: "refs/heads/main", expectedTargetHead: value.baseline, applyMode: "exact-reviewed-commit", applyRoot: value.applyRoot, validationPlanId: "required", validations, preparationDigest: hash("preparation") });

afterEach(async () => { for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true }); });

describe("M9 safe exact-commit apply", () => {
  it("prepares in isolation, preserves a dirty owner worktree, validates, promotes by CAS, and never pushes", async () => {
    const value = await fixture(); await writeFile(resolve(value.target, "owner-untracked.txt"), "keep me\n"); const hook = resolve(value.target, ".git", "hooks", "post-commit"); await writeFile(hook, "#!/bin/sh\nexit 99\n"); await chmod(hook, 0o755); const gateCalls: string[] = []; const executor = new SafeApplyExecutor(value.root, (projectId, operationId) => gateCalls.push(`${projectId}:${operationId}`)); const input = request(value); const prepared = await executor.prepare(input);
    expect(prepared.status).toBe("ready"); expect(prepared.oldHead).toBe(value.baseline); expect(prepared.preparedHead).not.toBe(value.baseline); expect(prepared.changedPaths).toEqual(["file.txt"]); expect(prepared.validations[0]?.outcome).toBe("passed"); expect(await readFile(resolve(value.target, "owner-untracked.txt"), "utf8")).toBe("keep me\n"); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(value.baseline); expect(await executor.prepare(input)).toEqual(prepared);
    const promoteInput = { applyId: input.applyId, ownerId: input.ownerId, targetProjectId: input.targetProjectId, targetRepositoryPath: input.targetRepositoryPath, targetRepositoryIdentity: input.targetRepositoryIdentity, targetRef: input.targetRef, expectedOldHead: input.expectedTargetHead, preparedHead: prepared.preparedHead!, applyWorktree: prepared.applyWorktree, applyWorktreeDigest: prepared.applyWorktreeDigest!, packageDigest: input.packageDigest, validationEvidenceDigest: prepared.validationEvidenceDigest, confirmationDigest: hash("confirmation") } as const; await expect(executor.promote({ ...promoteInput, packageDigest: hash("substituted-package") })).rejects.toThrow("evidence binding"); const promoted = await executor.promote(promoteInput); expect(promoted.status).toBe("promoted"); expect(await executor.promote(promoteInput)).toEqual(promoted); await expect(executor.promote({ ...promoteInput, preparedHead: value.reviewed })).rejects.toThrow("idempotency conflict"); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(prepared.preparedHead); expect(await git(value.targetRemote, ["rev-parse", "refs/heads/main"])).toBe(value.baseline); expect(gateCalls.length).toBeGreaterThan(5); await executor.cleanupPreparedWorkspace({ applyId: input.applyId, targetProjectId: input.targetProjectId, targetRepositoryPath: input.targetRepositoryPath, applyWorktree: prepared.applyWorktree }); await expect(access(resolve(value.applyRoot, input.applyId))).rejects.toThrow(); expect(await readFile(resolve(value.target, "owner-untracked.txt"), "utf8")).toBe("keep me\n");
  }, 30_000);

  it("fails closed on conflict and leaves the target ref unchanged", async () => {
    const value = await fixture(); await writeFile(resolve(value.target, "file.txt"), "target divergence\n"); await git(value.target, ["add", "file.txt"]); await git(value.target, ["-c", "user.name=Owner", "-c", "user.email=owner@invalid", "commit", "-m", "target divergence"]); const diverged = await git(value.target, ["rev-parse", "HEAD"]); await git(value.target, ["update-ref", "refs/heads/main", diverged, value.baseline]); const input = { ...request(value, "apply-conflict"), expectedTargetHead: diverged }; const prepared = await new SafeApplyExecutor(value.root).prepare(input); expect(prepared.status).toBe("conflicted"); expect(prepared.conflicts).toEqual(["file.txt"]); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(diverged);
  }, 30_000);

  it("blocks a checked-out target branch without touching owner files", async () => {
    const value = await fixture(); await git(value.target, ["switch", "main"]); await writeFile(resolve(value.target, "owner.txt"), "dirty\n"); await expect(new SafeApplyExecutor(value.root).prepare(request(value, "apply-checked-out"))).rejects.toThrow("checked out"); expect(await readFile(resolve(value.target, "owner.txt"), "utf8")).toBe("dirty\n"); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(value.baseline);
  }, 30_000);

  it("records failed authoritative validation and refuses promotion", async () => {
    const value = await fixture(); const input = request(value, "apply-validation-fail", [{ validationId: "node-fail", kind: "test", executable: process.execPath, args: ["-e", "console.error('1 test failed');process.exit(2)"], cwd: ".", timeoutMs: 10_000 }]); const executor = new SafeApplyExecutor(value.root); const prepared = await executor.prepare(input); expect(prepared.status).toBe("validation-failed"); expect(prepared.validations[0]).toMatchObject({ outcome: "failed", exitCode: 2, parsedCounts: { failed: 1 } }); await expect(executor.promote({ applyId: input.applyId, ownerId: input.ownerId, targetProjectId: input.targetProjectId, targetRepositoryPath: input.targetRepositoryPath, targetRepositoryIdentity: input.targetRepositoryIdentity, targetRef: input.targetRef, expectedOldHead: input.expectedTargetHead, preparedHead: prepared.preparedHead!, applyWorktree: prepared.applyWorktree, applyWorktreeDigest: prepared.applyWorktreeDigest!, packageDigest: input.packageDigest, validationEvidenceDigest: prepared.validationEvidenceDigest, confirmationDigest: hash("confirmation") })).rejects.toThrow("not promotion-ready");
  }, 30_000);

  it("detects stale target movement before compare-and-swap promotion", async () => {
    const value = await fixture(); const executor = new SafeApplyExecutor(value.root); await writeFile(resolve(value.target, "stale.txt"), "owner movement\n"); await git(value.target, ["add", "stale.txt"]); await git(value.target, ["-c", "user.name=Owner", "-c", "user.email=owner@invalid", "commit", "-m", "move target before prepare"]); const moved = await git(value.target, ["rev-parse", "HEAD"]); await git(value.target, ["update-ref", "refs/heads/main", moved, value.baseline]); await expect(executor.prepare(request(value, "apply-stale-before-prepare"))).rejects.toThrow("stale"); await git(value.target, ["update-ref", "refs/heads/main", value.baseline, moved]); const input = request(value, "apply-stale"); const prepared = await executor.prepare(input); await git(value.target, ["update-ref", "refs/heads/main", value.reviewed, value.baseline]); const promoted = await executor.promote({ applyId: input.applyId, ownerId: input.ownerId, targetProjectId: input.targetProjectId, targetRepositoryPath: input.targetRepositoryPath, targetRepositoryIdentity: input.targetRepositoryIdentity, targetRef: input.targetRef, expectedOldHead: input.expectedTargetHead, preparedHead: prepared.preparedHead!, applyWorktree: prepared.applyWorktree, applyWorktreeDigest: prepared.applyWorktreeDigest!, packageDigest: input.packageDigest, validationEvidenceDigest: prepared.validationEvidenceDigest, confirmationDigest: hash("confirmation") }); expect(promoted.status).toBe("stale"); expect(promoted.promotedAt).toBeNull();
  }, 30_000);

  it("rejects traversal and repository-controlled filters before application", async () => {
    const value = await fixture(); await expect(new SafeApplyExecutor(value.root).prepare({ ...request(value, "apply-traversal"), reviewedChangedPaths: ["../escape"] })).rejects.toThrow("unsafe"); await git(value.target, ["config", "filter.evil.clean", "node evil.js"]); await expect(new SafeApplyExecutor(value.root).prepare(request(value, "apply-filter"))).rejects.toThrow("configuration"); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(value.baseline);
  }, 30_000);

  it("records timeout or cancellation truthfully and never promotes it", async () => {
    const value = await fixture(); const input = request(value, "apply-timeout", [{ validationId: "node-timeout", kind: "test", executable: process.execPath, args: ["-e", "setInterval(()=>{},1000)"], cwd: ".", timeoutMs: 50 }]); const executor = new SafeApplyExecutor(value.root); const prepared = await executor.prepare(input); expect(["validation-failed", "apply-unknown", "cancelled"]).toContain(prepared.status); expect(["timeout", "unknown", "cancelled"]).toContain(prepared.validations[0]?.outcome); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(value.baseline);
  }, 30_000);

  it("fails closed when emergency stop activates at an external-operation boundary", async () => {
    const value = await fixture(); let calls = 0; const executor = new SafeApplyExecutor(value.root, () => { calls += 1; if (calls >= 8) throw new Error("emergency stop active"); }); await expect(executor.prepare(request(value, "apply-emergency"))).rejects.toThrow("emergency stop"); expect(await git(value.target, ["rev-parse", "refs/heads/main"])).toBe(value.baseline);
  }, 30_000);
});
