import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, realpath, rename, rm, writeFile } from "node:fs/promises";
import { basename, isAbsolute, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
import { detectRedactions, redactText } from "@chubz/shared";
import { NodeProcessSpawner, ProcessSupervisor, WindowsProcessTreeController } from "./process-supervisor.js";

const execFileAsync = promisify(execFile);
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u;
const HASH = /^sha256:[0-9a-f]{64}$/u;
const OID = /^[0-9a-f]{40,64}$/u;
const REF = /^refs\/heads\/[A-Za-z0-9](?:[A-Za-z0-9._/-]{0,126}[A-Za-z0-9])?$/u;
const FORBIDDEN_PATH = /(?:^|\/)(?:\.git(?:\/|$)|\.env(?:\.|$)|\.npmrc$|\.pypirc$|\.netrc$|credentials?(?:\/|$)|secrets?(?:\/|$)|tokens?(?:\/|$)|id_(?:rsa|dsa|ecdsa|ed25519)$)|\.(?:pem|key|p12|pfx|exe|dll|com|scr|msi|ps1|bat|cmd)$/iu;

export const M9_APPLY_LIMITS = Object.freeze({ maxFiles: 512, maxOutputBytes: 128 * 1024, maxGitBytes: 4 * 1024 * 1024, maxValidations: 16, maxValidationMs: 30 * 60_000, maxApplyBytes: 256 * 1024 * 1024 } as const);
export type M9ValidationCommand = Readonly<{ validationId: string; kind: "test" | "build" | "typecheck" | "lint" | "runtime-smoke" | "browser-e2e"; executable: string; args: readonly string[]; cwd: string; timeoutMs: number }>;
export type M9WorktreeObservation = Readonly<{ pathDigest: `sha256:${string}`; head: string | null; branchRef: string | null; statusDigest: `sha256:${string}`; dirty: boolean }>;
export type M9PrepareRequest = Readonly<{
  applyId: string; ownerId: string; sourceProjectId: string; targetProjectId: string; taskId: string; attemptId: string; operationId: string; workerId: string; adapterId: string;
  captureId: string; packageId: string; packageSchemaVersion: "m7.review-package/v1"; packageDigest: `sha256:${string}`; manifestDigest: `sha256:${string}`;
  sourceRepositoryPath: string; sourceRepositoryIdentity: `sha256:${string}`; reviewedBaseline: string; reviewedCommit: string; reviewedChangedPaths: readonly string[];
  targetRepositoryPath: string; targetRepositoryIdentity: `sha256:${string}`; targetRef: string; expectedTargetHead: string; applyMode: "exact-reviewed-commit";
  applyRoot: string; validationPlanId: string; validations: readonly M9ValidationCommand[]; preparationDigest: `sha256:${string}`;
}>;
export type M9ValidationResult = Readonly<{ validationId: string; kind: string; executable: string; args: readonly string[]; commandDigest: `sha256:${string}`; cwd: string; timeoutMs: number; startedAt: string; finishedAt: string; outcome: "passed" | "failed" | "timeout" | "cancelled" | "unknown"; exitCode: number | null; stdout: string; stderr: string; stdoutTruncated: boolean; stderrTruncated: boolean; parsedCounts: Readonly<{ passed: number | null; failed: number | null; skipped: number | null; total: number | null }>; processTree: unknown }>;
export type M9PrepareResult = Readonly<{ applyId: string; status: "ready" | "conflicted" | "validation-failed" | "cancelled" | "apply-unknown"; packageDigest: `sha256:${string}`; preparationDigest: `sha256:${string}`; targetRepositoryIdentity: `sha256:${string}`; oldHead: string; preparedHead: string | null; targetRef: string; applyWorktree: string; worktreesBefore: readonly M9WorktreeObservation[]; worktreesAfter: readonly M9WorktreeObservation[]; changedPaths: readonly string[]; diffStatistics: Readonly<{ files: number; additions: number; deletions: number; binaryFiles: number }>; conflicts: readonly string[]; validations: readonly M9ValidationResult[]; validationEvidenceDigest: `sha256:${string}`; applyWorktreeDigest: `sha256:${string}` | null; previewDigest: `sha256:${string}`; rollback: Readonly<{ originalHead: string; promotedHead: string | null; revertCandidateAvailable: boolean; automaticRollback: false; limitations: readonly string[] }>; startedAt: string; finishedAt: string }>;
export type M9PromoteRequest = Readonly<{ applyId: string; ownerId: string; targetProjectId: string; targetRepositoryPath: string; targetRepositoryIdentity: `sha256:${string}`; targetRef: string; expectedOldHead: string; preparedHead: string; applyWorktree: string; applyWorktreeDigest: `sha256:${string}`; packageDigest: `sha256:${string}`; validationEvidenceDigest: `sha256:${string}`; confirmationDigest: `sha256:${string}` }>;
export type M9PromotionResult = Readonly<{ applyId: string; status: "promoted" | "stale" | "blocked" | "promotion-unknown"; oldHead: string; newHead: string; targetRef: string; promotedAt: string | null; rollback: Readonly<{ originalHead: string; promotedHead: string; revertCandidateAvailable: true; automaticRollback: false; limitations: readonly string[] }> }>;

type Journal = Readonly<{ schemaVersion: "m9.apply-journal/v1"; applyId: string; requestDigest: `sha256:${string}`; stage: "preparing" | "applying" | "validating" | "ready" | "conflicted" | "validation-failed" | "cancelled" | "apply-unknown" | "promoting" | "promoted" | "stale" | "promotion-unknown"; result: M9PrepareResult | M9PromotionResult | null; updatedAt: string }>;
type EmergencyGate = (projectId: string, operationId: string) => void;

const sha256 = (value: string | Buffer): `sha256:${string}` => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const canonicalPath = (value: string): string => { const path = resolve(value).replace(/^\\\\\?\\/u, ""); return process.platform === "win32" ? path.toLowerCase() : path; };
const contained = (root: string, candidate: string): boolean => { const rel = relative(canonicalPath(root), canonicalPath(candidate)); return rel === "" || rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel); };
const repositoryIdentity = (value: string): `sha256:${string}` => sha256(canonicalPath(value));
const safeId = (value: string, label: string): void => { if (!ID.test(value) || value.includes("..")) throw new Error(`${label} is invalid`); };
const safePath = (value: string): string => { const path = value.replaceAll("\\", "/"); if (!path || path.startsWith("/") || path.includes("\0") || path.split("/").some((part) => !part || part === "." || part === "..") || FORBIDDEN_PATH.test(path)) throw new Error("unsafe or forbidden reviewed path"); return path; };
const sanitize = (value: string): string => { const bounded = Buffer.from(value, "utf8").subarray(0, M9_APPLY_LIMITS.maxOutputBytes).toString("utf8"); const findings = detectRedactions(bounded); if (!findings.ok) return "[REDACTED: scanner failure]"; const result = redactText(bounded, findings.value); return result.ok ? result.value.text : "[REDACTED: scanner failure]"; };
const parseCounts = (value: string): M9ValidationResult["parsedCounts"] => { const count = (name: string) => { const match = new RegExp(`(?:^|\\s)(\\d+)\\s+(?:tests?\\s+)?${name}\\b`, "iu").exec(value); return match ? Number(match[1]) : null; }; const passed = count("passed"); const failed = count("failed"); const skipped = count("skipped"); return { passed, failed, skipped, total: passed === null && failed === null && skipped === null ? null : (passed ?? 0) + (failed ?? 0) + (skipped ?? 0) }; };

async function rejectLinks(target: string): Promise<void> {
  const absolute = resolve(target); const root = absolute.slice(0, absolute.indexOf(sep) + 1); let cursor = root;
  for (const part of absolute.slice(root.length).split(sep).filter(Boolean)) { cursor = resolve(cursor, part); try { const info = await lstat(cursor); if (info.isSymbolicLink() || (info as unknown as { isReparsePoint?: () => boolean }).isReparsePoint?.()) throw new Error("symbolic links, junctions, and reparse points are rejected"); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return; throw error; } }
}

const gitEnvironment = (): Record<string, string> => ({ ...Object.fromEntries(["PATH", "Path", "PATHEXT", "SystemRoot", "ComSpec", "TEMP", "TMP"].flatMap((key) => process.env[key] === undefined ? [] : [[key, process.env[key]!]])), GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_GLOBAL: process.platform === "win32" ? "NUL" : "/dev/null", GIT_TERMINAL_PROMPT: "0", GIT_OPTIONAL_LOCKS: "0", GIT_CONFIG_COUNT: "5", GIT_CONFIG_KEY_0: "core.hooksPath", GIT_CONFIG_VALUE_0: process.platform === "win32" ? "NUL" : "/dev/null", GIT_CONFIG_KEY_1: "diff.external", GIT_CONFIG_VALUE_1: "", GIT_CONFIG_KEY_2: "core.attributesFile", GIT_CONFIG_VALUE_2: process.platform === "win32" ? "NUL" : "/dev/null", GIT_CONFIG_KEY_3: "filter.lfs.required", GIT_CONFIG_VALUE_3: "false", GIT_CONFIG_KEY_4: "protocol.file.allow", GIT_CONFIG_VALUE_4: "always" });

export class SafeApplyExecutor {
  private readonly supervisor: ProcessSupervisor;
  private readonly controllers = new Map<string, AbortController>();
  public constructor(private readonly approvedRoot = "B:\\AI_Agent_folder", private readonly emergencyGate?: EmergencyGate, supervisor?: ProcessSupervisor) { this.supervisor = supervisor ?? new ProcessSupervisor(new NodeProcessSpawner(), new WindowsProcessTreeController()); }

  private async git(cwd: string, projectId: string, operationId: string, args: readonly string[], allowFailure = false): Promise<Readonly<{ stdout: string; stderr: string; exitCode: number }>> {
    this.emergencyGate?.(projectId, operationId);
    try { const result = await execFileAsync("git", ["-c", `core.hooksPath=${process.platform === "win32" ? "NUL" : "/dev/null"}`, "-c", "diff.external=", "-c", `core.attributesFile=${process.platform === "win32" ? "NUL" : "/dev/null"}`, ...args], { cwd, encoding: "utf8", windowsHide: true, timeout: 60_000, maxBuffer: M9_APPLY_LIMITS.maxGitBytes, env: gitEnvironment() }); return { stdout: result.stdout, stderr: result.stderr, exitCode: 0 }; }
    catch (error) { const failure = error as Error & { stdout?: string; stderr?: string; code?: number }; if (allowFailure && typeof failure.code === "number") return { stdout: failure.stdout ?? "", stderr: failure.stderr ?? "", exitCode: failure.code }; throw new Error("bounded Git operation failed"); }
  }

  private journalPath(root: string): string { return resolve(root, "apply-journal.json"); }
  private async writeJournal(root: string, journal: Journal): Promise<void> { const target = this.journalPath(root); const staging = `${target}.staging`; await writeFile(staging, `${canonical(journal)}\n`, { mode: 0o600 }); await rename(staging, target); }
  private async readJournal(root: string): Promise<Journal | null> { try { return JSON.parse(await readFile(this.journalPath(root), "utf8")) as Journal; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return null; throw error; } }

  private validateRequest(input: M9PrepareRequest): void {
    for (const [label, value] of Object.entries({ applyId: input.applyId, ownerId: input.ownerId, sourceProjectId: input.sourceProjectId, targetProjectId: input.targetProjectId, taskId: input.taskId, attemptId: input.attemptId, operationId: input.operationId, workerId: input.workerId, adapterId: input.adapterId, captureId: input.captureId, packageId: input.packageId, validationPlanId: input.validationPlanId })) safeId(value, label);
    if (!HASH.test(input.packageDigest) || !HASH.test(input.manifestDigest) || !HASH.test(input.sourceRepositoryIdentity) || !HASH.test(input.targetRepositoryIdentity) || !HASH.test(input.preparationDigest)) throw new Error("apply digest is invalid");
    if (!OID.test(input.reviewedBaseline) || !OID.test(input.reviewedCommit) || !OID.test(input.expectedTargetHead) || !REF.test(input.targetRef) || input.targetRef.includes("..") || input.applyMode !== "exact-reviewed-commit") throw new Error("unsupported or unsafe apply identity");
    if (input.reviewedChangedPaths.length > M9_APPLY_LIMITS.maxFiles || new Set(input.reviewedChangedPaths.map((path) => safePath(path).toLowerCase())).size !== input.reviewedChangedPaths.length) throw new Error("reviewed path manifest is invalid");
    if (input.validations.length > M9_APPLY_LIMITS.maxValidations || input.validations.some((item) => !ID.test(item.validationId) || !item.executable || item.executable.includes("\0") || item.args.some((arg) => arg.includes("\0") || arg.length > 16_384) || ![".", ...input.reviewedChangedPaths.map((path) => path.split("/")[0]!)].includes(item.cwd) || item.timeoutMs < 1 || item.timeoutMs > M9_APPLY_LIMITS.maxValidationMs)) throw new Error("validation plan is invalid");
  }

  private async observations(repository: string, projectId: string, operationId: string): Promise<readonly M9WorktreeObservation[]> {
    const raw = (await this.git(repository, projectId, operationId, ["worktree", "list", "--porcelain"])).stdout; const records = raw.split(/\r?\n\r?\n/u).filter(Boolean); const output: M9WorktreeObservation[] = [];
    for (const record of records) { const lines = record.split(/\r?\n/u); const path = lines.find((line) => line.startsWith("worktree "))?.slice(9); if (!path) throw new Error("malformed worktree observation"); const head = lines.find((line) => line.startsWith("HEAD "))?.slice(5) ?? null; const branchRef = lines.find((line) => line.startsWith("branch "))?.slice(7) ?? null; await rejectLinks(path); const status = (await this.git(path, projectId, operationId, ["status", "--porcelain=v2", "-z", "--untracked-files=all"])).stdout; output.push({ pathDigest: sha256(canonicalPath(path)), head, branchRef, statusDigest: sha256(status), dirty: status.length > 0 }); }
    return output.sort((left, right) => left.pathDigest.localeCompare(right.pathDigest));
  }

  private async inspectGitSafety(repository: string, commit: string, projectId: string, operationId: string): Promise<void> {
    const unsafeConfig = await this.git(repository, projectId, operationId, ["config", "--local", "--get-regexp", "^(filter\\.|core\\.(hooksPath|fsmonitor)$|diff\\..*\\.command$|merge\\..*\\.driver$)"], true); if (unsafeConfig.exitCode === 0 && unsafeConfig.stdout.trim()) throw new Error("unsafe repository-local Git configuration rejected");
    const tree = (await this.git(repository, projectId, operationId, ["ls-tree", "-r", "-z", "--full-tree", commit])).stdout; const attributes: string[] = [];
    for (const record of tree.split("\0").filter(Boolean)) { const match = /^(\d+)\s+(\w+)\s+[0-9a-f]+\t(.+)$/u.exec(record); if (!match) throw new Error("malformed repository tree"); const path = safePath(match[3]!); if (match[1] === "120000" || match[1] === "160000" || path === ".gitmodules") throw new Error("repository links and submodules are rejected"); if (path === ".gitattributes" || path.endsWith("/.gitattributes")) attributes.push(path); }
    for (const path of attributes) { const content = (await this.git(repository, projectId, operationId, ["show", `${commit}:${path}`])).stdout; if (content.split(/\r?\n/u).some((line) => /(^|\s)(-?filter|filter=)/iu.test(line.replace(/#.*/u, "").trim()))) throw new Error("repository-controlled Git filters are rejected"); }
  }

  public async prepare(input: M9PrepareRequest): Promise<M9PrepareResult> {
    this.validateRequest(input); this.emergencyGate?.(input.targetProjectId, input.applyId);
    const approved = await realpath(this.approvedRoot); const source = await realpath(input.sourceRepositoryPath); const target = await realpath(input.targetRepositoryPath); const applyRootRequested = resolve(input.applyRoot); await rejectLinks(source); await rejectLinks(target); await rejectLinks(applyRootRequested);
    if (!contained(approved, source) || !contained(approved, target) || !contained(approved, applyRootRequested) || canonicalPath(source) === canonicalPath(target) || contained(source, target) || contained(target, source) || contained(source, applyRootRequested) || contained(target, applyRootRequested) || repositoryIdentity(source) !== input.sourceRepositoryIdentity || repositoryIdentity(target) !== input.targetRepositoryIdentity) throw new Error("repository or apply-root containment failed");
    await mkdir(applyRootRequested, { recursive: true }); const applyRoot = await realpath(applyRootRequested); const operationRoot = resolve(applyRoot, input.applyId); if (!contained(applyRoot, operationRoot) || canonicalPath(operationRoot) === canonicalPath(applyRoot)) throw new Error("apply workspace escaped its managed root"); await rejectLinks(operationRoot);
    const requestDigest = sha256(canonical(input)); const existing = await this.readJournal(operationRoot);
    if (existing) { if (existing.requestDigest !== requestDigest) throw new Error("apply idempotency conflict"); if (existing.result && ["ready", "conflicted", "validation-failed", "cancelled", "apply-unknown"].includes(existing.stage)) return existing.result as M9PrepareResult; throw new Error("apply outcome is uncertain and cannot be rerun"); }
    await mkdir(operationRoot, { recursive: false }); const startedAt = new Date().toISOString(); await this.writeJournal(operationRoot, { schemaVersion: "m9.apply-journal/v1", applyId: input.applyId, requestDigest, stage: "preparing", result: null, updatedAt: startedAt });
    const controller = new AbortController(); this.controllers.set(input.applyId, controller);
    try {
      const sourceCommon = (await this.git(source, input.sourceProjectId, input.applyId, ["rev-parse", "--path-format=absolute", "--git-common-dir"])).stdout.trim(); const targetCommon = (await this.git(target, input.targetProjectId, input.applyId, ["rev-parse", "--path-format=absolute", "--git-common-dir"])).stdout.trim(); if (!sourceCommon || !targetCommon) throw new Error("repository identity is unavailable");
      const sourceHeadType = (await this.git(source, input.sourceProjectId, input.applyId, ["cat-file", "-t", input.reviewedCommit])).stdout.trim(); const sourceParent = (await this.git(source, input.sourceProjectId, input.applyId, ["rev-parse", `${input.reviewedCommit}^`])).stdout.trim(); if (sourceHeadType !== "commit" || sourceParent !== input.reviewedBaseline) throw new Error("reviewed source is not one exact commit"); await this.inspectGitSafety(source, input.reviewedCommit, input.sourceProjectId, input.applyId); await this.inspectGitSafety(target, input.expectedTargetHead, input.targetProjectId, input.applyId);
      const sourcePaths = (await this.git(source, input.sourceProjectId, input.applyId, ["diff-tree", "--no-commit-id", "--name-only", "-r", "-z", input.reviewedCommit])).stdout.split("\0").filter(Boolean).map(safePath).sort(); const reviewedPaths = [...input.reviewedChangedPaths].map(safePath).sort(); if (canonical(sourcePaths) !== canonical(reviewedPaths)) throw new Error("source commit paths no longer match reviewed evidence");
      const before = await this.observations(target, input.targetProjectId, input.applyId); if (before.some((item) => item.branchRef === input.targetRef)) throw new Error("target branch is checked out in an owner worktree"); const oldHead = (await this.git(target, input.targetProjectId, input.applyId, ["rev-parse", "--verify", input.targetRef])).stdout.trim(); if (oldHead !== input.expectedTargetHead) throw new Error("target head is stale");
      this.emergencyGate?.(input.targetProjectId, input.applyId); await this.git(target, input.targetProjectId, input.applyId, ["fetch", "--no-tags", "--no-recurse-submodules", "--no-write-fetch-head", "--", source, input.reviewedCommit]);
      const workspace = resolve(operationRoot, "worktree"); await this.git(target, input.targetProjectId, input.applyId, ["worktree", "add", "--detach", "--", workspace, oldHead]); await rejectLinks(workspace); await this.writeJournal(operationRoot, { schemaVersion: "m9.apply-journal/v1", applyId: input.applyId, requestDigest, stage: "applying", result: null, updatedAt: new Date().toISOString() });
      this.emergencyGate?.(input.targetProjectId, input.applyId); const cherryPick = await this.git(workspace, input.targetProjectId, input.applyId, ["-c", "commit.gpgSign=false", "-c", "user.name=CHUBZ Apply", "-c", "user.email=apply@localhost.invalid", "cherry-pick", "--no-edit", input.reviewedCommit], true);
      if (cherryPick.exitCode !== 0) { const conflicts = (await this.git(workspace, input.targetProjectId, input.applyId, ["diff", "--name-only", "--diff-filter=U", "-z"], true)).stdout.split("\0").filter(Boolean).map(safePath).sort(); await this.git(workspace, input.targetProjectId, input.applyId, ["cherry-pick", "--abort"], true); const after = await this.observations(target, input.targetProjectId, input.applyId); const finishedAt = new Date().toISOString(); const result: M9PrepareResult = { applyId: input.applyId, status: "conflicted", packageDigest: input.packageDigest, preparationDigest: input.preparationDigest, targetRepositoryIdentity: input.targetRepositoryIdentity, oldHead, preparedHead: null, targetRef: input.targetRef, applyWorktree: workspace, worktreesBefore: before, worktreesAfter: after, changedPaths: [], diffStatistics: { files: 0, additions: 0, deletions: 0, binaryFiles: 0 }, conflicts, validations: [], validationEvidenceDigest: sha256("[]"), applyWorktreeDigest: null, previewDigest: sha256(canonical({ oldHead, conflicts, packageDigest: input.packageDigest })), rollback: { originalHead: oldHead, promotedHead: null, revertCandidateAvailable: false, automaticRollback: false, limitations: ["conflict requires a new reviewed attempt or separate owner-authorized resolution"] }, startedAt, finishedAt }; await this.writeJournal(operationRoot, { schemaVersion: "m9.apply-journal/v1", applyId: input.applyId, requestDigest, stage: "conflicted", result, updatedAt: finishedAt }); return result; }
      const preparedHead = (await this.git(workspace, input.targetProjectId, input.applyId, ["rev-parse", "HEAD"])).stdout.trim(); const changedPaths = (await this.git(workspace, input.targetProjectId, input.applyId, ["diff", "--name-only", "-z", oldHead, preparedHead, "--"])).stdout.split("\0").filter(Boolean).map(safePath).sort(); if (canonical(changedPaths) !== canonical(reviewedPaths)) throw new Error("applied change exceeds reviewed paths");
      const numstat = (await this.git(workspace, input.targetProjectId, input.applyId, ["diff", "--numstat", oldHead, preparedHead, "--"])).stdout; let additions = 0; let deletions = 0; let binaryFiles = 0; for (const line of numstat.split(/\r?\n/u).filter(Boolean)) { const match = /^(\d+|-)\t(\d+|-)\t/u.exec(line); if (!match) throw new Error("malformed applied diff statistics"); if (match[1] === "-" || match[2] === "-") binaryFiles += 1; else { additions += Number(match[1]); deletions += Number(match[2]); } }
      await this.writeJournal(operationRoot, { schemaVersion: "m9.apply-journal/v1", applyId: input.applyId, requestDigest, stage: "validating", result: null, updatedAt: new Date().toISOString() }); const validations: M9ValidationResult[] = [];
      for (const validation of input.validations) { this.emergencyGate?.(input.targetProjectId, input.applyId); const cwd = resolve(workspace, validation.cwd); if (!contained(workspace, cwd)) throw new Error("validation working directory escaped apply workspace"); await rejectLinks(cwd); const validationStarted = new Date().toISOString(); const process = await this.supervisor.run({ executable: validation.executable, args: validation.args, cwd, env: gitEnvironment(), taskContent: "", role: "validator", timeoutMs: validation.timeoutMs, terminationDeadlineMs: 10_000, maxOutputBytes: M9_APPLY_LIMITS.maxOutputBytes, emergencyScope: { projectId: input.targetProjectId, operationId: input.applyId }, signal: controller.signal }); const outcome = process.state === "execution-unknown" ? "unknown" : process.stopReason === "timeout" ? "timeout" : process.stopReason === "cancel" ? "cancelled" : process.exit?.code === 0 ? "passed" : "failed"; validations.push({ validationId: validation.validationId, kind: validation.kind, executable: validation.executable, args: validation.args, commandDigest: sha256(canonical([validation.executable, ...validation.args])), cwd: validation.cwd, timeoutMs: validation.timeoutMs, startedAt: validationStarted, finishedAt: new Date().toISOString(), outcome, exitCode: process.exit?.code ?? null, stdout: sanitize(process.stdout), stderr: sanitize(process.stderr), stdoutTruncated: process.stdoutTruncated, stderrTruncated: process.stderrTruncated, parsedCounts: parseCounts(`${process.stdout}\n${process.stderr}`), processTree: process.terminationEvidence }); if (outcome !== "passed") break; }
      const status = (await this.git(workspace, input.targetProjectId, input.applyId, ["status", "--porcelain=v2", "-z", "--untracked-files=all"])).stdout; const finalHead = (await this.git(workspace, input.targetProjectId, input.applyId, ["rev-parse", "HEAD"])).stdout.trim(); if (status || finalHead !== preparedHead) throw new Error("validation caused an unexpected mutation"); const after = await this.observations(target, input.targetProjectId, input.applyId); const ownerBefore = before.filter((item) => item.pathDigest !== sha256(canonicalPath(workspace))); const ownerAfter = after.filter((item) => item.pathDigest !== sha256(canonicalPath(workspace))); if (canonical(ownerBefore) !== canonical(ownerAfter)) throw new Error("owner worktree state changed during preparation");
      const validationEvidenceDigest = sha256(canonical(validations)); const applyWorktreeDigest = sha256(canonical({ preparedHead, status: sha256(status), changedPaths, validationEvidenceDigest })); const ready = validations.every((item) => item.outcome === "passed"); const finishedAt = new Date().toISOString(); const result: M9PrepareResult = { applyId: input.applyId, status: ready ? "ready" : validations.some((item) => item.outcome === "cancelled") ? "cancelled" : validations.some((item) => item.outcome === "unknown") ? "apply-unknown" : "validation-failed", packageDigest: input.packageDigest, preparationDigest: input.preparationDigest, targetRepositoryIdentity: input.targetRepositoryIdentity, oldHead, preparedHead, targetRef: input.targetRef, applyWorktree: workspace, worktreesBefore: before, worktreesAfter: after, changedPaths, diffStatistics: { files: changedPaths.length, additions, deletions, binaryFiles }, conflicts: [], validations, validationEvidenceDigest, applyWorktreeDigest, previewDigest: sha256(canonical({ input: input.preparationDigest, oldHead, preparedHead, changedPaths, validationEvidenceDigest })), rollback: { originalHead: oldHead, promotedHead: null, revertCandidateAvailable: ready, automaticRollback: false, limitations: ["rollback requires a new reviewed owner-authorized revert operation", "history rewrite and reset are forbidden"] }, startedAt, finishedAt }; await this.writeJournal(operationRoot, { schemaVersion: "m9.apply-journal/v1", applyId: input.applyId, requestDigest, stage: result.status, result, updatedAt: finishedAt }); return result;
    } catch (error) { const at = new Date().toISOString(); await this.writeJournal(operationRoot, { schemaVersion: "m9.apply-journal/v1", applyId: input.applyId, requestDigest, stage: "apply-unknown", result: null, updatedAt: at }); throw error; }
    finally { this.controllers.delete(input.applyId); }
  }

  public cancel(applyId: string): boolean { safeId(applyId, "applyId"); const controller = this.controllers.get(applyId); if (!controller) return false; controller.abort(); return true; }

  public async promote(input: M9PromoteRequest): Promise<M9PromotionResult> {
    for (const [label, value] of Object.entries({ applyId: input.applyId, ownerId: input.ownerId, targetProjectId: input.targetProjectId })) safeId(value, label); if (!REF.test(input.targetRef) || !OID.test(input.expectedOldHead) || !OID.test(input.preparedHead) || !HASH.test(input.targetRepositoryIdentity) || !HASH.test(input.applyWorktreeDigest) || !HASH.test(input.packageDigest) || !HASH.test(input.validationEvidenceDigest) || !HASH.test(input.confirmationDigest)) throw new Error("promotion binding is invalid");
    this.emergencyGate?.(input.targetProjectId, input.applyId); const target = await realpath(input.targetRepositoryPath); const workspace = await realpath(input.applyWorktree); if (!contained(await realpath(this.approvedRoot), target) || !contained(await realpath(this.approvedRoot), workspace) || repositoryIdentity(target) !== input.targetRepositoryIdentity) throw new Error("promotion repository identity failed"); await rejectLinks(target); await rejectLinks(workspace);
    const operationRoot = resolve(workspace, ".."); const journal = await this.readJournal(operationRoot); if (!journal || journal.applyId !== input.applyId || journal.stage !== "ready" || !journal.result) { if (journal?.stage === "promoted" && journal.result) { const prior = journal.result as M9PromotionResult; if (prior.oldHead !== input.expectedOldHead || prior.newHead !== input.preparedHead || prior.targetRef !== input.targetRef) throw new Error("promotion idempotency conflict"); return prior; } throw new Error("prepared operation is not promotion-ready"); }
    const preparation = journal.result as M9PrepareResult; if (preparation.preparedHead !== input.preparedHead || preparation.oldHead !== input.expectedOldHead || preparation.packageDigest !== input.packageDigest || preparation.targetRepositoryIdentity !== input.targetRepositoryIdentity || preparation.applyWorktreeDigest !== input.applyWorktreeDigest || preparation.validationEvidenceDigest !== input.validationEvidenceDigest || preparation.validations.some((item) => item.outcome !== "passed")) throw new Error("prepared evidence binding failed");
    const observations = await this.observations(target, input.targetProjectId, input.applyId); if (observations.some((item) => item.branchRef === input.targetRef)) throw new Error("target branch became checked out in an owner worktree"); const head = (await this.git(workspace, input.targetProjectId, input.applyId, ["rev-parse", "HEAD"])).stdout.trim(); const status = (await this.git(workspace, input.targetProjectId, input.applyId, ["status", "--porcelain=v2", "-z", "--untracked-files=all"])).stdout; const worktreeDigest = sha256(canonical({ preparedHead: head, status: sha256(status), changedPaths: preparation.changedPaths, validationEvidenceDigest: preparation.validationEvidenceDigest })); if (head !== input.preparedHead || status || worktreeDigest !== input.applyWorktreeDigest) throw new Error("prepared apply worktree integrity failed");
    const oldHead = (await this.git(target, input.targetProjectId, input.applyId, ["rev-parse", "--verify", input.targetRef])).stdout.trim(); if (oldHead !== input.expectedOldHead) { const result: M9PromotionResult = { applyId: input.applyId, status: "stale", oldHead, newHead: input.preparedHead, targetRef: input.targetRef, promotedAt: null, rollback: { originalHead: input.expectedOldHead, promotedHead: input.preparedHead, revertCandidateAvailable: true, automaticRollback: false, limitations: ["target moved; prepare a new operation"] } }; await this.writeJournal(operationRoot, { ...journal, stage: "stale", result, updatedAt: new Date().toISOString() }); return result; }
    const ancestry = await this.git(target, input.targetProjectId, input.applyId, ["merge-base", "--is-ancestor", input.expectedOldHead, input.preparedHead], true); if (ancestry.exitCode !== 0) throw new Error("prepared commit is not a fast-forward descendant of the expected target head");
    await this.writeJournal(operationRoot, { ...journal, stage: "promoting", result: null, updatedAt: new Date().toISOString() }); this.emergencyGate?.(input.targetProjectId, input.applyId); const update = await this.git(target, input.targetProjectId, input.applyId, ["update-ref", input.targetRef, input.preparedHead, input.expectedOldHead], true); const at = new Date().toISOString(); if (update.exitCode !== 0) { const current = (await this.git(target, input.targetProjectId, input.applyId, ["rev-parse", "--verify", input.targetRef])).stdout.trim(); const status = current === input.preparedHead ? "promoted" : current === input.expectedOldHead ? "promotion-unknown" : "stale"; const result: M9PromotionResult = { applyId: input.applyId, status, oldHead: input.expectedOldHead, newHead: input.preparedHead, targetRef: input.targetRef, promotedAt: status === "promoted" ? at : null, rollback: { originalHead: input.expectedOldHead, promotedHead: input.preparedHead, revertCandidateAvailable: true, automaticRollback: false, limitations: ["rollback requires a new reviewed owner-authorized revert operation"] } }; await this.writeJournal(operationRoot, { ...journal, stage: status, result, updatedAt: at }); return result; }
    const result: M9PromotionResult = { applyId: input.applyId, status: "promoted", oldHead: input.expectedOldHead, newHead: input.preparedHead, targetRef: input.targetRef, promotedAt: at, rollback: { originalHead: input.expectedOldHead, promotedHead: input.preparedHead, revertCandidateAvailable: true, automaticRollback: false, limitations: ["rollback requires a new reviewed owner-authorized revert operation", "no automatic push was performed"] } }; await this.writeJournal(operationRoot, { ...journal, stage: "promoted", result, updatedAt: at }); return result;
  }

  public async reconcile(operationRoot: string, targetRepositoryPath: string, targetRef: string): Promise<Readonly<{ applyId: string; outcome: string; automaticRetry: false }>> { const journal = await this.readJournal(operationRoot); if (!journal) throw new Error("apply journal was not found"); if (journal.stage === "promoting") { const result = journal.result as M9PromotionResult | null; const expected = result?.newHead; const actual = REF.test(targetRef) ? (await this.git(targetRepositoryPath, "reconciliation", journal.applyId, ["rev-parse", "--verify", targetRef], true)).stdout.trim() : ""; return { applyId: journal.applyId, outcome: expected && actual === expected ? "promoted" : "promotion-unknown", automaticRetry: false }; } if (["preparing", "applying", "validating"].includes(journal.stage)) return { applyId: journal.applyId, outcome: journal.stage === "preparing" ? "not-started-or-unknown" : journal.stage === "validating" ? "validation-unknown" : "apply-unknown", automaticRetry: false }; return { applyId: journal.applyId, outcome: journal.stage, automaticRetry: false }; }

  public async cleanupPreparedWorkspace(input: Readonly<{ applyId: string; targetProjectId: string; targetRepositoryPath: string; applyWorktree: string }>): Promise<void> { safeId(input.applyId, "applyId"); const target = await realpath(input.targetRepositoryPath); const workspace = await realpath(input.applyWorktree); const approved = await realpath(this.approvedRoot); const operationRoot = resolve(workspace, ".."); if (!contained(approved, workspace) || canonicalPath(workspace) === canonicalPath(approved) || basename(workspace) !== "worktree" || basename(operationRoot) !== input.applyId) throw new Error("unsafe apply cleanup target"); await rejectLinks(operationRoot); await rejectLinks(workspace); await this.git(target, input.targetProjectId, input.applyId, ["worktree", "remove", "--force", "--", workspace]); await rm(operationRoot, { recursive: true, force: true }); }
}
