import { createHash } from "node:crypto";
import {
  M10_ROUTING_VERSION,
  classifyM10Quota,
  classifyM10Risk,
  digestM10Recommendation,
  digestM10RoutingInput,
  evaluateM10Candidate,
  parseAdapterReadiness,
  rankM10Candidates,
  type M10CandidateEvaluation,
  type M10QuotaObservation,
} from "@chubz/shared";
import type { Principal } from "./auth.js";
import type { ControlPlaneDatabase } from "./database.js";
import { M6Error } from "./m6-ui.js";
import type { M8OperationsService } from "./m8-operations.js";

const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u;
const IDEMPOTENCY = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/u;
const sha256 = (value: string): `sha256:${string}` => `sha256:${createHash("sha256").update(value, "utf8").digest("hex")}`;
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const parseJson = <T>(value: string | null | undefined): T | null => { try { return value === null || value === undefined ? null : JSON.parse(value) as T; } catch { return null; } };
const requireId = (value: unknown, label: string): string => { if (typeof value !== "string" || !ID.test(value) || value.includes("..")) throw new M6Error("INVALID_REQUEST", `${label} is invalid`); return value; };
const requireKey = (value: unknown): string => { if (typeof value !== "string" || !IDEMPOTENCY.test(value)) throw new M6Error("INVALID_REQUEST", "idempotency key is invalid"); return value; };
const requireVersion = (value: unknown): number => { if (!Number.isSafeInteger(value) || Number(value) < 0) throw new M6Error("INVALID_REQUEST", "expected version is invalid"); return Number(value); };
const now = (): string => new Date().toISOString();

type TaskRow = { task_id: string; project_id: string; state: string; attempt_id: string | null; current_operation_id: string | null; version: number; blocked_context_json: string | null };
type AttemptRow = { attempt_id: string; action_json: string; action_digest: string };
type AssignmentRow = { worker_id: string; status: string; assignment_json: string };
type Policy = { preferLowerCost: boolean; requireStrongSandboxForHighRisk: boolean; allowManualRelay: boolean; maximumQuotaAgeSeconds: number; preferredWorkers: string[]; allowLowRiskConfirmation: boolean };
const DEFAULT_POLICY: Policy = Object.freeze({ preferLowerCost: true, requireStrongSandboxForHighRisk: true, allowManualRelay: true, maximumQuotaAgeSeconds: 900, preferredWorkers: ["codex-cli", "manual-relay"], allowLowRiskConfirmation: true });
class StaleRoutingError extends Error { public constructor(public readonly recommendationId: string, public readonly taskId: string, public readonly reason: string) { super(reason); } }

export class M10RoutingService {
  private publisher?: (taskId: string, eventKind: string) => void;
  public constructor(private readonly database: ControlPlaneDatabase, private readonly operations: M8OperationsService) {
    this.ensureUnknownObservation("codex-cli", "codex-cli-adapter");
    this.ensureUnknownObservation("manual-relay", "manual-relay");
    this.reconcileAfterRestart();
  }
  public setPublisher(publisher: (taskId: string, eventKind: string) => void): void { this.publisher = publisher; }
  private emit(taskId: string, kind: string): void {
    this.publisher?.(taskId, kind);
    const task = this.database.connection.prepare("SELECT project_id,attempt_id,current_operation_id FROM tasks WHERE task_id=?").get(taskId) as { project_id: string; attempt_id: string | null; current_operation_id: string | null } | undefined;
    const owner = this.database.connection.prepare("SELECT id FROM administrators ORDER BY created_at LIMIT 1").get() as { id: string } | undefined;
    if (task) {
      const count = (this.database.connection.prepare("SELECT COUNT(*) AS n FROM m8_operational_events WHERE source='m10_routing'").get() as { n: number }).n;
      this.operations.record({ eventId: `m10-event-${sha256(`${kind}\n${taskId}\n${count}`).slice(7, 55)}`, eventKind: kind, ownerId: owner?.id ?? null, projectId: task.project_id, taskId, attemptId: task.attempt_id, operationId: task.current_operation_id, source: "m10_routing", actorCategory: kind.includes("owner-") || kind.includes("confirmed") ? "owner" : "control-plane", summary: `M10 ${kind.replaceAll(".", " ")} recorded; this event does not authorize execution.`, details: { authority: "control-plane", automaticDispatch: false, sensitivePromptIncluded: false }, occurredAt: now() });
      this.operations.project();
    }
  }
  private assertOwner(principal: Principal): void {
    const row = this.database.connection.prepare("SELECT 1 FROM administrators WHERE id=? AND disabled_at IS NULL").get(principal.administratorId);
    if (!row) throw new M6Error("NOT_FOUND", "owner routing scope was not found");
  }
  private task(taskId: string): TaskRow {
    const row = this.database.connection.prepare("SELECT task_id,project_id,state,attempt_id,current_operation_id,version,blocked_context_json FROM tasks WHERE task_id=?").get(taskId) as TaskRow | undefined;
    if (!row) throw new M6Error("NOT_FOUND", "task was not found");
    return row;
  }
  private policy(ownerId: string, projectId: string): Readonly<{ value: Policy; version: number; digest: string }> {
    const row = this.database.connection.prepare("SELECT policy_json,version,policy_digest FROM m10_routing_policies WHERE owner_id=? AND project_id=?").get(ownerId, projectId) as { policy_json: string; version: number; policy_digest: string } | undefined;
    return row ? { value: parseJson<Policy>(row.policy_json) ?? DEFAULT_POLICY, version: row.version, digest: row.policy_digest } : { value: DEFAULT_POLICY, version: 0, digest: sha256(canonical(DEFAULT_POLICY)) };
  }
  private emergency(projectId: string): Readonly<{ active: boolean; digest: string }> {
    const rows = this.database.connection.prepare("SELECT stop_id,scope_type,project_id,version FROM m8_emergency_stops WHERE status='active' AND (scope_type='global' OR project_id=?) ORDER BY stop_id").all(projectId) as Array<Record<string, unknown>>;
    return Object.freeze({ active: rows.length > 0, digest: sha256(canonical(rows)) });
  }
  private mutation<T>(scope: string, key: string, request: unknown, execute: () => T): T {
    const requestDigest = sha256(canonical(request)); const db = this.database.connection;
    try {
      return db.transaction(() => {
        const existing = db.prepare("SELECT request_digest,result_json FROM m10_mutations WHERE mutation_scope=? AND idempotency_key=?").get(scope, key) as { request_digest: string; result_json: string | null } | undefined;
        if (existing) { if (existing.request_digest !== requestDigest) throw new M6Error("CONFLICT", "idempotency key conflicts with a prior routing mutation"); if (existing.result_json === null) throw new M6Error("CONFLICT", "the routing mutation is in progress"); return JSON.parse(existing.result_json) as T; }
        db.prepare("INSERT INTO m10_mutations(mutation_scope,idempotency_key,request_digest,result_json,recorded_at) VALUES(?,?,?,?,?)").run(scope, key, requestDigest, null, now());
        const result = execute(); db.prepare("UPDATE m10_mutations SET result_json=? WHERE mutation_scope=? AND idempotency_key=?").run(JSON.stringify(result), scope, key); return result;
      })();
    } catch (error) {
      if (error instanceof StaleRoutingError) { this.markStale(error.recommendationId, error.taskId, error.reason); throw new M6Error("STALE_STATE", error.reason); }
      throw error;
    }
  }
  private ensureUnknownObservation(workerId: string, adapterId: string): void {
    const present = this.database.connection.prepare("SELECT 1 FROM m10_quota_observations WHERE worker_id=? AND adapter_id=? LIMIT 1").get(workerId, adapterId);
    if (present) return;
    const observedAt = now(); const observation: M10QuotaObservation = { observationId: `quota-unknown-${workerId}`, workerId, adapterId, state: "unknown", confidence: "unknown", source: "unknown", observedAt, expiresAt: new Date(Date.parse(observedAt) + 15 * 60_000).toISOString(), resetAt: null, remaining: null, limitation: "The accepted adapter exposes no safe authoritative quota probe." };
    this.insertQuota(observation);
  }
  private insertQuota(observation: M10QuotaObservation): void {
    const digest = sha256(canonical(observation));
    const existing = this.database.connection.prepare("SELECT observation_digest FROM m10_quota_observations WHERE observation_id=?").get(observation.observationId) as { observation_digest: string } | undefined;
    if (existing) { if (existing.observation_digest !== digest) throw new M6Error("CONFLICT", "quota observation identity conflicts with prior evidence"); return; }
    this.database.connection.prepare("INSERT INTO m10_quota_observations(observation_id,worker_id,adapter_id,state,confidence,source,observed_at,expires_at,reset_at,remaining,limitation,observation_json,observation_digest) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(observation.observationId, observation.workerId, observation.adapterId, observation.state, observation.confidence, observation.source, observation.observedAt, observation.expiresAt, observation.resetAt, observation.remaining, observation.limitation, canonical(observation), digest);
  }
  public recordQuotaObservationSystem(raw: M10QuotaObservation): void {
    if (!ID.test(raw.observationId) || !ID.test(raw.workerId) || !ID.test(raw.adapterId) || !["available", "constrained", "exhausted", "unknown", "unavailable"].includes(raw.state) || !["high", "medium", "low", "unknown"].includes(raw.confidence) || !Number.isFinite(Date.parse(raw.observedAt))) throw new M6Error("INVALID_REQUEST", "quota observation is invalid");
    if (raw.source === "owner-attested" && raw.confidence === "high") throw new M6Error("INVALID_REQUEST", "owner-attested quota cannot claim high confidence");
    this.insertQuota(raw);
    this.operations.record({ eventId: `m10-quota-${sha256(raw.observationId).slice(7, 55)}`, eventKind: "routing.quota-state-changed", source: "m10_routing", actorCategory: raw.source === "owner-attested" ? "owner" : "control-plane", summary: `Quota state observation recorded for ${raw.workerId}; unknown remains unknown and cost authority is unchanged.`, details: { workerId: raw.workerId, adapterId: raw.adapterId, state: raw.state, confidence: raw.confidence, source: raw.source, rawProviderResponseIncluded: false }, occurredAt: raw.observedAt }); this.operations.project();
  }
  public recordHealthObservationSystem(raw: Readonly<{ observationId: string; workerId: string; adapterId: string; outcome: string; source: string; observedAt: string; expiresAt: string; evidence: Record<string, unknown> }>): void {
    if (!ID.test(raw.observationId) || !ID.test(raw.workerId) || !ID.test(raw.adapterId) || !["readiness-probe", "adapter-outcome", "system-reconciliation", "provider-response"].includes(raw.source) || raw.outcome.length > 128 || !Number.isFinite(Date.parse(raw.observedAt)) || !Number.isFinite(Date.parse(raw.expiresAt))) throw new M6Error("INVALID_REQUEST", "health observation is invalid");
    const digest = sha256(canonical(raw));
    const existing = this.database.connection.prepare("SELECT observation_digest FROM m10_health_observations WHERE observation_id=?").get(raw.observationId) as { observation_digest: string } | undefined; if (existing) { if (existing.observation_digest !== digest) throw new M6Error("CONFLICT", "health observation identity conflicts with prior evidence"); return; }
    this.database.connection.prepare("INSERT INTO m10_health_observations(observation_id,worker_id,adapter_id,outcome,source,observed_at,expires_at,evidence_json,observation_digest) VALUES(?,?,?,?,?,?,?,?,?)").run(raw.observationId, raw.workerId, raw.adapterId, raw.outcome, raw.source, raw.observedAt, raw.expiresAt, canonical(raw.evidence), digest);
    this.database.connection.prepare("DELETE FROM m10_health_observations WHERE observation_id IN (SELECT observation_id FROM m10_health_observations WHERE worker_id=? AND adapter_id=? ORDER BY observed_at DESC LIMIT -1 OFFSET 64)").run(raw.workerId, raw.adapterId);
  }
  private latestQuota(workerId: string, adapterId: string): M10QuotaObservation | null {
    const row = this.database.connection.prepare("SELECT observation_json FROM m10_quota_observations WHERE worker_id=? AND adapter_id=? ORDER BY observed_at DESC,observation_id DESC LIMIT 1").get(workerId, adapterId) as { observation_json: string } | undefined;
    return parseJson<M10QuotaObservation>(row?.observation_json) ?? null;
  }
  private quotaFor(workerId: string, adapterId: string, maximumAgeSeconds: number): ReturnType<typeof classifyM10Quota> {
    const observation = this.latestQuota(workerId, adapterId); const classified = classifyM10Quota(observation, now());
    if (observation && Date.now() - Date.parse(observation.observedAt) > maximumAgeSeconds * 1_000) return Object.freeze({ state: "stale" as const, confidence: observation.confidence, fresh: false, warning: "The quota observation exceeds the owner policy freshness limit." });
    return classified;
  }
  private reliability(workerId: string, adapterId: string): "high" | "medium" | "low" | "unknown" {
    const rows = this.database.connection.prepare("SELECT outcome,expires_at FROM m10_health_observations WHERE worker_id=? AND adapter_id=? ORDER BY observed_at DESC LIMIT 16").all(workerId, adapterId) as Array<{ outcome: string; expires_at: string }>;
    const current = rows.filter((row) => Date.parse(row.expires_at) > Date.now()); if (current.length === 0) return "unknown";
    const failures = current.filter((row) => !["ready", "completed", "healthy", "success"].includes(row.outcome)).length;
    return failures === 0 ? "high" : failures * 3 <= current.length ? "medium" : "low";
  }
  private projectInput(principal: Principal, taskId: string): Readonly<{ task: TaskRow; attempt: AttemptRow; assignment: AssignmentRow | null; input: Record<string, unknown>; inputDigest: string; risk: ReturnType<typeof classifyM10Risk>; quotaDigest: string; policy: ReturnType<M10RoutingService["policy"]> }> {
    this.assertOwner(principal); const task = this.task(taskId);
    if (task.attempt_id === null || task.current_operation_id === null) throw new M6Error("CONFLICT", "task has no active immutable attempt");
    const attempt = this.database.connection.prepare("SELECT attempt_id,action_json,action_digest FROM task_attempts WHERE attempt_id=? AND task_id=?").get(task.attempt_id, taskId) as AttemptRow | undefined;
    if (!attempt) throw new M6Error("CONFLICT", "attempt binding is unavailable");
    const assignment = this.database.connection.prepare("SELECT worker_id,status,assignment_json FROM m4_assignments WHERE task_id=? AND attempt_id=? AND operation_id=? ORDER BY created_at DESC LIMIT 1").get(taskId, task.attempt_id, task.current_operation_id) as AssignmentRow | undefined;
    const action = parseJson<Record<string, unknown>>(attempt.action_json) ?? {};
    const scopeRow = this.database.connection.prepare("SELECT scope_id,scope_hash,scope_json FROM m4_write_scopes WHERE task_id=? AND attempt_id=? AND operation_id=?").get(taskId, task.attempt_id, task.current_operation_id) as { scope_id: string; scope_hash: string; scope_json: string } | undefined;
    const scope = parseJson<Record<string, unknown>>(scopeRow?.scope_json) ?? null; const permissions = scope?.["permissions"] as Record<string, unknown> | undefined;
    const operation = String(action["operation"] ?? "unknown"); const policyClass = String(action["policyClass"] ?? "unknown");
    const actionTarget = (action["target"] as Record<string, unknown> | undefined)?.["resourceId"];
    const structuralText = `${operation} ${policyClass}`.toLowerCase();
    const risk = classifyM10Risk({ action: operation, readOnly: permissions ? !permissions["create"] && !permissions["modify"] && !permissions["delete"] : actionTarget === "manual-relay", repositoryMutation: Boolean(permissions?.["create"] || permissions?.["modify"] || permissions?.["delete"]), applyOrPromotion: /apply|promotion/u.test(structuralText), credentials: /credential/u.test(structuralText), productionOrDeployment: /production|deploy/u.test(structuralText), databaseAdministration: /database-admin/u.test(structuralText), externalSystems: /router|dns|billing|external-system/u.test(structuralText), destructiveGit: /reset-hard|destructive-git/u.test(structuralText), historyRewrite: /history-rewrite|force-push/u.test(structuralText), serviceRestart: /service-restart/u.test(structuralText), remoteAccess: /remote-access/u.test(structuralText), irreversible: /irreversible/u.test(structuralText), unknownScope: scope === null && actionTarget !== "manual-relay", insufficientEvidence: operation === "unknown" });
    const policy = this.policy(principal.administratorId, task.project_id); const emergency = this.emergency(task.project_id);
    const readinessRows = this.database.connection.prepare("SELECT readiness_id,worker_id,adapter_id,readiness_json,evidence_json,recorded_at FROM m5_adapter_readiness WHERE (worker_id,adapter_id,recorded_at) IN (SELECT worker_id,adapter_id,MAX(recorded_at) FROM m5_adapter_readiness GROUP BY worker_id,adapter_id) ORDER BY worker_id,adapter_id").all() as Array<Record<string, unknown>>;
    const quotaRefs = [["codex-cli", "codex-cli-adapter"], ["manual-relay", "manual-relay"]].map(([worker, adapter]) => this.latestQuota(worker!, adapter!));
    const quotaDigest = sha256(canonical(quotaRefs));
    const input = { routingVersion: M10_ROUTING_VERSION, ownerId: principal.administratorId, projectId: task.project_id, taskId, attemptId: task.attempt_id, operationId: task.current_operation_id, taskVersion: task.version, taskState: task.state, actionDigest: attempt.action_digest, requestedAction: operation, assignment: assignment ? { workerId: assignment.worker_id, status: assignment.status, digest: sha256(assignment.assignment_json) } : null, repository: scopeRow ? { scopeId: scopeRow.scope_id, scopeHash: scopeRow.scope_hash, permissions: permissions ?? null } : null, risk, policy: { version: policy.version, digest: policy.digest }, emergency, readiness: readinessRows.map((row) => ({ readinessId: row["readiness_id"], workerId: row["worker_id"], adapterId: row["adapter_id"], digest: sha256(String(row["readiness_json"])), recordedAt: row["recorded_at"] })), quotaDigest, boundedMetadata: { instructionsIncluded: false, fullPromptLogged: false } };
    return { task, attempt, assignment: assignment ?? null, input, inputDigest: digestM10RoutingInput(input), risk, quotaDigest, policy };
  }
  public inputs(principal: Principal, taskIdRaw: unknown): Record<string, unknown> { const taskId = requireId(taskIdRaw, "taskId"); const value = this.projectInput(principal, taskId); return { ...value.input, inputDigest: value.inputDigest }; }
  private candidates(projected: ReturnType<M10RoutingService["projectInput"]>): readonly M10CandidateEvaluation[] {
    const assigned = parseJson<Record<string, unknown>>(projected.assignment?.assignment_json); const target = ((parseJson<Record<string, unknown>>(projected.attempt.action_json)?.["target"] as Record<string, unknown> | undefined)?.["resourceId"] as string | undefined) ?? projected.assignment?.worker_id ?? "unknown"; const baseRequired = Array.isArray(assigned?.["requiredCapabilities"]) ? assigned!["requiredCapabilities"] as string[] : target === "manual-relay" ? ["text-output"] : ["review"];
    const readinessRow = this.database.connection.prepare("SELECT readiness_json,evidence_json FROM m5_adapter_readiness WHERE worker_id='codex-cli' AND adapter_id='codex-cli-adapter' ORDER BY recorded_at DESC LIMIT 1").get() as { readiness_json: string; evidence_json: string } | undefined;
    const parsed = readinessRow ? parseAdapterReadiness(parseJson(readinessRow.readiness_json)) : null; const readiness = parsed?.ok === true ? parsed.value : null; const evidence = parseJson<Record<string, unknown>>(readinessRow?.evidence_json); const sandbox = String((evidence?.["windowsSandbox"] as Record<string, unknown> | undefined)?.["assurance"] ?? "unknown");
    const readinessFresh = readiness?.capabilityProbeAt !== null && readiness?.capabilityProbeAt !== undefined && Date.now() - Date.parse(readiness.capabilityProbeAt) <= 15 * 60_000;
    const requiresStrongSandbox = projected.risk.riskClass === "high" && projected.policy.value.requireStrongSandboxForHighRisk; const required = [...baseRequired, ...(requiresStrongSandbox ? ["strong-sandbox"] : [])];
    const available: Record<string, "satisfied" | "unavailable" | "unknown"> = { "code-write": readiness ? "satisfied" : "unknown", review: readiness ? "satisfied" : "unknown", "text-output": readiness?.structuredOutputCapability && ["probed", "observed", "validated"].includes(readiness.structuredOutputCapability) ? "satisfied" : "unknown", "structured-output": readiness?.structuredOutputCapability && ["probed", "observed", "validated"].includes(readiness.structuredOutputCapability) ? "satisfied" : "unknown", cancellation: readiness?.cancellationCapability && ["probed", "observed", "validated"].includes(readiness.cancellationCapability) ? "satisfied" : "unknown", resume: readiness?.resumeCapability && ["probed", "observed", "validated"].includes(readiness.resumeCapability) ? "satisfied" : "unknown", "strong-sandbox": sandbox !== "unknown" && sandbox !== "degraded-bounded-local" ? "satisfied" : sandbox === "degraded-bounded-local" ? "unavailable" : "unknown" };
    const worker = this.database.connection.prepare("SELECT state FROM m5_worker_states WHERE worker_id='codex-cli'").get() as { state: string } | undefined;
    const codexQuota = this.quotaFor("codex-cli", "codex-cli-adapter", projected.policy.value.maximumQuotaAgeSeconds);
    const codex = evaluateM10Candidate({ workerId: "codex-cli", adapterId: "codex-cli-adapter", connectorTier: "cli", mandatoryCapabilities: required, availableCapabilities: available, readiness: !readinessFresh ? "unknown" : readiness?.readinessState === "ready" ? "ready" : readiness?.readinessState === "degraded" ? "degraded" : readiness ? "blocked" : "unknown", authentication: readiness?.authenticationState ?? "unknown", sandboxAssurance: sandbox, workerEnabled: worker?.state === "enabled", targetMatchesAttempt: target === "codex-cli", quota: codexQuota, costClass: "estimated-low", reliability: this.reliability("codex-cli", "codex-cli-adapter"), ownerPreference: Math.max(0, 20 - projected.policy.value.preferredWorkers.indexOf("codex-cli") * 5), manualRelayAllowed: projected.policy.value.allowManualRelay, preferLowerCost: projected.policy.value.preferLowerCost });
    const manualQuota = this.quotaFor("manual-relay", "manual-relay", projected.policy.value.maximumQuotaAgeSeconds);
    const manualCapabilities: Record<string, "satisfied" | "unavailable" | "unknown"> = { "text-output": "satisfied", review: "satisfied", "code-write": "unavailable", "structured-output": "unavailable", cancellation: "unavailable", resume: "unavailable", "strong-sandbox": "unavailable" };
    const manual = evaluateM10Candidate({ workerId: "manual-relay", adapterId: "manual-relay", connectorTier: "manual-relay", mandatoryCapabilities: required, availableCapabilities: manualCapabilities, readiness: "manual-only", authentication: "not-required", sandboxAssurance: "weaker-manual-owner-attested", workerEnabled: true, targetMatchesAttempt: target === "manual-relay", quota: manualQuota, costClass: "estimated-unknown", reliability: this.reliability("manual-relay", "manual-relay"), ownerPreference: Math.max(0, 20 - projected.policy.value.preferredWorkers.indexOf("manual-relay") * 5), manualRelayAllowed: projected.policy.value.allowManualRelay, preferLowerCost: projected.policy.value.preferLowerCost });
    return rankM10Candidates(projected.risk.structurallyRefused ? [codex, manual].map((entry) => ({ ...entry, eligible: false, rejectionReasons: [...entry.rejectionReasons, "structurally-refused-by-risk-policy"], score: entry.score - 1_000 })) : [codex, manual]);
  }
  public generate(principal: Principal, taskIdRaw: unknown, raw: Record<string, unknown>): Record<string, unknown> {
    const taskId = requireId(taskIdRaw, "taskId"); const key = requireKey(raw["idempotencyKey"]); const expectedVersion = requireVersion(raw["expectedVersion"]);
    return this.mutation(`routing.generate:${principal.administratorId}:${taskId}`, key, { taskId, expectedVersion }, () => {
      const projected = this.projectInput(principal, taskId); if (projected.task.version !== expectedVersion) throw new M6Error("STALE_STATE", "task version is stale");
      this.operations.assertExecutionAllowed(projected.task.project_id);
      if (!["AWAITING_DISPATCH", "BLOCKED"].includes(projected.task.state)) throw new M6Error("CONFLICT", "routing is unavailable for the current task state");
      const recent = (this.database.connection.prepare("SELECT COUNT(*) AS n FROM m10_routing_requests WHERE owner_id=? AND task_id=? AND created_at>=?").get(principal.administratorId, taskId, new Date(Date.now() - 60_000).toISOString()) as { n: number }).n; if (recent >= 10) throw new M6Error("CONFLICT", "routing refresh rate is bounded");
      const historical = (this.database.connection.prepare("SELECT COUNT(*) AS n FROM m10_routing_requests WHERE owner_id=? AND task_id=?").get(principal.administratorId, taskId) as { n: number }).n; if (historical >= 64) throw new M6Error("CONFLICT", "bounded routing history is full for this task");
      const existing = this.database.connection.prepare("SELECT recommendation_json FROM m10_recommendations WHERE routing_request_id IN (SELECT routing_request_id FROM m10_routing_requests WHERE owner_id=? AND task_id=? AND attempt_id=? AND operation_id=? AND input_digest=?)").get(principal.administratorId, taskId, projected.task.attempt_id, projected.task.current_operation_id, projected.inputDigest) as { recommendation_json: string } | undefined;
      if (existing) return JSON.parse(existing.recommendation_json) as Record<string, unknown>;
      const evaluated = this.candidates(projected); const selected = evaluated.find((entry) => entry.eligible) ?? null; const generatedAt = now(); const requestId = `routing-${sha256(`${principal.administratorId}\n${projected.inputDigest}`).slice(7, 55)}`; const recommendationId = `recommendation-${sha256(requestId).slice(7, 55)}`;
      const requestStatus = selected ? "recommended" : "no-eligible-route";
      const fallbackOptions: Array<Record<string, unknown>> = evaluated
        .filter((entry) => entry.workerId !== selected?.workerId && entry.rejectionReasons.every((reason) => reason === "immutable-attempt-target-mismatch"))
        .map((entry) => ({ kind: entry.connectorTier === "manual-relay" ? "manual-relay-new-attempt" : "new-immutable-attempt", workerId: entry.workerId, adapterId: entry.adapterId, requiresOwnerConfirmation: true, reasons: ["capabilities remain compatible, but changing the route requires a new immutable attempt"] }));
      const quotaWait = evaluated.find((entry) => ["constrained", "exhausted", "unknown", "stale", "unavailable"].includes(entry.quota.state));
      if (quotaWait) fallbackOptions.push({ kind: "wait-for-quota-evidence", workerId: quotaWait.workerId, adapterId: quotaWait.adapterId, quotaState: quotaWait.quota.state, requiresOwnerConfirmation: true, reasons: ["current quota evidence does not establish unconstrained availability"] });
      fallbackOptions.push({ kind: "owner-intervention", requiresOwnerConfirmation: true, reasons: ["no fallback executes automatically; the owner may choose a new authoritative action"] });
      const recommendationCore = { recommendationId, routingRequestId: requestId, recommendationVersion: M10_ROUTING_VERSION, inputDigest: projected.inputDigest, quotaObservationDigest: projected.quotaDigest, generatedAt, riskClass: projected.risk.riskClass, riskReasons: projected.risk.reasons, policyRules: projected.risk.policyRules, selected: selected ? { workerId: selected.workerId, adapterId: selected.adapterId } : null, status: selected ? "generated" : "no-eligible-route", candidates: evaluated, rationale: selected ? ["all mandatory capability checks passed", "authoritative readiness ranked before cost", "cost is estimated and does not authorize execution", "owner confirmation remains required"] : ["no candidate satisfied every mandatory requirement"], fallbackOptions, automaticDispatch: false, automaticFallback: false };
      const recommendation = { ...recommendationCore, recommendationDigest: digestM10Recommendation(recommendationCore) };
      const db = this.database.connection; db.prepare("INSERT INTO m10_routing_requests(routing_request_id,owner_id,project_id,task_id,attempt_id,operation_id,expected_task_version,input_json,input_digest,risk_class,risk_reasons_json,policy_rules_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(requestId, principal.administratorId, projected.task.project_id, taskId, projected.task.attempt_id, projected.task.current_operation_id, expectedVersion, canonical(projected.input), projected.inputDigest, projected.risk.riskClass, canonical(projected.risk.reasons), canonical(projected.risk.policyRules), requestStatus, generatedAt, generatedAt);
      evaluated.forEach((entry, index) => { const digest = sha256(canonical(entry)); db.prepare("INSERT INTO m10_candidate_evaluations(evaluation_id,routing_request_id,worker_id,adapter_id,rank,eligible,score,evaluation_json,evaluation_digest,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(`evaluation-${digest.slice(7, 55)}`, requestId, entry.workerId, entry.adapterId, index + 1, entry.eligible ? 1 : 0, entry.score, canonical(entry), digest, generatedAt); });
      db.prepare("INSERT INTO m10_recommendations(recommendation_id,routing_request_id,owner_id,project_id,task_id,attempt_id,operation_id,recommendation_version,input_digest,quota_digest,selected_worker_id,selected_adapter_id,risk_class,recommendation_json,recommendation_digest,status,generated_at,finalized_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(recommendationId, requestId, principal.administratorId, projected.task.project_id, taskId, projected.task.attempt_id, projected.task.current_operation_id, M10_ROUTING_VERSION, projected.inputDigest, projected.quotaDigest, selected?.workerId ?? null, selected?.adapterId ?? null, projected.risk.riskClass, canonical(recommendation), recommendation.recommendationDigest, recommendationCore.status, generatedAt, generatedAt);
      const blocked = parseJson<Record<string, unknown>>(projected.task.blocked_context_json); const noFallback = blocked?.["blockedReason"] === "execution-unknown" || blocked?.["cancellationState"] === "unconfirmed";
      const options = noFallback ? [] : fallbackOptions; const fallbackStatus = options.length ? "proposed" : "unavailable"; db.prepare("INSERT INTO m10_fallback_plans(fallback_plan_id,routing_request_id,recommendation_id,owner_id,project_id,task_id,attempt_id,operation_id,reason,evidence_json,options_json,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`fallback-${sha256(recommendationId).slice(7, 55)}`, requestId, recommendationId, principal.administratorId, projected.task.project_id, taskId, projected.task.attempt_id, projected.task.current_operation_id, noFallback ? "fallback forbidden while execution or cancellation is uncertain" : "safe alternatives require a new authoritative owner decision", canonical({ taskState: projected.task.state, blockedContextDigest: sha256(canonical(blocked)) }), canonical(options), fallbackStatus, generatedAt);
      this.emit(taskId, selected ? "routing.recommendation-generated" : "routing.no-eligible-route"); if (options.length) this.emit(taskId, "routing.fallback-proposed"); return recommendation;
    });
  }
  private recommendation(principal: Principal, recommendationId: string): { row: Record<string, unknown>; value: Record<string, unknown> } {
    const row = this.database.connection.prepare("SELECT * FROM m10_recommendations WHERE recommendation_id=? AND owner_id=?").get(recommendationId, principal.administratorId) as Record<string, unknown> | undefined;
    if (!row) throw new M6Error("NOT_FOUND", "routing recommendation was not found"); return { row, value: JSON.parse(String(row["recommendation_json"])) as Record<string, unknown> };
  }
  public confirm(principal: Principal, taskIdRaw: unknown, recommendationIdRaw: unknown, raw: Record<string, unknown>): Record<string, unknown> {
    const taskId = requireId(taskIdRaw, "taskId"); const recommendationId = requireId(recommendationIdRaw, "recommendationId"); const key = requireKey(raw["idempotencyKey"]); const expectedVersion = requireVersion(raw["expectedVersion"]);
    return this.mutation(`routing.confirm:${principal.administratorId}:${recommendationId}`, key, { taskId, recommendationId, expectedVersion, inputDigest: raw["inputDigest"], recommendationVersion: raw["recommendationVersion"] }, () => {
      const found = this.recommendation(principal, recommendationId); if (found.row["task_id"] !== taskId) throw new M6Error("NOT_FOUND", "routing recommendation was not found"); this.operations.assertExecutionAllowed(String(found.row["project_id"])); if (found.row["status"] !== "generated") throw new M6Error("CONFLICT", "recommendation is not confirmable");
      const projected = this.projectInput(principal, taskId); if (projected.task.version !== expectedVersion || projected.inputDigest !== found.row["input_digest"] || raw["inputDigest"] !== found.row["input_digest"] || raw["recommendationVersion"] !== M10_ROUTING_VERSION) throw new StaleRoutingError(recommendationId, taskId, "authoritative input or task version changed");
      this.operations.assertExecutionAllowed(projected.task.project_id); const emergency = this.emergency(projected.task.project_id); const selectedWorker = String(found.row["selected_worker_id"]); const selectedAdapter = String(found.row["selected_adapter_id"]); const current = this.candidates(projected).find((entry) => entry.workerId === selectedWorker && entry.adapterId === selectedAdapter); if (!current?.eligible) throw new StaleRoutingError(recommendationId, taskId, "selected route is no longer eligible");
      if (!current.quota.fresh) throw new StaleRoutingError(recommendationId, taskId, "quota observation is stale");
      if (selectedWorker === "codex-cli" && projected.assignment?.status !== "pending-approval") throw new StaleRoutingError(recommendationId, taskId, "assignment is no longer awaiting approval");
      const projectRunning = (this.database.connection.prepare("SELECT COUNT(*) AS n FROM tasks WHERE project_id=? AND task_id<>? AND state IN ('RUNNING','CANCELLING')").get(projected.task.project_id, taskId) as { n: number }).n; const globalRunning = (this.database.connection.prepare("SELECT COUNT(*) AS n FROM tasks WHERE task_id<>? AND state IN ('RUNNING','CANCELLING')").get(taskId) as { n: number }).n; if (projectRunning >= 1 || globalRunning >= 2) throw new M6Error("CONFLICT", "current concurrency limits do not permit route confirmation");
      if (projected.risk.riskClass === "owner-only") throw new M6Error("CONFLICT", "structurally refused work cannot be confirmed");
      if (projected.risk.riskClass === "low" && !projected.policy.value.allowLowRiskConfirmation) throw new M6Error("CONFLICT", "owner policy disallows low-risk route confirmation");
      const selected = found.value["selected"] as Record<string, unknown>; if (raw["selectedWorkerId"] !== selected["workerId"] || raw["selectedAdapterId"] !== selected["adapterId"]) throw new M6Error("CONFLICT", "selected route does not match the deterministic recommendation");
      const capabilityScope = current.capabilityMatch; const at = now(); const confirmationCore = { ownerId: principal.administratorId, taskId, attemptId: found.row["attempt_id"], operationId: found.row["operation_id"], projectId: found.row["project_id"], selectedWorkerId: selectedWorker, selectedAdapterId: selectedAdapter, recommendationVersion: M10_ROUTING_VERSION, inputDigest: found.row["input_digest"], riskClass: found.row["risk_class"], capabilityScope, quotaDigest: found.row["quota_digest"], expectedTaskVersion: expectedVersion, emergencyStateDigest: emergency.digest, confirmedAt: at }; const confirmationDigest = sha256(canonical(confirmationCore)); const confirmationId = `route-confirmation-${confirmationDigest.slice(7, 55)}`;
      const db = this.database.connection; db.prepare("INSERT INTO m10_route_confirmations(confirmation_id,recommendation_id,owner_id,project_id,task_id,attempt_id,operation_id,selected_worker_id,selected_adapter_id,recommendation_version,input_digest,risk_class,capability_scope_json,quota_digest,expected_task_version,emergency_state_digest,confirmation_digest,confirmed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(confirmationId, recommendationId, principal.administratorId, found.row["project_id"], taskId, found.row["attempt_id"], found.row["operation_id"], selectedWorker, selectedAdapter, M10_ROUTING_VERSION, found.row["input_digest"], found.row["risk_class"], canonical(capabilityScope), found.row["quota_digest"], expectedVersion, emergency.digest, confirmationDigest, at);
      db.prepare("UPDATE m10_recommendations SET status='confirmed' WHERE recommendation_id=? AND status='generated'").run(recommendationId); db.prepare("UPDATE m10_routing_requests SET status='confirmed',updated_at=? WHERE routing_request_id=?").run(at, found.row["routing_request_id"]); this.emit(taskId, "routing.owner-confirmed"); return { confirmationId, recommendationId, taskId, selectedWorkerId: selectedWorker, selectedAdapterId: selectedAdapter, riskClass: found.row["risk_class"], confirmedAt: at, dispatchCreated: false, capabilityGranted: false, nextGate: "existing-owner-approval-and-capability-grant" };
    });
  }
  public reject(principal: Principal, taskIdRaw: unknown, recommendationIdRaw: unknown, raw: Record<string, unknown>): Record<string, unknown> {
    const taskId = requireId(taskIdRaw, "taskId"); const recommendationId = requireId(recommendationIdRaw, "recommendationId"); const key = requireKey(raw["idempotencyKey"]); const expectedVersion = requireVersion(raw["expectedVersion"]);
    return this.mutation(`routing.reject:${principal.administratorId}:${recommendationId}`, key, { taskId, recommendationId, expectedVersion }, () => { const found = this.recommendation(principal, recommendationId); const task = this.task(taskId); if (found.row["task_id"] !== taskId) throw new M6Error("NOT_FOUND", "recommendation was not found"); if (task.version !== expectedVersion) throw new M6Error("STALE_STATE", "task version is stale"); if (!["generated", "no-eligible-route"].includes(String(found.row["status"]))) throw new M6Error("CONFLICT", "recommendation cannot be rejected"); const at = now(); this.database.connection.prepare("UPDATE m10_recommendations SET status='rejected' WHERE recommendation_id=?").run(recommendationId); this.database.connection.prepare("UPDATE m10_routing_requests SET status='rejected',updated_at=? WHERE routing_request_id=?").run(at, found.row["routing_request_id"]); this.emit(taskId, "routing.owner-rejected"); return { recommendationId, status: "rejected", rejectedAt: at, dispatchCreated: false }; });
  }
  private markStale(recommendationId: string, taskId: string, reason: string): void { const at = now(); this.database.connection.prepare("UPDATE m10_recommendations SET status='stale' WHERE recommendation_id=? AND status IN ('generated','confirmed')").run(recommendationId); this.database.connection.prepare("UPDATE m10_routing_requests SET status='stale',updated_at=? WHERE routing_request_id=(SELECT routing_request_id FROM m10_recommendations WHERE recommendation_id=?)").run(at, recommendationId); this.database.connection.prepare("UPDATE m10_fallback_plans SET status='stale' WHERE recommendation_id=? AND status='proposed'").run(recommendationId); const row = this.database.connection.prepare("SELECT owner_id,project_id FROM m10_recommendations WHERE recommendation_id=?").get(recommendationId) as { owner_id: string; project_id: string } | undefined; if (row) this.database.connection.prepare("INSERT OR IGNORE INTO m10_routing_incidents(incident_id,owner_id,project_id,task_id,recommendation_id,condition,evidence_json,created_at) VALUES(?,?,?,?,?,?,?,?)").run(`routing-incident-${sha256(`${recommendationId}\n${reason}`).slice(7, 55)}`, row.owner_id, row.project_id, taskId, recommendationId, "stale-recommendation", canonical({ reason }), at); this.emit(taskId, "routing.recommendation-stale"); }
  public assertConfirmedForDispatch(principal: Principal, taskId: string): void {
    const task = this.task(taskId); const row = this.database.connection.prepare("SELECT c.selected_worker_id,c.selected_adapter_id,c.expected_task_version,r.status FROM m10_route_confirmations c JOIN m10_recommendations r ON r.recommendation_id=c.recommendation_id WHERE c.owner_id=? AND c.task_id=? AND c.attempt_id=? AND c.operation_id=? ORDER BY c.confirmed_at DESC LIMIT 1").get(principal.administratorId, taskId, task.attempt_id, task.current_operation_id) as { selected_worker_id: string; selected_adapter_id: string; expected_task_version: number; status: string } | undefined;
    if (!row || row.status !== "confirmed" || row.expected_task_version !== task.version) throw new M6Error("CONFLICT", "an exact current M10 route confirmation is required before dispatch approval"); this.operations.assertExecutionAllowed(task.project_id);
  }
  public isConfirmedForDispatch(principal: Principal, taskId: string): boolean { try { this.assertConfirmedForDispatch(principal, taskId); return true; } catch { return false; } }
  public fallback(principal: Principal, taskIdRaw: unknown): Record<string, unknown> {
    const taskId = requireId(taskIdRaw, "taskId"); this.assertOwner(principal); const row = this.database.connection.prepare("SELECT f.* FROM m10_fallback_plans f WHERE f.owner_id=? AND f.task_id=? ORDER BY f.created_at DESC LIMIT 1").get(principal.administratorId, taskId) as Record<string, unknown> | undefined; if (!row) throw new M6Error("NOT_FOUND", "fallback plan was not found"); return { fallbackPlanId: row["fallback_plan_id"], recommendationId: row["recommendation_id"], taskId, reason: row["reason"], evidence: parseJson(String(row["evidence_json"])), options: parseJson(String(row["options_json"])), status: row["status"], createdAt: row["created_at"], automaticExecution: false };
  }
  public confirmFallback(principal: Principal, taskIdRaw: unknown, fallbackIdRaw: unknown, raw: Record<string, unknown>): Record<string, unknown> {
    const taskId = requireId(taskIdRaw, "taskId"); const fallbackId = requireId(fallbackIdRaw, "fallbackPlanId"); const key = requireKey(raw["idempotencyKey"]); const expectedVersion = requireVersion(raw["expectedVersion"]);
    return this.mutation(`routing.fallback.confirm:${principal.administratorId}:${fallbackId}`, key, { taskId, fallbackId, expectedVersion, optionIndex: raw["optionIndex"] }, () => { const row = this.database.connection.prepare("SELECT * FROM m10_fallback_plans WHERE fallback_plan_id=? AND owner_id=? AND task_id=?").get(fallbackId, principal.administratorId, taskId) as Record<string, unknown> | undefined; if (!row) throw new M6Error("NOT_FOUND", "fallback plan was not found"); const task = this.task(taskId); if (task.version !== expectedVersion) throw new M6Error("STALE_STATE", "task version is stale"); this.operations.assertExecutionAllowed(task.project_id); const blocked = parseJson<Record<string, unknown>>(task.blocked_context_json); if (blocked?.["blockedReason"] === "execution-unknown" || blocked?.["cancellationState"] === "unconfirmed" || ["RUNNING", "CANCELLING"].includes(task.state)) throw new M6Error("CONFLICT", "fallback is forbidden while original execution may be active or cancellation is uncertain"); if (row["status"] !== "proposed") throw new M6Error("CONFLICT", "fallback plan is not confirmable"); const options = parseJson<unknown[]>(String(row["options_json"])) ?? []; const optionIndex = Number(raw["optionIndex"]); if (!Number.isSafeInteger(optionIndex) || optionIndex < 0 || optionIndex >= options.length) throw new M6Error("INVALID_REQUEST", "fallback option is invalid"); const at = now(); this.database.connection.prepare("UPDATE m10_fallback_plans SET status='confirmed',confirmed_at=? WHERE fallback_plan_id=? AND status='proposed'").run(at, fallbackId); this.emit(taskId, "routing.fallback-confirmed"); return { fallbackPlanId: fallbackId, status: "confirmed", selectedOption: options[optionIndex], confirmedAt: at, dispatchCreated: false, attemptCreated: false, nextRequiredAction: "create-new-immutable-attempt-through-normal-lifecycle" }; });
  }
  public updatePolicy(principal: Principal, projectIdRaw: unknown, raw: Record<string, unknown>): Record<string, unknown> {
    this.assertOwner(principal); const projectId = requireId(projectIdRaw, "projectId"); const key = requireKey(raw["idempotencyKey"]); const expectedVersion = requireVersion(raw["expectedVersion"]);
    const preferredWorkers = Array.isArray(raw["preferredWorkers"]) ? raw["preferredWorkers"] : DEFAULT_POLICY.preferredWorkers; if (preferredWorkers.some((entry) => entry !== "codex-cli" && entry !== "manual-relay") || new Set(preferredWorkers).size !== preferredWorkers.length) throw new M6Error("INVALID_REQUEST", "preferred worker order is invalid"); const maximumQuotaAgeSeconds = Number(raw["maximumQuotaAgeSeconds"] ?? DEFAULT_POLICY.maximumQuotaAgeSeconds); if (!Number.isSafeInteger(maximumQuotaAgeSeconds) || maximumQuotaAgeSeconds < 60 || maximumQuotaAgeSeconds > 86_400) throw new M6Error("INVALID_REQUEST", "quota age policy is invalid"); const policy: Policy = { preferLowerCost: raw["preferLowerCost"] !== false, requireStrongSandboxForHighRisk: raw["requireStrongSandboxForHighRisk"] !== false, allowManualRelay: raw["allowManualRelay"] !== false, maximumQuotaAgeSeconds, preferredWorkers: preferredWorkers as string[], allowLowRiskConfirmation: raw["allowLowRiskConfirmation"] !== false };
    return this.mutation(`routing.policy:${principal.administratorId}:${projectId}`, key, { projectId, expectedVersion, policy }, () => { const current = this.policy(principal.administratorId, projectId); if (current.version !== expectedVersion) throw new M6Error("STALE_STATE", "routing policy is stale"); const version = expectedVersion + 1; const digest = sha256(canonical({ version, policy })); const at = now(); this.database.connection.prepare("INSERT INTO m10_routing_policies(policy_id,owner_id,project_id,version,policy_json,policy_digest,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(owner_id,project_id) DO UPDATE SET version=excluded.version,policy_json=excluded.policy_json,policy_digest=excluded.policy_digest,updated_at=excluded.updated_at WHERE m10_routing_policies.version=?").run(`routing-policy-${sha256(`${principal.administratorId}\n${projectId}`).slice(7, 55)}`, principal.administratorId, projectId, version, canonical(policy), digest, at, expectedVersion); this.operations.record({ eventId: `m10-policy-${digest.slice(7, 55)}`, eventKind: "routing.policy-changed", ownerId: principal.administratorId, projectId, source: "m10_routing", actorCategory: "owner", summary: "Owner changed bounded routing preferences; structural refusals and mandatory security capabilities remain fixed.", details: { version, policyDigest: digest }, occurredAt: at }); this.operations.project(); return { projectId, version, policy, policyDigest: digest, updatedAt: at }; });
  }
  public snapshot(principal: Principal, taskId?: string): Record<string, unknown> {
    this.assertOwner(principal); const where = taskId ? "AND r.task_id=?" : ""; const params = taskId ? [principal.administratorId, taskId] : [principal.administratorId]; const recommendations = this.database.connection.prepare(`SELECT r.recommendation_json,r.status AS authoritative_status,c.confirmation_id,c.confirmed_at FROM m10_recommendations r LEFT JOIN m10_route_confirmations c ON c.recommendation_id=r.recommendation_id WHERE r.owner_id=? ${where} ORDER BY r.generated_at DESC LIMIT 200`).all(...params) as Array<{ recommendation_json: string; authoritative_status: string; confirmation_id: string | null; confirmed_at: string | null }>;
    const quotas = this.database.connection.prepare("SELECT observation_json FROM m10_quota_observations WHERE observation_id IN (SELECT observation_id FROM m10_quota_observations q WHERE q.worker_id=m10_quota_observations.worker_id AND q.adapter_id=m10_quota_observations.adapter_id ORDER BY observed_at DESC LIMIT 1) ORDER BY worker_id,adapter_id").all() as Array<{ observation_json: string }>;
    const health = this.database.connection.prepare("SELECT worker_id,adapter_id,outcome,source,observed_at,expires_at FROM m10_health_observations WHERE observed_at >= ? ORDER BY observed_at DESC LIMIT 64").all(new Date(Date.now() - 7 * 86_400_000).toISOString());
    const policies = this.database.connection.prepare("SELECT project_id,version,policy_json,policy_digest,updated_at FROM m10_routing_policies WHERE owner_id=? ORDER BY project_id").all(principal.administratorId) as Array<Record<string, unknown>>;
    const fallbackWhere = taskId ? "AND task_id=?" : ""; const fallbackParams = taskId ? [principal.administratorId, taskId] : [principal.administratorId];
    const fallbacks = this.database.connection.prepare(`SELECT fallback_plan_id,recommendation_id,task_id,reason,evidence_json,options_json,status,created_at,confirmed_at FROM m10_fallback_plans WHERE owner_id=? ${fallbackWhere} ORDER BY created_at DESC LIMIT 200`).all(...fallbackParams) as Array<Record<string, unknown>>;
    return { routingVersion: M10_ROUTING_VERSION, recommendations: recommendations.map((row) => ({ ...JSON.parse(row.recommendation_json) as Record<string, unknown>, authoritativeStatus: row.authoritative_status, confirmation: row.confirmation_id ? { confirmationId: row.confirmation_id, confirmedAt: row.confirmed_at } : null })), fallbackPlans: fallbacks.map((row) => ({ fallbackPlanId: row["fallback_plan_id"], recommendationId: row["recommendation_id"], taskId: row["task_id"], reason: row["reason"], evidence: parseJson(String(row["evidence_json"])), options: parseJson(String(row["options_json"])) ?? [], status: row["status"], createdAt: row["created_at"], confirmedAt: row["confirmed_at"], automaticExecution: false })), quotaObservations: quotas.map((row) => { const value = parseJson<M10QuotaObservation>(row.observation_json)!; return { ...value, ...classifyM10Quota(value, now()) }; }), healthObservations: health, policies: policies.map((row) => ({ projectId: row["project_id"], version: row["version"], policy: parseJson(String(row["policy_json"])), policyDigest: row["policy_digest"], updatedAt: row["updated_at"] })), semantics: { recommendationIsDispatch: false, costIsEstimate: true, unknownQuotaIsAvailable: false, automaticFallback: false, executionUnknownFallback: false, manualRelayAssurance: "weaker-owner-attested" } };
  }
  public reconcileAfterRestart(): Record<string, unknown> {
    const candidates = this.database.connection.prepare("SELECT r.recommendation_id,r.task_id,r.status,r.input_digest,q.expected_task_version,t.version,t.state,t.blocked_context_json FROM m10_recommendations r JOIN m10_routing_requests q ON q.routing_request_id=r.routing_request_id JOIN tasks t ON t.task_id=r.task_id WHERE r.status IN ('generated','confirmed') ORDER BY r.recommendation_id").all() as Array<{ recommendation_id: string; task_id: string; status: string; input_digest: string; expected_task_version: number; version: number; state: string; blocked_context_json: string | null }>;
    let stale = 0; let preserved = 0; for (const row of candidates) { const blocked = parseJson<Record<string, unknown>>(row.blocked_context_json); if (row.version !== row.expected_task_version || !["AWAITING_DISPATCH", "BLOCKED"].includes(row.state) || blocked?.["blockedReason"] === "execution-unknown") { this.markStale(row.recommendation_id, row.task_id, blocked?.["blockedReason"] === "execution-unknown" ? "execution-unknown preserved across restart" : "task state changed across restart"); stale += 1; } else preserved += 1; }
    const core = { trigger: "control-plane-start", stale, preserved, noDispatchRepeated: true, noFallbackActivated: true }; const digest = sha256(canonical(core)); const at = now(); const inserted = this.database.connection.prepare("INSERT OR IGNORE INTO m10_reconciliation_runs(run_id,status,summary_json,started_at,completed_at,run_digest) VALUES(?,?,?,?,?,?)").run(`m10-reconcile-${digest.slice(7, 55)}`, "completed", canonical(core), at, at, digest); if (inserted.changes > 0) { this.operations.record({ eventId: `m10-reconciliation-${digest.slice(7, 55)}`, eventKind: "routing.reconciliation", source: "m10_routing", actorCategory: "system-recovery", summary: `M10 restart reconciliation preserved ${preserved} route(s), marked ${stale} stale, and triggered no dispatch or fallback.`, details: core, occurredAt: at }); this.operations.project(); } return core;
  }
}
