import { createHash } from "node:crypto";
import { statfsSync } from "node:fs";
import type { Principal } from "./auth.js";
import type { ControlPlaneConfig } from "./config.js";
import { ControlPlaneDatabase } from "./database.js";
import { M6Error } from "./m6-ui.js";

export const M11_OPERATIONAL_VERSION = "m11.operations/v1" as const;
export const M11_RELEASE_STATUS = "local MVP candidate" as const;
export const M11_LIMITS = Object.freeze({ maxAlerts: 500, maxEvidenceRefs: 16, maxSummaryBytes: 512, maxActionBytes: 512 } as const);
export type EvidenceConfidence = "authoritative" | "observed" | "estimated" | "owner-attested" | "unknown" | "stale";
type AlertSeverity = "info" | "warning" | "high" | "critical";
type AlertCondition = Readonly<{ projectId: string | null; key: string; severity: AlertSeverity; source: string; summary: string; action: string; evidenceRefs: readonly string[] }>;
type AlertRow = Readonly<{ alert_id: string; owner_id: string; project_id: string | null; condition_key: string; severity: AlertSeverity; source_condition: string; evidence_json: string; summary: string; recommended_action: string; state: "active" | "acknowledged" | "resolved"; first_seen_at: string; last_seen_at: string; acknowledged_at: string | null; resolved_at: string | null; resolution_evidence_json: string | null; version: number }>;

const now = (): string => new Date().toISOString();
const canonical = (value: unknown): string => {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;
};
const sha256 = (value: string): string => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const clean = (value: string, maximum: number): string => { const normalized = [...value].map((character) => { const code = character.charCodeAt(0); return code <= 31 || code === 127 || character === "<" || character === ">" ? " " : character; }).join(""); return Buffer.from(normalized.replace(/\s+/gu, " ").trim(), "utf8").subarray(0, maximum).toString("utf8"); };
const metric = <T>(value: T, confidence: EvidenceConfidence, evidenceRefs: readonly string[], observedAt = now()): Readonly<{ value: T; confidence: EvidenceConfidence; evidenceRefs: readonly string[]; observedAt: string }> => Object.freeze({ value, confidence, evidenceRefs: Object.freeze([...evidenceRefs].slice(0, M11_LIMITS.maxEvidenceRefs)), observedAt });
const parse = <T>(value: unknown, fallback: T): T => {
  try {
    const parsed = JSON.parse(String(value)) as T;
    return parsed === null || parsed === undefined ? fallback : parsed;
  } catch {
    return fallback;
  }
};
const safeId = (value: unknown): string => typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._:-]{0,191}$/u.test(value) && !value.includes("..") ? value : "unknown";

export class M11OperationsService {
  private publisher: ((eventKind: string) => void) | undefined;
  public constructor(private readonly database: ControlPlaneDatabase, private readonly config: ControlPlaneConfig) {}
  public setPublisher(publisher: (eventKind: string) => void): void { this.publisher = publisher; }

  private owner(principal?: Principal): string | null {
    if (principal) {
      const exists = this.database.connection.prepare("SELECT 1 FROM administrators WHERE id=? AND disabled_at IS NULL").get(principal.administratorId);
      if (!exists) throw new M6Error("NOT_FOUND", "owner scope is unavailable");
      return principal.administratorId;
    }
    return (this.database.connection.prepare("SELECT id FROM administrators WHERE disabled_at IS NULL ORDER BY created_at LIMIT 1").get() as { id: string } | undefined)?.id ?? null;
  }

  private alertId(ownerId: string, condition: AlertCondition): string { return `alert-${sha256(canonical({ ownerId, projectId: condition.projectId, key: condition.key })).slice(7, 55)}`; }
  private conditions(): readonly AlertCondition[] {
    const db = this.database.connection; const result: AlertCondition[] = [];
    const push = (value: AlertCondition): void => { result.push(Object.freeze({ ...value, projectId: value.projectId === null ? null : safeId(value.projectId), summary: clean(value.summary, M11_LIMITS.maxSummaryBytes), action: clean(value.action, M11_LIMITS.maxActionBytes), evidenceRefs: Object.freeze(value.evidenceRefs.map(safeId).slice(0, M11_LIMITS.maxEvidenceRefs)) })); };
    const bridge = db.prepare("SELECT connection_state,last_seen_at,version FROM m8_bridge_state WHERE bridge_id='local-bridge'").get() as { connection_state: string; last_seen_at: string | null; version: number } | undefined;
    if (bridge?.connection_state !== "connected") push({ projectId: null, key: "bridge-disconnected", severity: "high", source: "m8_bridge_state", summary: "Local Bridge is not authoritatively connected.", action: "Validate local configuration and start the outbound-only Bridge; do not bypass execution gates.", evidenceRefs: ["bridge:local-bridge", `bridge-version:${bridge?.version ?? 0}`] });
    const componentVersion = db.prepare("SELECT runtime_version FROM m11_component_versions WHERE component_id='local-bridge'").get() as { runtime_version: string } | undefined; const expectedRuntimeVersion = process.env["CHUBZ_BUILD_VERSION"] ?? "0.11.0-mvp.1"; if (componentVersion && componentVersion.runtime_version !== expectedRuntimeVersion) push({ projectId: null, key: "runtime-version-mismatch", severity: "high", source: "m11_component_versions", summary: "Control Plane and Local Bridge runtime versions do not match.", action: "Stop the known local runtime, verify one release package, and restart both components from that package.", evidenceRefs: ["bridge:local-bridge", `bridge-version:${bridge?.version ?? 0}`] });
    const migration = db.prepare("SELECT COUNT(*) AS count,MAX(version) AS version FROM schema_migrations").get() as { count: number; version: number }; if (migration.count !== ControlPlaneDatabase.latestSchemaVersion || migration.version !== ControlPlaneDatabase.latestSchemaVersion) push({ projectId: null, key: "database-migration-mismatch", severity: "critical", source: "schema_migrations", summary: "Database migration history does not match the packaged runtime schema.", action: "Keep runtime execution unavailable and run only the bounded migration inspection or migration command after backup review.", evidenceRefs: ["schema_migrations"] });
    const adapters = db.prepare("SELECT worker_id,adapter_id,readiness_state,readiness_json,evidence_json,recorded_at FROM m5_adapter_readiness ORDER BY recorded_at DESC").all() as Array<Record<string, unknown>>; const seen = new Set<string>();
    for (const row of adapters) { const identity = `${safeId(row["worker_id"])}:${safeId(row["adapter_id"])}`; if (seen.has(identity)) continue; seen.add(identity); const readiness = parse<Record<string, unknown>>(row["readiness_json"], {}); const evidence = parse<Record<string, unknown>>(row["evidence_json"], {}); const state = String(row["readiness_state"]); if (state !== "ready") push({ projectId: null, key: `adapter-unavailable:${identity}`, severity: state === "blocked" ? "high" : "warning", source: "m5_adapter_readiness", summary: `Adapter ${identity} readiness is ${clean(state, 32)}.`, action: "Inspect bounded readiness evidence and re-probe locally before dispatch.", evidenceRefs: [safeId(readiness["readinessId"]), identity] }); if (evidence["drift"] === true) push({ projectId: null, key: `adapter-drift:${identity}`, severity: "high", source: "m5_adapter_readiness", summary: `Adapter ${identity} has observed compatibility drift.`, action: "Freeze dispatch and run the bounded compatibility canary before owner approval.", evidenceRefs: [safeId(readiness["readinessId"]), identity] }); if (["missing", "expired", "unknown"].includes(String(readiness["authenticationState"]))) push({ projectId: null, key: `authentication-unavailable:${identity}`, severity: "high", source: "m5_adapter_readiness", summary: `Adapter ${identity} authentication is unavailable or unknown.`, action: "Complete owner-authorized local authentication in the isolated adapter home, then re-probe.", evidenceRefs: [safeId(readiness["readinessId"]), identity] }); const sandbox = parse<Record<string, unknown>>(String(row["evidence_json"]), {})["windowsSandbox"] as Record<string, unknown> | undefined; if (sandbox?.["assurance"] === "degraded-bounded-local") push({ projectId: null, key: `sandbox-degraded:${identity}`, severity: "warning", source: "m5_adapter_readiness", summary: `Adapter ${identity} is using degraded bounded-local sandbox assurance.`, action: "Review the recorded sandbox limitation before approving any execution.", evidenceRefs: [safeId(readiness["readinessId"]), identity] }); }
    const latestQuota = db.prepare("SELECT worker_id,adapter_id,observation_id,observation_json,observed_at,expires_at FROM m10_quota_observations ORDER BY observed_at DESC").all() as Array<Record<string, unknown>>; const quotaSeen = new Set<string>();
    for (const row of latestQuota) { const identity = `${safeId(row["worker_id"])}:${safeId(row["adapter_id"])}`; if (quotaSeen.has(identity)) continue; quotaSeen.add(identity); const value = parse<Record<string, unknown>>(row["observation_json"], {}); const confidence = String(value["confidence"] ?? "unknown"); const remaining = value["remaining"]; const expires = typeof row["expires_at"] === "string" ? Date.parse(row["expires_at"]) : Number.NaN; const stale = Number.isFinite(expires) && expires < Date.now(); const constrained = remaining === 0 || ["exhausted", "constrained"].includes(String(value["rateLimitState"] ?? value["quotaKind"])); if (stale || confidence === "unknown" || constrained) push({ projectId: null, key: `quota-${stale ? "stale" : constrained ? "constrained" : "unknown"}:${identity}`, severity: constrained ? "high" : "warning", source: "m10_quota_observations", summary: `Quota for ${identity} is ${stale ? "stale" : constrained ? "constrained or exhausted" : "unknown"}.`, action: "Refresh authoritative quota evidence; unknown quota must not be treated as available.", evidenceRefs: [safeId(row["observation_id"]), identity] }); }
    for (const row of db.prepare("SELECT task_id,project_id,state,blocked_context_json,current_operation_id FROM tasks WHERE state IN ('BLOCKED','CANCELLING')").all() as Array<Record<string, unknown>>) { const blocked = parse<Record<string, unknown>>(row["blocked_context_json"], {}); if (blocked["blockedReason"] === "execution-unknown") push({ projectId: String(row["project_id"]), key: `execution-unknown:${safeId(row["task_id"])}`, severity: "critical", source: "tasks", summary: `Task ${safeId(row["task_id"])} has execution-unknown state.`, action: "Do not retry; reconcile only from authoritative owner and runtime evidence.", evidenceRefs: [safeId(row["task_id"]), safeId(row["current_operation_id"])] }); if (row["state"] === "CANCELLING" || blocked["cancellationState"] === "unconfirmed") push({ projectId: String(row["project_id"]), key: `cancellation-uncertain:${safeId(row["task_id"])}`, severity: "high", source: "tasks", summary: `Task ${safeId(row["task_id"])} cancellation is not authoritatively confirmed.`, action: "Keep execution blocked until Bridge process-tree termination evidence is authoritative.", evidenceRefs: [safeId(row["task_id"]), safeId(row["current_operation_id"])] }); }
    for (const row of db.prepare("SELECT stop_id,scope_type,project_id FROM m8_emergency_stops WHERE status='active'").all() as Array<Record<string, unknown>>) push({ projectId: row["scope_type"] === "project" ? String(row["project_id"]) : null, key: `emergency-stop:${safeId(row["stop_id"])}`, severity: "critical", source: "m8_emergency_stops", summary: "Authoritative emergency stop is active.", action: "Inspect cancellation evidence; release only after the condition is understood. Release never resumes work.", evidenceRefs: [safeId(row["stop_id"])] });
    for (const row of db.prepare("SELECT incident_id,project_id,condition,severity FROM m8_recovery_incidents WHERE resolution_state!='closed'").all() as Array<Record<string, unknown>>) push({ projectId: typeof row["project_id"] === "string" ? row["project_id"] : null, key: `recovery:${safeId(row["incident_id"])}`, severity: ["info","warning","high","critical"].includes(String(row["severity"])) ? row["severity"] as AlertSeverity : "warning", source: "m8_recovery_incidents", summary: `Recovery incident remains unresolved: ${clean(String(row["condition"]), 128)}.`, action: "Review the authoritative incident evidence; acknowledgement does not resolve it.", evidenceRefs: [safeId(row["incident_id"])] });
    const projection = db.prepare("SELECT status,version FROM m8_projection_state WHERE projection_id=1").get() as { status: string; version: number } | undefined; if (projection && !["current", "empty"].includes(projection.status)) push({ projectId: null, key: `projection-${safeId(projection.status)}`, severity: "high", source: "m8_projection_state", summary: `Bridge Log projection status is ${clean(projection.status, 64)}.`, action: "Verify authoritative events, then rebuild the non-authoritative projection if safe.", evidenceRefs: [`projection-version:${projection.version}`] });
    for (const row of db.prepare("SELECT capture_id,project_id,status FROM m7_capture_requests WHERE status IN ('incomplete','quarantined','failed')").all() as Array<Record<string, unknown>>) push({ projectId: String(row["project_id"]), key: `capture-${safeId(row["capture_id"])}`, severity: row["status"] === "quarantined" ? "high" : "warning", source: "m7_capture_requests", summary: `Evidence capture ${safeId(row["capture_id"])} is ${clean(String(row["status"]), 32)}.`, action: "Inspect capture evidence; do not treat an incomplete or quarantined package as verified.", evidenceRefs: [safeId(row["capture_id"])] });
    for (const row of db.prepare("SELECT recommendation_id,project_id FROM m10_recommendations WHERE status='stale'").all() as Array<Record<string, unknown>>) push({ projectId: String(row["project_id"]), key: `routing-stale:${safeId(row["recommendation_id"])}`, severity: "warning", source: "m10_recommendations", summary: `Routing recommendation ${safeId(row["recommendation_id"])} is stale.`, action: "Generate a fresh recommendation; stale confirmation cannot authorize dispatch.", evidenceRefs: [safeId(row["recommendation_id"])] });
    for (const row of db.prepare("SELECT apply_id,target_project_id,status FROM m9_apply_requests WHERE status IN ('apply-unknown','promotion-unknown')").all() as Array<Record<string, unknown>>) push({ projectId: String(row["target_project_id"]), key: `apply-unknown:${safeId(row["apply_id"])}`, severity: "critical", source: "m9_apply_requests", summary: `Apply operation ${safeId(row["apply_id"])} has an unknown outcome.`, action: "Do not retry or roll back automatically; reconcile repository evidence first.", evidenceRefs: [safeId(row["apply_id"])] });
    try { const storage = statfsSync(this.config.dataDirectory); const total = Number(storage.blocks) * Number(storage.bsize); const available = Number(storage.bavail) * Number(storage.bsize); const usedPercent = total > 0 ? Math.round((1 - available / total) * 100) : 0; const threshold = this.config.m11?.storageWarningPercent ?? 85; if (usedPercent >= threshold) push({ projectId: null, key: "storage-bound-approaching", severity: usedPercent >= 95 ? "critical" : "warning", source: "filesystem-capacity", summary: `Managed storage volume is ${usedPercent}% used.`, action: "Use the owner-configured retention preview; never delete authoritative evidence or project files.", evidenceRefs: ["storage:managed-volume"] }); } catch { push({ projectId: null, key: "storage-unknown", severity: "warning", source: "filesystem-capacity", summary: "Managed storage capacity is unknown.", action: "Inspect the local managed volume before starting new bounded captures or packages.", evidenceRefs: ["storage:managed-volume"] }); }
    return Object.freeze(result);
  }

  public refreshAlerts(principal?: Principal): readonly Record<string, unknown>[] {
    const ownerId = this.owner(principal); if (ownerId === null) return Object.freeze([]); const observedAt = now(); const conditions = this.conditions(); const activeIds = new Set<string>(); const eventKinds = new Set<string>();
    this.database.connection.transaction(() => {
      for (const condition of conditions) {
        const alertId = this.alertId(ownerId, condition);
        activeIds.add(alertId);
        const evidenceCore = canonical({ refs: condition.evidenceRefs, authority: condition.source });
        const evidence = canonical({ refs: condition.evidenceRefs, authority: condition.source, observedAt });
        const existing = this.database.connection.prepare("SELECT state,severity,source_condition,summary,recommended_action,evidence_json FROM m11_alerts WHERE alert_id=?").get(alertId) as Record<string, unknown> | undefined;
        if (!existing) {
          this.database.connection.prepare("INSERT INTO m11_alerts(alert_id,owner_id,project_id,condition_key,severity,source_condition,evidence_json,summary,recommended_action,state,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,'active',?,?)").run(alertId, ownerId, condition.projectId, condition.key, condition.severity, condition.source, evidence, condition.summary, condition.action, observedAt, observedAt);
          eventKinds.add("alert.created");
        } else {
          const priorEvidence = parse<Record<string, unknown>>(existing["evidence_json"], {});
          const priorEvidenceCore = canonical({ refs: priorEvidence["refs"] ?? [], authority: priorEvidence["authority"] ?? existing["source_condition"] });
          const preserve = existing["state"] === "acknowledged" ? "acknowledged" : "active";
          const material = existing["severity"] !== condition.severity || existing["source_condition"] !== condition.source || existing["summary"] !== condition.summary || existing["recommended_action"] !== condition.action || priorEvidenceCore !== evidenceCore || existing["state"] === "resolved";
          this.database.connection.prepare("UPDATE m11_alerts SET severity=?,source_condition=?,evidence_json=?,summary=?,recommended_action=?,state=?,last_seen_at=?,resolved_at=NULL,resolution_evidence_json=NULL,version=version+? WHERE alert_id=?").run(condition.severity, condition.source, evidence, condition.summary, condition.action, preserve, observedAt, material ? 1 : 0, alertId);
          if (material) eventKinds.add("alert.updated");
        }
      }
      const unresolved = this.database.connection.prepare("SELECT alert_id FROM m11_alerts WHERE owner_id=? AND state!='resolved'").all(ownerId) as Array<{ alert_id: string }>;
      for (const row of unresolved) if (!activeIds.has(row.alert_id)) { this.database.connection.prepare("UPDATE m11_alerts SET state='resolved',resolved_at=?,last_seen_at=?,resolution_evidence_json=?,version=version+1 WHERE alert_id=? AND state!='resolved'").run(observedAt, observedAt, canonical({ authority: "condition-reconciliation", conditionPresent: false, observedAt }), row.alert_id); eventKinds.add("alert.resolved"); }
    })();
    for (const eventKind of eventKinds) this.publisher?.(eventKind); return this.listAlerts({ administratorId: ownerId } as Principal);
  }

  private projectAlert(row: AlertRow): Record<string, unknown> { const evidence = parse<{ refs?: unknown[]; authority?: string; observedAt?: string }>(row.evidence_json, {}); return { alertId: row.alert_id, projectId: row.project_id, conditionKey: row.condition_key, severity: row.severity, sourceCondition: row.source_condition, state: row.state, firstSeenAt: row.first_seen_at, lastSeenAt: row.last_seen_at, acknowledgedAt: row.acknowledged_at, resolvedAt: row.resolved_at, version: row.version, summary: row.summary, recommendedAction: row.recommended_action, evidence: { references: Array.isArray(evidence.refs) ? evidence.refs.slice(0, M11_LIMITS.maxEvidenceRefs) : [], authority: evidence.authority ?? row.source_condition, observedAt: evidence.observedAt ?? row.last_seen_at }, acknowledgementResolvesCondition: false };
  }
  public listAlerts(principal: Principal, state?: string): readonly Record<string, unknown>[] { const ownerId = this.owner(principal)!; const boundedState = state === undefined ? null : ["active","acknowledged","resolved"].includes(state) ? state : (() => { throw new M6Error("INVALID_REQUEST", "alert state is invalid"); })(); const rows = boundedState === null ? this.database.connection.prepare("SELECT * FROM m11_alerts WHERE owner_id=? ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'warning' THEN 2 ELSE 3 END,last_seen_at DESC LIMIT ?").all(ownerId, M11_LIMITS.maxAlerts) : this.database.connection.prepare("SELECT * FROM m11_alerts WHERE owner_id=? AND state=? ORDER BY last_seen_at DESC LIMIT ?").all(ownerId, boundedState, M11_LIMITS.maxAlerts); return Object.freeze((rows as AlertRow[]).map((row) => Object.freeze(this.projectAlert(row)))); }
  public alert(principal: Principal, alertIdRaw: unknown): Record<string, unknown> { const alertId = safeId(alertIdRaw); const row = this.database.connection.prepare("SELECT * FROM m11_alerts WHERE alert_id=? AND owner_id=?").get(alertId, this.owner(principal)) as AlertRow | undefined; if (!row) throw new M6Error("NOT_FOUND", "alert was not found"); return this.projectAlert(row); }

  private mutation<T>(scope: string, keyRaw: unknown, request: unknown, execute: () => T): T { const key = safeId(keyRaw); if (key === "unknown") throw new M6Error("INVALID_REQUEST", "idempotency key is invalid"); const requestDigest = sha256(canonical(request)); return this.database.connection.transaction(() => { const row = this.database.connection.prepare("SELECT request_digest,result_json FROM m11_mutations WHERE mutation_scope=? AND idempotency_key=?").get(scope, key) as { request_digest: string; result_json: string | null } | undefined; if (row) { if (row.request_digest !== requestDigest) throw new M6Error("CONFLICT", "idempotency key conflicts with a prior request"); if (row.result_json === null) throw new M6Error("CONFLICT", "mutation outcome is uncertain"); return parse<T>(row.result_json, undefined as T); } this.database.connection.prepare("INSERT INTO m11_mutations(mutation_scope,idempotency_key,request_digest,recorded_at) VALUES(?,?,?,?)").run(scope, key, requestDigest, now()); const result = execute(); this.database.connection.prepare("UPDATE m11_mutations SET result_json=? WHERE mutation_scope=? AND idempotency_key=?").run(canonical(result), scope, key); return result; })(); }
  public acknowledge(principal: Principal, alertIdRaw: unknown, raw: Record<string, unknown>): Record<string, unknown> { const alertId = safeId(alertIdRaw); const expectedVersion = Number(raw["expectedVersion"]); if (!Number.isSafeInteger(expectedVersion) || expectedVersion < 1) throw new M6Error("INVALID_REQUEST", "expected version is invalid"); return this.mutation(`alert.ack:${principal.administratorId}:${alertId}`, raw["idempotencyKey"], { alertId, expectedVersion }, () => { const row = this.database.connection.prepare("SELECT * FROM m11_alerts WHERE alert_id=? AND owner_id=?").get(alertId, this.owner(principal)) as AlertRow | undefined; if (!row) throw new M6Error("NOT_FOUND", "alert was not found"); if (row.version !== expectedVersion) throw new M6Error("STALE_STATE", "alert version is stale"); if (row.state === "resolved") throw new M6Error("CONFLICT", "resolved alert cannot be acknowledged"); const at = now(); this.database.connection.prepare("UPDATE m11_alerts SET state='acknowledged',acknowledged_at=?,acknowledged_by=?,version=version+1 WHERE alert_id=? AND version=?").run(at, principal.administratorId, alertId, expectedVersion); this.publisher?.("alert.acknowledged"); return { alertId, state: "acknowledged", version: expectedVersion + 1, acknowledgedAt: at, conditionResolved: false }; }); }

  public operationalSummary(principal: Principal): Record<string, unknown> {
    this.owner(principal); const db = this.database.connection; const generatedAt = now(); const scalar = (sql: string, ...params: unknown[]): number => Number((db.prepare(sql).get(...params) as { n: number }).n);
    const stateRows = db.prepare("SELECT state,COUNT(*) AS n FROM tasks GROUP BY state").all() as Array<{ state: string; n: number }>; const states = Object.fromEntries(stateRows.map((row) => [row.state.toLowerCase().replaceAll("_", "-"), row.n])); const executionUnknown = scalar("SELECT COUNT(*) AS n FROM tasks WHERE state='BLOCKED' AND json_extract(blocked_context_json,'$.blockedReason')='execution-unknown'");
    const bridge = (db.prepare("SELECT connection_state,last_seen_at,version FROM m8_bridge_state WHERE bridge_id='local-bridge'").get() as Record<string, unknown> | undefined) ?? { connection_state: "unknown", last_seen_at: null, version: 0 }; const bridgeVersion = (db.prepare("SELECT runtime_version FROM m11_component_versions WHERE component_id='local-bridge'").get() as { runtime_version: string } | undefined)?.runtime_version ?? null; const projection = (db.prepare("SELECT status,cursor_sequence,projected_event_count,verified_at,version FROM m8_projection_state WHERE projection_id=1").get() as Record<string, unknown> | undefined) ?? { status: "unknown", cursor_sequence: 0, projected_event_count: 0, verified_at: null, version: 0 }; const migrations = db.prepare("SELECT COUNT(*) AS n,MAX(version) AS version FROM schema_migrations").get() as { n: number; version: number }; const event = db.prepare("SELECT head_sequence,oldest_retained_sequence FROM event_streams WHERE stream_id='ui-tasks'").get() as Record<string, unknown> | undefined;
    const adapters = db.prepare("SELECT readiness_state,COUNT(*) AS n FROM (SELECT readiness_state,ROW_NUMBER() OVER(PARTITION BY worker_id,adapter_id ORDER BY recorded_at DESC) AS rank FROM m5_adapter_readiness) WHERE rank=1 GROUP BY readiness_state").all() as Array<Record<string, unknown>>; const adapterDrift = scalar("SELECT COUNT(*) AS n FROM m5_adapter_readiness WHERE json_extract(evidence_json,'$.drift')=1"); const degradedSandbox = scalar("SELECT COUNT(*) AS n FROM m5_adapter_readiness WHERE json_extract(evidence_json,'$.windowsSandbox.assurance')='degraded-bounded-local'");
    const quota = db.prepare("SELECT observation_json,observed_at,expires_at FROM m10_quota_observations ORDER BY observed_at DESC LIMIT 1").get() as Record<string, unknown> | undefined; const quotaValue = quota ? parse<Record<string, unknown>>(quota["observation_json"], {}) : {}; const quotaConfidence: EvidenceConfidence = !quota ? "unknown" : typeof quota["expires_at"] === "string" && Date.parse(quota["expires_at"]) < Date.now() ? "stale" : quotaValue["confidence"] === "owner-attested" ? "owner-attested" : quotaValue["confidence"] === "estimated" ? "estimated" : quotaValue["confidence"] === "authoritative" ? "authoritative" : "observed";
    let storageValue: Record<string, unknown> = { available: false, usedPercent: null }; let storageConfidence: EvidenceConfidence = "unknown"; try { const stat = statfsSync(this.config.dataDirectory); const total = Number(stat.blocks) * Number(stat.bsize); const available = Number(stat.bavail) * Number(stat.bsize); storageValue = { available: true, totalBytes: total, availableBytes: available, usedPercent: total > 0 ? Math.round((1 - available / total) * 100) : 0 }; storageConfidence = "observed"; } catch { /* honest unknown */ }
    const alerts = this.refreshAlerts(principal); const activeAlerts = alerts.filter((item) => item["state"] !== "resolved"); const runtimeVersion = process.env["CHUBZ_BUILD_VERSION"] ?? "0.11.0-mvp.1"; const buildCommit = process.env["CHUBZ_BUILD_COMMIT"] ?? "working-tree"; const buildTimestamp = process.env["CHUBZ_BUILD_TIMESTAMP"] ?? null;
    return { operationalVersion: M11_OPERATIONAL_VERSION, generatedAt, releaseStatus: M11_RELEASE_STATUS, metrics: {
      controlPlane: metric({ health: "ok", readiness: this.database.isReady() ? "ready" : "unavailable", localOnly: true }, "authoritative", ["control-plane:process"], generatedAt),
      bridge: metric({ connection: bridge["connection_state"], lastSeenAt: bridge["last_seen_at"] ?? null, runtimeVersion: bridgeVersion ?? "unknown", versionMatch: bridgeVersion === null ? "unknown" : bridgeVersion === runtimeVersion, failClosed: bridge["connection_state"] !== "connected" }, "authoritative", ["m8_bridge_state:local-bridge", ...(bridgeVersion === null ? [] : ["m11_component_versions:local-bridge"])], generatedAt),
      database: metric({ ready: this.database.isReady(), migrationCount: migrations.n, schemaVersion: migrations.version, expectedSchemaVersion: ControlPlaneDatabase.latestSchemaVersion, migrationMatch: migrations.version === ControlPlaneDatabase.latestSchemaVersion }, "authoritative", ["schema_migrations"], generatedAt),
      eventStream: metric({ websocketRoute: "available", streamId: "ui-tasks", headSequence: event?.["head_sequence"] ?? 0, oldestRetainedSequence: event?.["oldest_retained_sequence"] ?? 1 }, "authoritative", ["event_streams:ui-tasks"], generatedAt),
      tasks: metric({ total: scalar("SELECT COUNT(*) AS n FROM tasks"), active: scalar("SELECT COUNT(*) AS n FROM tasks WHERE state NOT IN ('CANCELLED','REJECTED','FAILED','COMPLETED')"), attempts: scalar("SELECT COUNT(*) AS n FROM task_attempts"), queued: scalar("SELECT COUNT(*) AS n FROM m4_dispatch_queue WHERE status='queued'"), running: Number(states["running"] ?? 0), blocked: Number(states["blocked"] ?? 0), cancelled: Number(states["cancelled"] ?? 0), failed: Number(states["failed"] ?? 0), executionUnknown }, "authoritative", ["tasks", "task_attempts", "m4_dispatch_queue"], generatedAt),
      adapters: metric({ readinessCounts: Object.fromEntries(adapters.map((row) => [String(row["readiness_state"]), Number(row["n"])])), driftCount: adapterDrift }, adapters.length > 0 ? "observed" : "unknown", ["m5_adapter_readiness"], generatedAt),
      sandbox: metric({ degradedCount: degradedSandbox, assurance: degradedSandbox > 0 ? "degraded-bounded-local" : adapters.length > 0 ? "recorded" : "unknown" }, adapters.length > 0 ? "observed" : "unknown", ["m5_adapter_readiness:sandbox"], generatedAt),
      quota: metric({ state: quota ? quotaValue : "unknown", observedAt: quota?.["observed_at"] ?? null, expiresAt: quota?.["expires_at"] ?? null }, quotaConfidence, quota ? ["m10_quota_observations"] : [], generatedAt),
      emergencyStop: metric({ active: scalar("SELECT COUNT(*) AS n FROM m8_emergency_stops WHERE status='active'") > 0, activeCount: scalar("SELECT COUNT(*) AS n FROM m8_emergency_stops WHERE status='active'") }, "authoritative", ["m8_emergency_stops"], generatedAt),
      recovery: metric({ unresolvedIncidents: scalar("SELECT COUNT(*) AS n FROM m8_recovery_incidents WHERE resolution_state!='closed'") }, "authoritative", ["m8_recovery_incidents"], generatedAt),
      projection: metric({ status: projection["status"], cursor: projection["cursor_sequence"], entries: projection["projected_event_count"], verifiedAt: projection["verified_at"], rebuildable: true }, "authoritative", ["m8_projection_state"], generatedAt),
      reviewPackages: metric({ total: scalar("SELECT COUNT(*) AS n FROM m7_review_packages"), captured: scalar("SELECT COUNT(*) AS n FROM m7_review_packages WHERE status='captured'"), unavailable: scalar("SELECT COUNT(*) AS n FROM m7_review_packages WHERE status!='captured'") }, "authoritative", ["m7_review_packages"], generatedAt),
      applyPromotion: metric({ total: scalar("SELECT COUNT(*) AS n FROM m9_apply_requests"), unknown: scalar("SELECT COUNT(*) AS n FROM m9_apply_requests WHERE status IN ('apply-unknown','promotion-unknown')"), incidents: scalar("SELECT COUNT(*) AS n FROM m9_apply_evidence WHERE evidence_kind LIKE '%unknown%'") }, "authoritative", ["m9_apply_requests", "m9_apply_evidence"], generatedAt),
      routing: metric({ recommendations: scalar("SELECT COUNT(*) AS n FROM m10_recommendations"), stale: scalar("SELECT COUNT(*) AS n FROM m10_recommendations WHERE status='stale'"), confirmations: scalar("SELECT COUNT(*) AS n FROM m10_route_confirmations") }, "authoritative", ["m10_recommendations", "m10_route_confirmations"], generatedAt),
      storage: metric(storageValue, storageConfidence, storageConfidence === "unknown" ? [] : ["filesystem:managed-volume"], generatedAt),
      alerts: metric({ unresolved: activeAlerts.length, critical: activeAlerts.filter((item) => item["severity"] === "critical").length, acknowledged: activeAlerts.filter((item) => item["state"] === "acknowledged").length }, "authoritative", ["m11_alerts"], generatedAt),
      version: metric({ applicationVersion: runtimeVersion, gitCommit: buildCommit, buildTimestamp, schemaVersions: { database: ControlPlaneDatabase.latestSchemaVersion, operations: M11_OPERATIONAL_VERSION }, packageFormatVersion: 1, components: { controlPlane: runtimeVersion, web: runtimeVersion, localBridge: runtimeVersion }, supportedOperatingSystem: "Windows 10/11 local", requiredRuntime: { node: ">=20", pnpm: ">=11" }, status: M11_RELEASE_STATUS, milestone: "M11 implementation candidate", knownLimitations: ["No remote access", "No automatic installation, upgrade, rollback, push, or deployment", "No live provider quota guarantee"] }, buildCommit === "working-tree" ? "unknown" : "authoritative", ["release:identity"], generatedAt),
    }, alerts: activeAlerts };
  }

  public reconcile(): Record<string, unknown> { const startedAt = now(); const owner = this.owner(); const alerts = owner === null ? [] : this.refreshAlerts(); const summary = { trigger: "control-plane-start", alertsObserved: alerts.length, automaticExecution: false, automaticCleanup: false, bridgeGateRequired: true }; const runDigest = sha256(canonical(summary)); const runId = `m11-reconcile-${runDigest.slice(7, 55)}`; this.database.connection.prepare("INSERT OR IGNORE INTO m11_reconciliation_runs(run_id,trigger_kind,summary_json,run_digest,started_at,completed_at) VALUES(?,?,?,?,?,?)").run(runId, "control-plane-start", canonical(summary), runDigest, startedAt, now()); return { runId, ...summary };
}
}
