import { createHash } from "node:crypto";
import { lstatSync, readFileSync, readdirSync } from "node:fs";
import { isAbsolute, relative, resolve, sep } from "node:path";

const safeName = (name: string): boolean => { if (name === "." || name === ".." || Buffer.byteLength(name) < 1 || Buffer.byteLength(name) > 192 || name.endsWith(".") || name.endsWith(" ") || /[<>:"/\\|?*]/u.test(name) || /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/iu.test(name)) return false; return [...name].every((character) => character.charCodeAt(0) > 31 && character.charCodeAt(0) !== 127); };
const sha = (value: Buffer): string => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const canonical = (value: unknown): string => { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; };
const contained = (root: string, target: string): boolean => { const rel = relative(root, target); return rel === "" || (rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel)); };
export type ReleaseFileHash = Readonly<{ path: string; size: number; sha256: string }>;
export function hashReleaseFiles(rootRaw: string, limits = { maxFiles: 20_000, maxBytes: 512 * 1024 * 1024 }): readonly ReleaseFileHash[] { const root = resolve(rootRaw); const stack = [root]; const files: ReleaseFileHash[] = []; let total = 0; while (stack.length > 0) { const current = stack.pop()!; for (const entry of readdirSync(current, { withFileTypes: true })) { if (!safeName(entry.name) || entry.isSymbolicLink()) throw new Error("release contains an unsafe filename or link"); const path = resolve(current, entry.name); if (!contained(root, path)) throw new Error("release entry escaped its root"); const metadata = lstatSync(path); if (metadata.isSymbolicLink()) throw new Error("release contains a link or reparse point"); if (entry.isDirectory()) stack.push(path); else if (entry.isFile()) { const content = readFileSync(path); total += content.byteLength; files.push(Object.freeze({ path: relative(root, path).split(sep).join("/"), size: content.byteLength, sha256: sha(content) })); if (files.length > limits.maxFiles || total > limits.maxBytes) throw new Error("release exceeds its file-count or size bound"); } else throw new Error("release contains an unsupported filesystem entry"); } } return Object.freeze(files.sort((left, right) => left.path.localeCompare(right.path))); }
export function verifyLocalReleasePackage(rootRaw: string): Readonly<{ verified: boolean; packageDigest: string; fileCount: number; sizeBytes: number; errors: readonly string[] }> { const root = resolve(rootRaw); try { const actual = hashReleaseFiles(root); const manifestFile = actual.find((entry) => entry.path === "SHA256SUMS.json"); if (!manifestFile) throw new Error("release hash manifest is missing"); const manifest = JSON.parse(readFileSync(resolve(root, "SHA256SUMS.json"), "utf8")) as Record<string, unknown>; const expected = Array.isArray(manifest["files"]) ? manifest["files"] : []; const content = actual.filter((entry) => entry.path !== "SHA256SUMS.json"); const verified = manifest["formatVersion"] === 1 && canonical(expected) === canonical(content); return Object.freeze({ verified, packageDigest: `sha256:${createHash("sha256").update(canonical(content)).digest("hex")}`, fileCount: actual.length, sizeBytes: actual.reduce((sum, entry) => sum + entry.size, 0), errors: Object.freeze(verified ? [] : ["Release file hashes do not match the manifest."]) }); } catch { return Object.freeze({ verified: false, packageDigest: "unavailable", fileCount: 0, sizeBytes: 0, errors: Object.freeze(["Release verification failed safely."]) }); } }
