import { execFile, spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { createServer } from "node:net";
import { basename, dirname, isAbsolute, resolve } from "node:path";
import { promisify } from "node:util";
import { configurationDigest, type M11RuntimeConfiguration } from "./m11-config.js";
import { verifyLocalReleasePackage } from "./m11-package.js";

const execFileAsync = promisify(execFile);
const COMPONENTS = ["control-plane", "local-bridge"] as const;
export type RuntimeComponent = (typeof COMPONENTS)[number];
export type RuntimePidRecord = Readonly<{ recordVersion: 1; component: RuntimeComponent; pid: number; executablePath: string; commandDigest: string; configurationDigest: string; processStartedAt: string; recordedAt: string }>;
export type ProcessIdentity = Readonly<{ pid: number; executablePath: string; commandDigest: string; processStartedAt: string }>;
export interface RuntimeProcessAdapter { inspect(pid: number): Promise<ProcessIdentity | null>; spawn(executable: string, args: readonly string[], environment: NodeJS.ProcessEnv): Promise<number>; terminateKnown(identity: ProcessIdentity): Promise<Readonly<{ terminated: boolean; proven: boolean; observedPids: readonly number[]; livePids: readonly number[] }>>; }

const canonical = (value: unknown): string => { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; };
const sha = (value: string): string => `sha256:${createHash("sha256").update(value).digest("hex")}`;
export const runtimeCommandDigest = (executable: string, args: readonly string[]): string => sha(canonical({ executable: resolve(executable), args: [...args] }));
const recordPath = (config: M11RuntimeConfiguration, component: RuntimeComponent): string => resolve(config.paths.managedDataRoot, "runtime", `${component}.pid.json`);
const validateRecord = (raw: unknown): RuntimePidRecord => { const value = raw as Partial<RuntimePidRecord>; if (value.recordVersion !== 1 || !COMPONENTS.includes(value.component as RuntimeComponent) || !Number.isSafeInteger(value.pid) || Number(value.pid) <= 0 || typeof value.executablePath !== "string" || !isAbsolute(value.executablePath) || typeof value.commandDigest !== "string" || !/^sha256:[0-9a-f]{64}$/u.test(value.commandDigest) || typeof value.configurationDigest !== "string" || !/^sha256:[0-9a-f]{64}$/u.test(value.configurationDigest) || typeof value.processStartedAt !== "string" || !Number.isFinite(Date.parse(value.processStartedAt)) || typeof value.recordedAt !== "string") throw new Error("runtime PID record is invalid"); return Object.freeze(value as RuntimePidRecord); };
export const readRuntimePidRecord = (config: M11RuntimeConfiguration, component: RuntimeComponent): RuntimePidRecord | null => { const path = recordPath(config, component); if (!existsSync(path)) return null; const bytes = readFileSync(path); if (bytes.byteLength > 16_384) throw new Error("runtime PID record exceeds its bound"); return validateRecord(JSON.parse(bytes.toString("utf8"))); };
const sameIdentity = (record: RuntimePidRecord, identity: ProcessIdentity): boolean => record.pid === identity.pid && resolve(record.executablePath).toLowerCase() === resolve(identity.executablePath).toLowerCase() && record.commandDigest === identity.commandDigest && Math.abs(Date.parse(record.processStartedAt) - Date.parse(identity.processStartedAt)) < 2_000;

const WINDOWS_INSPECT = String.raw`
$ErrorActionPreference='Stop'
$id=[int]$env:CHUBZ_RUNTIME_INSPECT_PID
$p=Get-CimInstance Win32_Process -Filter "ProcessId=$id" -ErrorAction SilentlyContinue
if($null -eq $p){[Console]::Out.Write('{}');exit 0}
$gp=Get-Process -Id $id -ErrorAction Stop
$command=[string]$p.CommandLine
$bytes=[Text.Encoding]::UTF8.GetBytes($command)
$hash=[Security.Cryptography.SHA256]::Create().ComputeHash($bytes)
[Console]::Out.Write((@{pid=$id;executablePath=[string]$p.ExecutablePath;commandDigest=('sha256:'+[BitConverter]::ToString($hash).Replace('-','').ToLowerInvariant());processStartedAt=$gp.StartTime.ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress))
`;
const WINDOWS_TERMINATE = String.raw`
$ErrorActionPreference='Stop'
$root=[int]$env:CHUBZ_RUNTIME_TERMINATE_PID
$snapshot=@(Get-CimInstance Win32_Process|Select-Object ProcessId,ParentProcessId)
$ids=New-Object 'System.Collections.Generic.HashSet[int]';[void]$ids.Add($root)
do{$before=$ids.Count;foreach($p in $snapshot){if($ids.Contains([int]$p.ParentProcessId)){[void]$ids.Add([int]$p.ProcessId)}}}while($ids.Count-ne$before)
$observed=@($ids|Sort-Object);foreach($id in @($observed|Sort-Object -Descending)){Stop-Process -Id $id -Force -ErrorAction SilentlyContinue}
$live=@($observed|Where-Object{Get-Process -Id $_ -ErrorAction SilentlyContinue})
[Console]::Out.Write((@{terminated=($live.Count-eq 0);proven=($observed-contains $root -and $live.Count-eq 0);observedPids=$observed;livePids=$live}|ConvertTo-Json -Compress))
`;

export class WindowsRuntimeProcessAdapter implements RuntimeProcessAdapter {
  public async inspect(pid: number): Promise<ProcessIdentity | null> { if (process.platform !== "win32" || !Number.isSafeInteger(pid) || pid <= 0) throw new Error("Windows process inspection is unavailable"); const { stdout } = await execFileAsync("powershell.exe", ["-NoLogo", "-NoProfile", "-NonInteractive", "-Command", WINDOWS_INSPECT], { encoding: "utf8", windowsHide: true, timeout: 10_000, maxBuffer: 64 * 1024, env: { ...process.env, CHUBZ_RUNTIME_INSPECT_PID: String(pid) } }); const value = JSON.parse(stdout) as Partial<ProcessIdentity>; return typeof value.pid === "number" && typeof value.executablePath === "string" && typeof value.commandDigest === "string" && typeof value.processStartedAt === "string" ? Object.freeze(value as ProcessIdentity) : null; }
  public async spawn(executable: string, args: readonly string[], environment: NodeJS.ProcessEnv): Promise<number> { if (!isAbsolute(executable) || args.some((arg) => arg.includes("\0") || arg.length > 16_384)) throw new Error("runtime process invocation is invalid"); const child = spawn(executable, [...args], { env: { ...environment }, shell: false, windowsHide: true, detached: true, stdio: "ignore" }); if (!child.pid) throw new Error("runtime process did not start"); child.unref(); return child.pid; }
  public async terminateKnown(identity: ProcessIdentity): Promise<Readonly<{ terminated: boolean; proven: boolean; observedPids: readonly number[]; livePids: readonly number[] }>> { const current = await this.inspect(identity.pid); if (!current || current.executablePath.toLowerCase() !== identity.executablePath.toLowerCase() || current.commandDigest !== identity.commandDigest || Math.abs(Date.parse(current.processStartedAt) - Date.parse(identity.processStartedAt)) >= 2_000) throw new Error("refusing to terminate an unrecognized or reused process identity"); const { stdout } = await execFileAsync("powershell.exe", ["-NoLogo", "-NoProfile", "-NonInteractive", "-Command", WINDOWS_TERMINATE], { encoding: "utf8", windowsHide: true, timeout: 15_000, maxBuffer: 64 * 1024, env: { ...process.env, CHUBZ_RUNTIME_TERMINATE_PID: String(identity.pid) } }); return Object.freeze(JSON.parse(stdout)); }
}

export async function portAvailable(host: "127.0.0.1" | "::1", port: number): Promise<boolean> { return new Promise((complete) => { const server = createServer(); server.unref(); server.once("error", () => complete(false)); server.listen({ host, port, exclusive: true }, () => server.close(() => complete(true))); }); }

export async function inspectRuntime(config: M11RuntimeConfiguration, adapter: RuntimeProcessAdapter): Promise<readonly Readonly<{ component: RuntimeComponent; status: "absent" | "running" | "stale" | "mismatch"; record: RuntimePidRecord | null }>[] > { const result = []; for (const component of COMPONENTS) { const record = readRuntimePidRecord(config, component); if (!record) { result.push(Object.freeze({ component, status: "absent" as const, record: null })); continue; } const identity = await adapter.inspect(record.pid); result.push(Object.freeze({ component, status: identity === null ? "stale" as const : sameIdentity(record, identity) ? "running" as const : "mismatch" as const, record })); } return Object.freeze(result); }

/** Removes only records whose exact PID is proven absent. Running and mismatched identities are never touched. */
export async function clearStaleRuntimePidRecords(config: M11RuntimeConfiguration, adapter: RuntimeProcessAdapter = new WindowsRuntimeProcessAdapter()): Promise<Record<string, unknown>> {
  const states = await inspectRuntime(config, adapter); if (states.some((entry) => entry.status === "running" || entry.status === "mismatch")) throw new Error("stale PID cleanup refused because a running or mismatched process identity exists"); const removed: RuntimeComponent[] = [];
  for (const entry of states) if (entry.status === "stale" && entry.record !== null) { const current = await adapter.inspect(entry.record.pid); if (current !== null) throw new Error("stale PID cleanup refused because process identity changed during inspection"); unlinkSync(recordPath(config, entry.component)); removed.push(entry.component); }
  return { removed, exactPidAbsenceProven: true, processesTerminated: false, unrelatedFilesRemoved: false };
}

const writeRecord = (config: M11RuntimeConfiguration, record: RuntimePidRecord): void => { const path = recordPath(config, record.component); mkdirSync(dirname(path), { recursive: true }); if (existsSync(path)) throw new Error(`${record.component} PID record already exists; inspect stale state before startup`); const temp = `${path}.${process.pid}.tmp`; const descriptor = openSync(temp, "wx", 0o600); try { writeFileSync(descriptor, `${canonical(record)}\n`); } finally { closeSync(descriptor); } renameSync(temp, path); };

const packagedEnvironment = (config: M11RuntimeConfiguration, packageRoot: string): NodeJS.ProcessEnv => {
  const verification = verifyLocalReleasePackage(packageRoot); if (!verification.verified) throw new Error("runtime startup refused because package integrity verification failed"); const manifestPath = resolve(packageRoot, "release", "release-manifest.json"); const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>; const version = manifest["applicationVersion"]; const commit = manifest["gitCommit"]; const timestamp = manifest["buildTimestamp"];
  if (typeof version !== "string" || !/^[0-9A-Za-z][0-9A-Za-z._-]{0,127}$/u.test(version) || typeof commit !== "string" || !/^[0-9a-f]{40}$/u.test(commit) || typeof timestamp !== "string" || !Number.isFinite(Date.parse(timestamp))) throw new Error("runtime release identity is invalid"); const secretName = /^environment:([A-Z][A-Z0-9_]{2,127})$/u.exec(config.controlPlane.sessionSecretRef)?.[1]; if (!secretName || process.env[secretName] === undefined) throw new Error("runtime secret reference is unavailable");
  const environment: NodeJS.ProcessEnv = { NODE_ENV: "production", CHUBZ_BUILD_VERSION: version, CHUBZ_BUILD_COMMIT: commit, CHUBZ_BUILD_TIMESTAMP: timestamp, [secretName]: process.env[secretName] }; for (const key of ["SystemRoot", "WINDIR", "ComSpec", "PATH", "PATHEXT", "TEMP", "TMP"] as const) if (process.env[key] !== undefined) environment[key] = process.env[key]; return environment;
};

export async function startRuntime(config: M11RuntimeConfiguration, configPath: string, packageRoot: string, adapter: RuntimeProcessAdapter = new WindowsRuntimeProcessAdapter()): Promise<Record<string, unknown>> { if (!isAbsolute(configPath)) throw new Error("runtime configuration path must be absolute"); const states = await inspectRuntime(config, adapter); if (states.some((entry) => entry.status !== "absent")) throw new Error("runtime startup refused because a running, stale, or mismatched PID record exists"); if (!await portAvailable(config.controlPlane.host, config.controlPlane.port)) throw new Error("runtime startup refused because the configured port is already in use"); const root = resolve(packageRoot); const runtimeEnvironment = packagedEnvironment(config, root); const entries = [{ component: "control-plane" as const, entry: resolve(root, "app", "control-plane.mjs") }, { component: "local-bridge" as const, entry: resolve(root, "app", "local-bridge.mjs") }]; for (const value of entries) if (!existsSync(value.entry)) throw new Error("runtime package entry is missing"); const started: RuntimePidRecord[] = [];
  try { for (const value of entries) { const args = [value.entry, "--config", resolve(configPath)]; const pid = await adapter.spawn(process.execPath, args, runtimeEnvironment); const identity = await adapter.inspect(pid); if (!identity) throw new Error("started runtime process identity is unavailable; outcome requires operator inspection"); const record: RuntimePidRecord = Object.freeze({ recordVersion: 1, component: value.component, pid, executablePath: identity.executablePath, commandDigest: identity.commandDigest, configurationDigest: configurationDigest(config), processStartedAt: identity.processStartedAt, recordedAt: new Date().toISOString() }); writeRecord(config, record); started.push(record); if (value.component === "control-plane" && adapter instanceof WindowsRuntimeProcessAdapter) { const readiness = await waitForReadiness(config, 30_000); if (readiness["ready"] !== true) throw new Error("Control Plane readiness was not established before Local Bridge startup"); } } }
  catch (failure) { let rollbackProven = true; for (const record of [...started].reverse()) { const identity = await adapter.inspect(record.pid); if (!identity || !sameIdentity(record, identity)) { rollbackProven = false; continue; } const result = await adapter.terminateKnown(identity); if (!result.proven) { rollbackProven = false; continue; } unlinkSync(recordPath(config, record.component)); } if (!rollbackProven) throw new Error("runtime startup failed and partial-start cleanup is not fully proven; inspect PID evidence before any retry"); throw failure; }
  return { started: started.map((entry) => ({ component: entry.component, pid: entry.pid })), permanentInstallation: false, serviceCreated: false, scheduledTaskCreated: false, registryModified: false, firewallModified: false };
}

export async function stopRuntime(config: M11RuntimeConfiguration, adapter: RuntimeProcessAdapter = new WindowsRuntimeProcessAdapter()): Promise<Record<string, unknown>> { const states = await inspectRuntime(config, adapter); if (states.some((entry) => entry.status === "stale" || entry.status === "mismatch")) throw new Error("runtime shutdown refused because PID evidence is stale or belongs to another process"); const results = []; for (const component of ["local-bridge", "control-plane"] as const) { const state = states.find((entry) => entry.component === component)!; if (state.status === "absent" || !state.record) { results.push({ component, status: "absent" }); continue; } const identity = await adapter.inspect(state.record.pid); if (!identity || !sameIdentity(state.record, identity)) throw new Error("runtime identity changed before shutdown"); const result = await adapter.terminateKnown(identity); if (!result.proven) throw new Error("runtime process-tree termination is unproven"); unlinkSync(recordPath(config, component)); results.push({ component, status: "terminated", observedPids: result.observedPids }); } return { results, knownProcessTreesOnly: true, stalePidFilesRemovedAutomatically: false, provenPidRecordsRemoved: true };
}

export async function waitForReadiness(config: M11RuntimeConfiguration, timeoutMs = 30_000): Promise<Record<string, unknown>> { if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 100 || timeoutMs > 120_000) throw new Error("readiness wait bound is invalid"); const deadline = Date.now() + timeoutMs; const url = `${config.controlPlane.allowedOrigin}/readyz`; do { try { const response = await fetch(url, { signal: AbortSignal.timeout(2_000) }); if (response.ok) return { ready: true, status: await response.json(), checkedAt: new Date().toISOString() }; } catch { /* retry only readiness observation, never execution */ } await new Promise((done) => setTimeout(done, 250)); } while (Date.now() < deadline); return { ready: false, reason: "readiness-timeout", checkedAt: new Date().toISOString() }; }

export function runtimePackageEntryName(path: string): string { return basename(path); }
